; SPDX-License-Identifier: GPL-3.0-or-later
; One pinned style for every platform. The UI draws its own controls from the
; token set (qml/Theme.qml); Basic keeps Qt Quick Controls from theming anything
; underneath them.
[Controls]
Style=Basic
