// SPDX-License-Identifier: GPL-3.0-or-later
/*
 * Copyright (C) 2026 by arancormonk <180709949+arancormonk@users.noreply.github.com>
 */

/*
 * X-macro lists of every action, label and predicate the menu tree references,
 * so test_ui_menu_tree_audit.c can link menu_items.c without the rest of the UI.
 * A new row with a new handler adds one line here; the linker says which.
 */
#ifndef DSD_NEO_TESTS_UI_TEST_UI_MENU_TREE_AUDIT_STUBS_H_
#define DSD_NEO_TESTS_UI_TEST_UI_MENU_TREE_AUDIT_STUBS_H_

/* ---- Generated from menu_items.c: every symbol the tree references. ----
   Regenerate with: grep -oE '\.(on_select|label_fn|is_enabled) = [a-z_0-9]+' src/ui/terminal/menu_items.c */

#define AUDIT_ACTIONS(X)                                                                                               \
    X(act_allow_toggle)                                                                                                \
    X(act_anytone_bp)                                                                                                  \
    X(act_auto_ppm_freeze)                                                                                             \
    X(act_auto_ppm_pwr_prompt)                                                                                         \
    X(act_auto_ppm_snr_prompt)                                                                                         \
    X(act_auto_ppm_zerohz_prompt)                                                                                      \
    X(act_auto_ppm_zeroppm_prompt)                                                                                     \
    X(act_channel_cycle)                                                                                               \
    X(act_config_load)                                                                                                 \
    X(act_config_load_profile)                                                                                         \
    X(act_config_save_as)                                                                                              \
    X(act_config_save_current)                                                                                         \
    X(act_config_save_default)                                                                                         \
    X(act_crc_relax)                                                                                                   \
    X(act_decode_mode)                                                                                                 \
    X(act_deemph_cycle)                                                                                                \
    X(act_dmr_le)                                                                                                      \
    X(act_dmr_reset)                                                                                                   \
    X(act_dsp_out)                                                                                                     \
    X(act_eh_next)                                                                                                     \
    X(act_eh_prev)                                                                                                     \
    X(act_eh_toggle_slot)                                                                                              \
    X(act_enc_lockout_clear)                                                                                           \
    X(act_env_editor)                                                                                                  \
    X(act_event_log_disable)                                                                                           \
    X(act_event_log_set)                                                                                               \
    X(act_export_p25_bandplan)                                                                                         \
    X(act_force_rc4)                                                                                                   \
    X(act_hangtime)                                                                                                    \
    X(act_history_cycle)                                                                                               \
    X(act_hpf_d_toggle)                                                                                                \
    X(act_hpf_toggle)                                                                                                  \
    X(act_import_chan)                                                                                                 \
    X(act_import_group)                                                                                                \
    X(act_import_p25_bandplan)                                                                                         \
    X(act_iq_dc_k_prompt)                                                                                              \
    X(act_ken_scr)                                                                                                     \
    X(act_keys_dec)                                                                                                    \
    X(act_keys_hex)                                                                                                    \
    X(act_lcw_toggle)                                                                                                  \
    X(act_lockout_slot1)                                                                                               \
    X(act_lockout_slot2)                                                                                               \
    X(act_lpf_toggle)                                                                                                  \
    X(act_m17_user_data)                                                                                               \
    X(act_mod_cycle)                                                                                                   \
    X(act_mod_p2_toggle)                                                                                               \
    X(act_mt)                                                                                                          \
    X(act_p25_enc_lockout)                                                                                             \
    X(act_p2_params)                                                                                                   \
    X(act_pbf_toggle)                                                                                                  \
    X(act_provoice_esk)                                                                                                \
    X(act_provoice_mode)                                                                                               \
    X(act_raw_wav)                                                                                                     \
    X(act_reset_eh)                                                                                                    \
    X(act_retevis_rc2)                                                                                                 \
    X(act_return_cc)                                                                                                   \
    X(act_rev_mute)                                                                                                    \
    X(act_rr_account_key)                                                                                              \
    X(act_rr_account_user)                                                                                             \
    X(act_rr_import)                                                                                                   \
    X(act_rr_library)                                                                                                  \
    X(act_scan_avoid)                                                                                                  \
    X(act_scan_avoid_clear)                                                                                            \
    X(act_scan_hold_toggle)                                                                                            \
    X(act_scan_voice_hold)                                                                                             \
    X(act_scan_voice_only)                                                                                             \
    X(act_scan_voice_qualify)                                                                                          \
    X(act_rt_sched)                                                                                                    \
    X(act_scan_toggle)                                                                                                 \
    X(act_set_audio_lpf)                                                                                               \
    X(act_set_input_warn)                                                                                              \
    X(act_set_p25_cc_grace)                                                                                            \
    X(act_set_p25_force_extra)                                                                                         \
    X(act_set_p25_force_margin)                                                                                        \
    X(act_set_p25_grant_voice)                                                                                         \
    X(act_set_p25_min_follow)                                                                                          \
    X(act_set_p25_p1_err_pct)                                                                                          \
    X(act_set_p25_p1_err_sec)                                                                                          \
    X(act_set_p25_vc_grace)                                                                                            \
    X(act_setmod_bw)                                                                                                   \
    X(act_sim_nocar)                                                                                                   \
    X(act_slot1_toggle)                                                                                                \
    X(act_slot2_toggle)                                                                                                \
    X(act_slot_pref)                                                                                                   \
    X(act_static_wav)                                                                                                  \
    X(act_tcp_prebuf_prompt)                                                                                           \
    X(act_tcp_rcvbuf_prompt)                                                                                           \
    X(act_tcp_rcvtimeo_prompt)                                                                                         \
    X(act_tcp_waitall)                                                                                                 \
    X(act_ted_gain_prompt)                                                                                             \
    X(act_tg_hold)                                                                                                     \
    X(act_toggle_cq)                                                                                                   \
    X(act_toggle_dsp_panel)                                                                                            \
    X(act_toggle_ftz_daz)                                                                                              \
    X(act_toggle_invert)                                                                                               \
    X(act_toggle_iq_dc)                                                                                                \
    X(act_toggle_iqbal)                                                                                                \
    X(act_toggle_payload)                                                                                              \
    X(act_toggle_ui_channels)                                                                                          \
    X(act_toggle_ui_compact)                                                                                           \
    X(act_toggle_ui_p25_affil)                                                                                         \
    X(act_toggle_ui_p25_callsign)                                                                                      \
    X(act_toggle_ui_p25_ccc)                                                                                           \
    X(act_toggle_ui_p25_ga)                                                                                            \
    X(act_toggle_ui_p25_iden)                                                                                          \
    X(act_toggle_ui_p25_metrics)                                                                                       \
    X(act_toggle_ui_p25_neighbors)                                                                                     \
    X(act_trunk_toggle)                                                                                                \
    X(act_tune_data)                                                                                                   \
    X(act_tune_group)                                                                                                  \
    X(act_tune_priv)                                                                                                   \
    X(act_tyt_ap)                                                                                                      \
    X(act_tyt_ep)                                                                                                      \
    X(act_vis_const)                                                                                                   \
    X(act_vis_const_norm)                                                                                              \
    X(act_vis_eye)                                                                                                     \
    X(act_vis_eye_color)                                                                                               \
    X(act_vis_eye_unicode)                                                                                             \
    X(act_vis_fsk)                                                                                                     \
    X(act_vis_spectrum)                                                                                                \
    X(act_window_freeze_toggle)                                                                                        \
    X(act_xor_ks)                                                                                                      \
    X(inv_dmr)                                                                                                         \
    X(inv_dpmr)                                                                                                        \
    X(inv_m17)                                                                                                         \
    X(inv_x2)                                                                                                          \
    X(io_enable_per_call_wav)                                                                                          \
    X(io_replay_last_symbol_bin)                                                                                       \
    X(io_rigctl_config)                                                                                                \
    X(io_save_symbol_capture)                                                                                          \
    X(io_select_call_alert_events)                                                                                     \
    X(io_set_gain_ana)                                                                                                 \
    X(io_set_gain_dig)                                                                                                 \
    X(io_set_input_volume)                                                                                             \
    X(io_set_pulse_in)                                                                                                 \
    X(io_set_pulse_out)                                                                                                \
    X(io_set_udp_out)                                                                                                  \
    X(io_stop_symbol_playback)                                                                                         \
    X(io_stop_symbol_saving)                                                                                           \
    X(io_tcp_direct_link)                                                                                              \
    X(io_toggle_call_alert)                                                                                            \
    X(io_toggle_cc_candidates)                                                                                         \
    X(io_toggle_cosine)                                                                                                \
    X(io_toggle_monitor)                                                                                               \
    X(io_toggle_mute_enc)                                                                                              \
    X(key_aes)                                                                                                         \
    X(key_basic)                                                                                                       \
    X(key_force_bp)                                                                                                    \
    X(key_hytera)                                                                                                      \
    X(key_rc4des)                                                                                                      \
    X(key_scrambler)                                                                                                   \
    X(lr_custom)                                                                                                       \
    X(lr_dsdp)                                                                                                         \
    X(lr_home)                                                                                                         \
    X(lr_off)                                                                                                          \
    X(rtl_restart)                                                                                                     \
    X(rtl_set_bw)                                                                                                      \
    X(rtl_set_dev)                                                                                                     \
    X(rtl_set_freq)                                                                                                    \
    X(rtl_set_gain)                                                                                                    \
    X(rtl_set_ppm)                                                                                                     \
    X(rtl_set_sql)                                                                                                     \
    X(rtl_set_vol)                                                                                                     \
    X(rtl_toggle_auto_ppm)                                                                                             \
    X(rtl_toggle_bias)                                                                                                 \
    X(rtl_toggle_rtltcp_autotune)                                                                                      \
    X(rtl_toggle_tuner_autogain)                                                                                       \
    X(switch_out_pulse)                                                                                                \
    X(switch_out_toggle_mute)                                                                                          \
    X(switch_to_pulse)                                                                                                 \
    X(switch_to_rtl)                                                                                                   \
    X(switch_to_symbol)                                                                                                \
    X(switch_to_udp)                                                                                                   \
    X(switch_to_wav)

#define AUDIT_LABELS(X)                                                                                                \
    X(lbl_allow)                                                                                                       \
    X(lbl_audio_lpf)                                                                                                   \
    X(lbl_auto_ppm_freeze)                                                                                             \
    X(lbl_auto_ppm_pwr)                                                                                                \
    X(lbl_auto_ppm_snr)                                                                                                \
    X(lbl_auto_ppm_zerohz)                                                                                             \
    X(lbl_auto_ppm_zeroppm)                                                                                            \
    X(lbl_call_alert)                                                                                                  \
    X(lbl_call_alert_events)                                                                                           \
    X(lbl_cosine)                                                                                                      \
    X(lbl_cqpsk_timing_bias)                                                                                           \
    X(lbl_crc_relax)                                                                                                   \
    X(lbl_current_input)                                                                                               \
    X(lbl_current_output)                                                                                              \
    X(lbl_decode_mode)                                                                                                 \
    X(lbl_deemph)                                                                                                      \
    X(lbl_dmr_le)                                                                                                      \
    X(lbl_dsp_panel)                                                                                                   \
    X(lbl_enc_lockout_clear)                                                                                           \
    X(lbl_event_log)                                                                                                   \
    X(lbl_ftz_daz)                                                                                                     \
    X(lbl_gain_ana)                                                                                                    \
    X(lbl_gain_dig)                                                                                                    \
    X(lbl_hangtime)                                                                                                    \
    X(lbl_history_mode)                                                                                                \
    X(lbl_history_slot)                                                                                                \
    X(lbl_hpf)                                                                                                         \
    X(lbl_hpf_d)                                                                                                       \
    X(lbl_input_volume)                                                                                                \
    X(lbl_input_warn)                                                                                                  \
    X(lbl_inv_dmr)                                                                                                     \
    X(lbl_inv_dpmr)                                                                                                    \
    X(lbl_inv_m17)                                                                                                     \
    X(lbl_inv_x2)                                                                                                      \
    X(lbl_invert_all)                                                                                                  \
    X(lbl_iq_dc)                                                                                                       \
    X(lbl_iq_dc_k)                                                                                                     \
    X(lbl_key_force_bp)                                                                                                \
    X(lbl_key_force_rc4)                                                                                               \
    X(lbl_key_hytera)                                                                                                  \
    X(lbl_lcw)                                                                                                         \
    X(lbl_lpf)                                                                                                         \
    X(lbl_lrrp_current)                                                                                                \
    X(lbl_m17_user_data)                                                                                               \
    X(lbl_modulation)                                                                                                  \
    X(lbl_monitor)                                                                                                     \
    X(lbl_mt)                                                                                                          \
    X(lbl_muting)                                                                                                      \
    X(lbl_onoff_cq)                                                                                                    \
    X(lbl_onoff_iqbal)                                                                                                 \
    X(lbl_out_mute)                                                                                                    \
    X(lbl_p25_cc_grace)                                                                                                \
    X(lbl_p25_enc_lockout)                                                                                             \
    X(lbl_p25_force_extra)                                                                                             \
    X(lbl_p25_force_margin)                                                                                            \
    X(lbl_p25_grant_voice)                                                                                             \
    X(lbl_p25_min_follow)                                                                                              \
    X(lbl_p25_p1_err_pct)                                                                                              \
    X(lbl_p25_p1_err_sec)                                                                                              \
    X(lbl_p25_vc_grace)                                                                                                \
    X(lbl_p25p2_mod_lock)                                                                                              \
    X(lbl_pbf)                                                                                                         \
    X(lbl_per_call_wav)                                                                                                \
    X(lbl_pref_cc)                                                                                                     \
    X(lbl_provoice_esk)                                                                                                \
    X(lbl_provoice_mode)                                                                                               \
    X(lbl_replay_last)                                                                                                 \
    X(lbl_rev_mute)                                                                                                    \
    X(lbl_rigctl)                                                                                                      \
    X(lbl_rr_account)                                                                                                  \
    X(lbl_rt_sched)                                                                                                    \
    X(lbl_rtl_auto_ppm)                                                                                                \
    X(lbl_rtl_bias)                                                                                                    \
    X(lbl_rtl_bw)                                                                                                      \
    X(lbl_rtl_freq)                                                                                                    \
    X(lbl_rtl_gain)                                                                                                    \
    X(lbl_rtl_ppm)                                                                                                     \
    X(lbl_rtl_rtltcp_autotune)                                                                                         \
    X(lbl_rtl_tuner_autogain)                                                                                          \
    X(lbl_rtl_vol)                                                                                                     \
    X(lbl_scan)                                                                                                        \
    X(lbl_scan_avoid_clear)                                                                                            \
    X(lbl_scan_hold)                                                                                                   \
    X(lbl_scan_voice_hold)                                                                                             \
    X(lbl_scan_voice_only)                                                                                             \
    X(lbl_scan_voice_qualify)                                                                                          \
    X(lbl_slot1)                                                                                                       \
    X(lbl_slot2)                                                                                                       \
    X(lbl_slotpref)                                                                                                    \
    X(lbl_stop_symbol_capture)                                                                                         \
    X(lbl_stop_symbol_playback)                                                                                        \
    X(lbl_sym_save)                                                                                                    \
    X(lbl_tcp)                                                                                                         \
    X(lbl_tcp_prebuf)                                                                                                  \
    X(lbl_tcp_rcvbuf)                                                                                                  \
    X(lbl_tcp_rcvtimeo)                                                                                                \
    X(lbl_tcp_waitall)                                                                                                 \
    X(lbl_ted_gain)                                                                                                    \
    X(lbl_tg_hold)                                                                                                     \
    X(lbl_toggle_payload)                                                                                              \
    X(lbl_trunk)                                                                                                       \
    X(lbl_tune_data)                                                                                                   \
    X(lbl_tune_group)                                                                                                  \
    X(lbl_tune_priv)                                                                                                   \
    X(lbl_ui_channels)                                                                                                 \
    X(lbl_ui_compact)                                                                                                  \
    X(lbl_ui_p25_affil)                                                                                                \
    X(lbl_ui_p25_callsign)                                                                                             \
    X(lbl_ui_p25_ccc)                                                                                                  \
    X(lbl_ui_p25_ga)                                                                                                   \
    X(lbl_ui_p25_iden)                                                                                                 \
    X(lbl_ui_p25_metrics)                                                                                              \
    X(lbl_ui_p25_neighbors)                                                                                            \
    X(lbl_vis_const)                                                                                                   \
    X(lbl_vis_const_norm)                                                                                              \
    X(lbl_vis_eye)                                                                                                     \
    X(lbl_vis_eye_color)                                                                                               \
    X(lbl_vis_eye_unicode)                                                                                             \
    X(lbl_vis_fsk)                                                                                                     \
    X(lbl_vis_spectrum)                                                                                                \
    X(lbl_window_freeze)

#define AUDIT_PREDICATES(X)                                                                                            \
    X(const_view_active)                                                                                               \
    X(eye_view_active)                                                                                                 \
    X(io_rtl_active)                                                                                                   \
    X(is_not_qpsk)                                                                                                     \
    X(is_ted_allowed)                                                                                                  \
    X(provoice_active)                                                                                                 \
    X(rr_feature_available)                                                                                            \
    X(rr_imports_available_and_feature)                                                                                \
    X(rr_key_prompt_offered_and_feature)                                                                               \
    X(scan_rotation_active)                                                                                            \
    X(trunk_enabled)

#endif /* DSD_NEO_TESTS_UI_TEST_UI_MENU_TREE_AUDIT_STUBS_H_ */
