#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate the full-chain I/Q decode fixtures in tests/fixtures/iq.

The fixtures are short cu8 baseband captures plus dsd-neo-iq metadata sidecars.
Replaying them with --iq-replay drives the complete chain (decimation, filtering,
discriminator/CQPSK timing, symbol slicer, frame sync, protocol layer), which is
what the DECODE_IQ_* CTest cases assert against.

Two source kinds feed the same output format:

  "iq"     the upstream recording already is complex baseband; it is resampled to
           48 kHz and requantized to cu8.
  "audio"  the upstream recording is FM discriminator audio with no I/Q. Because
           FM demodulation is invertible, the audio is treated as instantaneous
           frequency and integrated back into a complex baseband signal. The
           result exercises the same demodulation chain, but carries none of the
           original RF impairments (noise, fading, adjacent-channel energy).

Fixtures are committed, so this script is provenance and regeneration only -- it
is not run by CI and needs network access plus ffmpeg. Regenerated bytes are not
guaranteed bit-identical across ffmpeg versions; re-run the DECODE_IQ_* tests
after regenerating.

Usage:
    python3 tools/build_iq_fixtures.py [--out tests/fixtures/iq] [--cache .iq-cache]
"""

import argparse
import hashlib
import math
import os
import subprocess
import sys
import urllib.request
import zipfile

import numpy as np

SAMPLE_RATE_HZ = 48000
DSP_BW_KHZ = 48  # keeps demod rate at 48 kHz -> integer samples/symbol for every mode
DEFAULT_DEVIATION = 0.35  # remodulation deviation as a fraction of Nyquist

# Upstream sources. The Signal Identification Wiki publishes no explicit
# content license, so no CC claim is made for that material (short off-air
# excerpts redistributed for testing with attribution); the m17-fme sample is
# GPL. THIRD_PARTY.md is the authoritative attribution/licensing notice.
SOURCES = {
    "p25_c4fm_cc_if": "https://www.sigidwiki.com/images/4/4a/P25_C4FM-CC_BEE0014C_IF.wav",
    "p25_c4fm_vc_if": "https://www.sigidwiki.com/images/2/25/P25-C4FM-VC_IF.wav",
    "p25_cqpsk_cc_if": "https://www.sigidwiki.com/images/c/cb/P25_CQPSK-CC_920650D5_IF.wav",
    "p25_cqpsk_vc_if": "https://www.sigidwiki.com/images/a/ab/P25_CQPSK-VC_91FE5105_IF.wav",
    "p25_sacch": "https://www.sigidwiki.com/images/3/39/SACCH.mp3",
    "dmr_mototrbo": "https://www.sigidwiki.com/images/d/d2/DMRMOTOTRBO_Sound.mp3",
    "dmr_t3_cc": "https://www.sigidwiki.com/images/b/b8/DMR_Control_Channel_454580kHz_AF.mp3",
    "nxdn_iq_zip": "https://www.sigidwiki.com/images/0/03/NXDN_IQ.zip",
    "dpmr_zip": "https://www.sigidwiki.com/images/e/e0/DPMR.zip",
    "dstar": "https://www.sigidwiki.com/images/2/2e/DStar_Sound.mp3",
    "ysf": "https://www.sigidwiki.com/images/2/26/Yaesu_sys_fusion.wav",
    "edacs": "https://www.sigidwiki.com/images/a/a8/EDACS96_Sound.mp3",
    "m17": "https://raw.githubusercontent.com/lwvmobile/m17-fme/main/samples/m17_clear_voice_wav.wav",
}

# Sources contributed directly by users (issue attachments / file shares) with
# no stable download URL. Place the named file in the cache directory to
# regenerate the fixtures that depend on it; the pinned SHA-256 in SHA256SUMS
# still applies. Missing local sources skip their fixtures with a warning so
# the rest of the set can still be regenerated.
LOCAL_SOURCES = {
    # DSDPlus raw discriminator capture (96 kHz mono s16) of a Motorola Tier III
    # RAS TSCC: a CSBK-only control channel (C_ALOHA fill, no voice, no idle
    # bursts) using colour code 0. Contributed by the reporter of
    # https://github.com/arancormonk/dsd-neo/issues/348 in that issue thread.
    "dmr_t3_ras_cc": "dmr_t3_ras_cc.wav",
}

# SHA-256 of each upstream download, pinned so regeneration detects upstream
# changes or tampering. If an upstream file is legitimately replaced, re-verify
# the new content, update the hash here, and re-run the DECODE_IQ_* tests.
SHA256SUMS = {
    "p25_c4fm_cc_if": "2545836bfdae3f87c67ca24b23579bb568b955c8cff28d466e2ddc2f1978ccd3",
    "p25_c4fm_vc_if": "1c7132e96f16e410724c76aa40f090d1a965f2a47c8e3f205ccbba563f06f58c",
    "p25_cqpsk_cc_if": "39d02f22eab5f20558c8fd05664dbf650ff7884ea5ee2eac734112ad6b699762",
    "p25_cqpsk_vc_if": "baec0f488a0879bf61d6b999f3d8de7f976a3f987f31efa7935e8496d477e3a4",
    "p25_sacch": "27aa48510760ac78fcb88b8046ee0d3834e12ffd4406132af17ba6a714a60077",
    "dmr_mototrbo": "10c4e6f181cf1bf935681d988b4e8fb4df7d9f947c1d7b199938424f36345d91",
    "dmr_t3_cc": "f92e7ea484a95d2c712ed35a98f43fdab65e60dbedfb19ad22a6972a3cad5afa",
    "nxdn_iq_zip": "6d5e0607da23f32d1d2205ff75aea45338e9d0c9dfc7e70eb9b153a965022cd3",
    "dpmr_zip": "12512779b482bd48e113adec721ad9d160092fba87204ee0119e59bf56495b56",
    "dstar": "b419679d20bd31ab9738be2b3e300b98ec762ec05d2a93683df86ae3a9946001",
    "ysf": "607b9f9789cecc9ab1c7c204f869d10879a0d69b7b4ae60a132694e88d5476e0",
    "edacs": "c043bdbf7f8dfec2063cf8c98f87b6b6fc6f97a0a516cff2d971e2c46fdfd99f",
    "m17": "e841be537491fd6a71264bf8d4c5b54667c80a0be278d6332bb49156d7f1b4f7",
    "dmr_t3_ras_cc": "4950da56e384b939675744a70ac12ca38fe6d6e35a74870717ab56ffc8e3e23c",
}

# Members to extract from zipped sources.
ZIP_MEMBERS = {
    "nxdn_iq_zip": {"nxdn48_iq": "NXDN48 IQ.wav", "nxdn96_iq": "NXDN96 IQ.wav"},
    "dpmr_zip": {"dpmr_iq": "SDRSharp_20160101_231640Z_12kHz_IQ.wav"},
}

# name, source key, kind, start_s, duration_s, deviation (audio kind only)
FIXTURES = [
    ("p25p1_c4fm_cc", "p25_c4fm_cc_if", "iq", 0, 2, None),
    ("p25p1_c4fm_vc", "p25_c4fm_vc_if", "iq", 0, 3, None),
    ("p25p1_cqpsk_cc", "p25_cqpsk_cc_if", "iq", 0, 2, None),
    ("p25p1_cqpsk_vc", "p25_cqpsk_vc_if", "iq", 0, 2, None),
    ("p25p2_cc", "p25_sacch", "audio", 0, 2, 0.35),
    ("dmr_voice", "dmr_mototrbo", "audio", 0, 2, 0.35),
    ("dmr_t3_cc", "dmr_t3_cc", "audio", 0, 2, 0.35),
    # CSBK-only RAS TSCC with colour code 0: locks the confidence gate from
    # C_ALOHA traffic alone (no idle bursts, no voice) and exercises the -F RAS
    # CRC bypass. Regression coverage for issue #348.
    ("dmr_t3_ras_cc", "dmr_t3_ras_cc", "audio", 2, 2, 0.35),
    ("nxdn48", "nxdn48_iq", "iq", 0, 6, None),
    ("nxdn96", "nxdn96_iq", "iq", 0, 2, None),
    ("dpmr", "dpmr_iq", "iq", 0, 10, None),
    ("dstar", "dstar", "audio", 0, 4, 0.35),
    ("ysf", "ysf", "audio", 0, 6, 0.35),
    ("edacs", "edacs", "audio", 0, 2, 0.35),
    # The upstream sample is mostly impaired test transmissions; the clean voice
    # stream occupies only the final seconds, so cut the fixture from there. The
    # deviation stays near M17's real +/-2.4 kHz so the synthetic FM signal fits
    # the 12.5 kHz channel filter profile (0.15 * 24 kHz Nyquist = 3.6 kHz peak).
    ("m17", "m17", "audio", 19, 4.3, 0.15),
]

# Derived fixtures synthesized from already-committed fixtures (no network or
# ffmpeg needed; run with --derived-only to regenerate just these).
#
# Simulcast: a second ray of the same transmission arrives with a launch-time
# offset, an amplitude ratio, and a small carrier offset. The carrier offset
# sweeps the composite through constructive and destructive combining (the
# beat fading seen on real LSM simulcast systems), and the delay makes the
# channel frequency-selective (ISI). 3 samples at 48 kHz = 62.5 us, ~30% of a
# 4800-baud symbol; +1.5 Hz gives a 0.67 s beat so a 2 s fixture crosses at
# least two deep fades.
#
# name, source fixture, delay_samples, ray2 amplitude, ray2 CFO Hz, ray2 phase
DERIVED_SIMULCAST = [
    ("p25p1_cqpsk_cc_simulcast", "p25p1_cqpsk_cc", 3, 0.6, 1.5, 0.7),
]

# Receiver noise with the squelch open -- no signal at all, which is what a scanner sits on
# between transmissions. Protocols whose sync words are short enough for noise to reproduce
# used to decode this into RANs and voice (issue #398), so it is committed as a reject
# fixture. Deterministic from the seed; complex Gaussian, quantized without peak
# normalization so sigma stays where it is set rather than being scaled up to full scale.
#
# name, seed, duration_s, sigma (LSB of the cu8 range)
DERIVED_NOISE = [
    ("noise_floor", 398, 10.0, 16.0),
]

# A dPMR signal synthesized from the CCH reference vectors (issue #407).
#
# The one off-air dPMR recording available to this project carries no recoverable
# CCH: its Hamming syndromes are at the random rate and its 4FSK eye is closed, so
# nothing it produces is a decode, and no integrity check can be validated against
# it. This fixture is modulated from tests/protocol/dpmr/fixtures, the same vectors
# DPMR_REFERENCE_VECTORS decodes, so the tree has one dPMR sample that is correct
# by construction: every CCH CRC-7 in it passes.
#
# dPMR is 4FSK at 2400 baud, symbol deviations +/-1050 Hz and +/-350 Hz
# (ETSI TS 102 658). The dibit-to-deviation map is dsd-neo's own slicer convention
# (src/core/frames/dsd_dibit.c): 1 -> +3, 0 -> +1, 2 -> -1, 3 -> -3.
DPMR_SYNTH_NAME = "dpmr_synth"
DPMR_SYNTH_SEED = 407
DPMR_SYNTH_SYMBOL_RATE = 2400
DPMR_SYNTH_OUTER_DEVIATION_HZ = 1050.0
DPMR_SYNTH_LEAD_IN_S = 0.25
DPMR_SYNTH_FRAME_REPEATS = 30
DPMR_SYNTH_NOISE_SIGMA = 0.02
DPMR_DIBIT_TO_LEVEL = {1: 3.0, 0: 1.0, 2: -1.0, 3: -3.0}

METADATA_TEMPLATE = """{{
  "format": "dsd-neo-iq",
  "version": 1,
  "sample_format": "cu8",
  "iq_order": "IQ",
  "endianness": "none",
  "capture_stage": "post_mute_pre_widen",
  "sample_rate_hz": {sample_rate},
  "center_frequency_hz": 851375000,
  "capture_center_frequency_hz": 851375000,
  "ppm": 0,
  "tuner_gain_tenth_db": 270,
  "rtl_dsp_bw_khz": {bw_khz},
  "base_decimation": 1,
  "post_downsample": 1,
  "demod_rate_hz": {demod_rate},
  "offset_tuning_enabled": false,
  "fs4_shift_enabled": false,
  "combine_rotate_enabled": false,
  "muted_bytes_excluded": true,
  "contains_retunes": false,
  "capture_retune_count": 0,
  "source_backend": "rtl",
  "source_args": "fixture",
  "capture_started_utc": "1970-01-01T00:00:00Z",
  "data_file": "{data_file}",
  "data_bytes": {data_bytes},
  "capture_drops": 0,
  "capture_drop_blocks": 0,
  "input_ring_drops": 0,
  "notes": "generated by tools/build_iq_fixtures.py"
}}
"""


def verify_sha256(key, path):
    """Check path against the pinned hash in SHA256SUMS (which must exist)."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    actual = digest.hexdigest()
    expected = SHA256SUMS[key]
    if actual != expected:
        raise ValueError(
            f"SHA-256 mismatch for {key} ({path}):\n"
            f"  expected {expected}\n"
            f"  actual   {actual}\n"
            "Upstream content changed (or the cache is corrupt). Delete the cached "
            "file to re-download; if the change is legitimate, update SHA256SUMS "
            "and re-run the DECODE_IQ_* tests."
        )


def fetch(cache_dir, key, url):
    """Download url into cache_dir, returning the local path.

    Only the hard-coded https URLs in SOURCES are ever fetched; the scheme guard
    below rejects anything else so a local file:// or ftp:// path cannot be
    substituted by editing a source list entry. Every download (cached or fresh)
    is verified against the pinned SHA-256 in SHA256SUMS.
    """
    if not url.startswith("https://"):
        raise ValueError(f"refusing non-https fixture source for {key}: {url}")
    path = os.path.join(cache_dir, key + os.path.splitext(url)[1])
    if os.path.exists(path) and os.path.getsize(path) > 0:
        verify_sha256(key, path)
        return path
    # URLs come only from the SOURCES constant above and are guarded to https.
    req = urllib.request.Request(url, headers={"User-Agent": "dsd-neo-fixture-builder"})  # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
    with urllib.request.urlopen(req) as resp:  # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
        data = resp.read()
    with open(path, "wb") as handle:
        handle.write(data)
    verify_sha256(key, path)
    return path


def resolve_local(cache_dir, key):
    """Locate a user-contributed source in cache_dir, or None if absent."""
    path = os.path.join(cache_dir, LOCAL_SOURCES[key])
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        return None
    verify_sha256(key, path)
    return path


def extract_zip_members(cache_dir, key, archive_path):
    """Extract the members named in ZIP_MEMBERS[key], returning {name: path}."""
    out = {}
    with zipfile.ZipFile(archive_path) as zf:
        for name, member in ZIP_MEMBERS[key].items():
            dest = os.path.join(cache_dir, name + ".wav")
            if not os.path.exists(dest):
                with open(dest, "wb") as handle:
                    handle.write(zf.read(member))
            out[name] = dest
    return out


def ffmpeg_read(path, channels, start_s, duration_s):
    """Decode path to float32 PCM at SAMPLE_RATE_HZ with the requested channel count."""
    cmd = ["ffmpeg", "-v", "error"]
    if start_s:
        cmd += ["-ss", str(start_s)]
    cmd += ["-i", path]
    if duration_s:
        cmd += ["-t", str(duration_s)]
    cmd += ["-f", "f32le", "-ac", str(channels), "-ar", str(SAMPLE_RATE_HZ), "-"]
    proc = subprocess.run(cmd, capture_output=True, check=True)
    return np.frombuffer(proc.stdout, dtype=np.float32).astype(np.float64)


def load_iq(path, start_s, duration_s):
    raw = ffmpeg_read(path, 2, start_s, duration_s)
    return raw[0::2] + 1j * raw[1::2]


def remodulate(audio, deviation):
    """Integrate discriminator audio back into complex baseband (inverse FM demod)."""
    audio = audio - np.mean(audio)
    scale = np.percentile(np.abs(audio), 99.5)
    if scale <= 0.0:
        scale = 1.0
    freq = audio / scale * deviation
    phase = np.cumsum(freq) * math.pi
    return np.exp(1j * phase)


def to_cu8(samples, headroom=0.9, normalize=True):
    """Quantize complex baseband to interleaved unsigned 8-bit I/Q.

    normalize=False keeps the caller's amplitude, which matters for noise: scaling it to
    full scale would set the level from whichever sample happened to be the largest.
    """
    real = np.real(samples)
    imag = np.imag(samples)
    scale = headroom
    if normalize:
        peak = max(np.max(np.abs(real)), np.max(np.abs(imag)))
        if peak <= 0.0:
            peak = 1.0
        scale = headroom / peak
    interleaved = np.empty(len(samples) * 2)
    interleaved[0::2] = real * scale
    interleaved[1::2] = imag * scale
    return np.clip(np.round(interleaved * 127.5 + 127.5), 0, 255).astype(np.uint8)


def write_fixture(out_dir, name, samples, normalize=True):
    payload = to_cu8(samples, normalize=normalize)
    data_name = name + ".iq"
    data_path = os.path.join(out_dir, data_name)
    with open(data_path, "wb") as handle:
        handle.write(payload.tobytes())
    metadata = METADATA_TEMPLATE.format(
        sample_rate=SAMPLE_RATE_HZ,
        bw_khz=DSP_BW_KHZ,
        demod_rate=SAMPLE_RATE_HZ,
        data_file=data_name,
        data_bytes=len(payload),
    )
    with open(data_path + ".json", "w", encoding="utf-8") as handle:
        handle.write(metadata)
    return len(payload)


def load_cu8_fixture(path):
    """Read a committed cu8 fixture back into complex baseband."""
    raw = np.fromfile(path, dtype=np.uint8).astype(np.float64)
    centered = (raw - 127.5) / 127.5
    return centered[0::2] + 1j * centered[1::2]


def simulcast_two_ray(samples, delay_samples, amp2, cfo_hz, phase2):
    """Sum the signal with a delayed, attenuated, frequency-offset copy."""
    if delay_samples > 0:
        delayed = np.concatenate([np.zeros(delay_samples, dtype=samples.dtype), samples[:-delay_samples]])
    else:
        delayed = samples
    n = np.arange(len(samples))
    rotation = np.exp(1j * (2.0 * math.pi * cfo_hz * n / SAMPLE_RATE_HZ + phase2))
    return samples + amp2 * delayed * rotation


def build_noise(out_dir):
    """Write the open-squelch receiver-noise fixtures (issue #398)."""
    total = 0
    for name, seed, duration_s, sigma_lsb in DERIVED_NOISE:
        rng = np.random.default_rng(seed)
        count = int(round(duration_s * SAMPLE_RATE_HZ))
        sigma = sigma_lsb / 127.5
        samples = rng.normal(0.0, sigma, count) + 1j * rng.normal(0.0, sigma, count)
        written = write_fixture(out_dir, name, samples, normalize=False)
        total += written
        print(f"{name:28s} noise   {written // 1024:6d} KiB")
    return total


def load_dpmr_reference_vectors():
    """Import the dPMR CCH vector generator so fixture and unit test share one source."""
    import importlib.util

    path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..",
        "tests",
        "protocol",
        "dpmr",
        "fixtures",
        "generate_dpmr_reference_vectors.py",
    )
    spec = importlib.util.spec_from_file_location("dpmr_reference_vectors", os.path.normpath(path))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def dpmr_symbol_stream(vectors):
    """FS2 plus body dibits, alternating the two reference superframe parts."""
    frames = [vectors.build_frame(spec) for spec in vectors.FRAME_SPECS]
    vectors.self_check(frames)
    fs2 = [int(char) for char in vectors.FS2_SYMBOLS]

    dibits = []
    for repeat in range(DPMR_SYNTH_FRAME_REPEATS):
        frame = frames[repeat % len(frames)]
        dibits += fs2
        dibits += frame["body"]
    return dibits


def modulate_4fsk(dibits, rng):
    """Continuous-phase 4FSK, one symbol at a time, with a noise lead-in.

    Rectangular symbols keep the eye fully open: the point of this fixture is a
    signal whose CCH decodes exactly, not a realistic channel. Impairment belongs
    in derived fixtures, the way p25p1_cqpsk_cc_simulcast adds it.
    """
    sps = SAMPLE_RATE_HZ // DPMR_SYNTH_SYMBOL_RATE
    if SAMPLE_RATE_HZ % DPMR_SYNTH_SYMBOL_RATE:
        raise ValueError("dPMR symbol rate must divide the fixture sample rate")

    # Outer symbols sit at +/-1050 Hz, so one level step is a third of that.
    step_rad = 2.0 * math.pi * (DPMR_SYNTH_OUTER_DEVIATION_HZ / 3.0) / SAMPLE_RATE_HZ

    lead_in = int(round(DPMR_SYNTH_LEAD_IN_S * SAMPLE_RATE_HZ))
    freq = np.zeros(lead_in + (len(dibits) * sps))
    for index, dibit in enumerate(dibits):
        start = lead_in + (index * sps)
        freq[start : start + sps] = DPMR_DIBIT_TO_LEVEL[dibit] * step_rad

    samples = np.exp(1j * np.cumsum(freq))
    samples[:lead_in] = 0.0
    noise = rng.normal(0.0, DPMR_SYNTH_NOISE_SIGMA, len(samples)) + 1j * rng.normal(
        0.0, DPMR_SYNTH_NOISE_SIGMA, len(samples)
    )
    return samples + noise


def build_dpmr_synth(out_dir):
    """Write the synthetic dPMR fixture built from the CCH reference vectors (#407)."""
    vectors = load_dpmr_reference_vectors()
    dibits = dpmr_symbol_stream(vectors)
    rng = np.random.default_rng(DPMR_SYNTH_SEED)
    samples = modulate_4fsk(dibits, rng)
    written = write_fixture(out_dir, DPMR_SYNTH_NAME, samples)
    print(f"{DPMR_SYNTH_NAME:28s} synth   {written // 1024:6d} KiB")
    return written


def build_derived(out_dir):
    total = 0
    for name, source, delay_samples, amp2, cfo_hz, phase2 in DERIVED_SIMULCAST:
        source_path = os.path.join(out_dir, source + ".iq")
        samples = load_cu8_fixture(source_path)
        impaired = simulcast_two_ray(samples, delay_samples, amp2, cfo_hz, phase2)
        written = write_fixture(out_dir, name, impaired)
        total += written
        print(f"{name:28s} derived {written // 1024:6d} KiB")
    return total


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", default=os.path.join("tests", "fixtures", "iq"))
    parser.add_argument("--cache", default=".iq-fixture-cache")
    parser.add_argument(
        "--derived-only",
        action="store_true",
        help="only regenerate fixtures derived from committed ones (no network/ffmpeg)",
    )
    parser.add_argument(
        "--only",
        action="append",
        help="regenerate just the named fixture(s); other fixtures and their downloads are skipped",
    )
    args = parser.parse_args()

    os.makedirs(args.out, exist_ok=True)

    total = 0
    if not args.derived_only:
        os.makedirs(args.cache, exist_ok=True)

        selected = [entry for entry in FIXTURES if not args.only or entry[0] in args.only]
        needed = {entry[1] for entry in selected}

        resolved = {}
        for key, url in SOURCES.items():
            members = ZIP_MEMBERS.get(key)
            wanted = key in needed if members is None else any(member in needed for member in members)
            if not wanted:
                continue
            path = fetch(args.cache, key, url)
            if members:
                resolved.update(extract_zip_members(args.cache, key, path))
            else:
                resolved[key] = path
        for key in LOCAL_SOURCES:
            if key not in needed:
                continue
            path = resolve_local(args.cache, key)
            if path is not None:
                resolved[key] = path
                continue
            message = (
                f"local source for {key} not found; place the contributed file at "
                f"{os.path.join(args.cache, LOCAL_SOURCES[key])} (see LOCAL_SOURCES for provenance)"
            )
            if args.only:
                raise FileNotFoundError(message)
            print(f"WARNING: {message}; skipping dependent fixtures", file=sys.stderr)

        for name, source_key, kind, start_s, duration_s, deviation in selected:
            if source_key not in resolved:
                print(f"{name:28s} skipped (source {source_key} unavailable)")
                continue
            path = resolved[source_key]
            if kind == "iq":
                samples = load_iq(path, start_s, duration_s)
            else:
                audio = ffmpeg_read(path, 1, start_s, duration_s)
                samples = remodulate(audio, deviation or DEFAULT_DEVIATION)
            written = write_fixture(args.out, name, samples)
            total += written
            print(f"{name:28s} {kind:5s}   {written // 1024:6d} KiB")

    if not args.only:
        total += build_derived(args.out)
        total += build_noise(args.out)
        total += build_dpmr_synth(args.out)
    else:
        for entry in DERIVED_SIMULCAST + [(n,) for n, _, _, _ in DERIVED_NOISE] + [(DPMR_SYNTH_NAME,)]:
            if entry[0] in args.only:
                raise SystemExit(f"{entry[0]} is a derived fixture; regenerate it with --derived-only")
    print(f"total {total // 1024} KiB in {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
