// SPDX-License-Identifier: ISC
/*
 * Copyright (C) 2026 by arancormonk <180709949+arancormonk@users.noreply.github.com>
 */
/*-------------------------------------------------------------------------------
 * dsd_ncurses_printer.c
 * DSD-FME ncurses open, printer, and close
 *
 * ASCII art generated by:
 * https://fsymbols.com/generators/carty/
 *
 * LWVMOBILE
 * 2025-05 DSD-FME Florida Man Edition
 *
 * ilyacodes
 * 2024-03 EDACS-FME display improvements
 *-----------------------------------------------------------------------------*/

#include "dsd-neo/core/input_level.h"

#include <curses.h>
#include <dsd-neo/app_control/frontend.h>
#include <dsd-neo/app_control/history.h>
#include <dsd-neo/core/opts.h>
#include <dsd-neo/core/power.h>
#include <dsd-neo/core/state.h>
#include <dsd-neo/core/sync_patterns.h>
#include <dsd-neo/core/synctype_ids.h>
#include <dsd-neo/core/talkgroup_policy.h>
#include <dsd-neo/protocol/edacs/edacs_afs.h>
#include <dsd-neo/protocol/m17/m17_parse.h>
#include <dsd-neo/protocol/p25/p25_callsign.h>
#include <dsd-neo/protocol/p25/p25_trunk_sm.h>
#include <dsd-neo/ui/menu_core.h>
#include <dsd-neo/ui/ncurses.h>
#include <dsd-neo/ui/ncurses_dsp_display.h>
#include <dsd-neo/ui/ncurses_internal.h>
#include <dsd-neo/ui/ncurses_p25_display.h>
#include <dsd-neo/ui/ncurses_trunk_display.h>
#include <dsd-neo/ui/panels.h>
#include <dsd-neo/ui/ui_async.h>
#include <dsd-neo/ui/ui_prims.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "dsd-neo/core/opts_fwd.h"
#include "dsd-neo/core/safe_api.h"
#include "dsd-neo/core/secret_redaction.h"
#include "dsd-neo/core/state_fwd.h"
#include "dsd-neo/platform/platform.h"
#include "ui_key_status.h"
#include "ui_snr_readout.h"

#ifdef USE_RADIO
#include <dsd-neo/ui/keymap.h>
#include <dsd-neo/ui/ncurses_snr.h>
#include <dsd-neo/ui/ncurses_visualizers.h>
#endif

static int
ui_lookup_group_label(const dsd_state* state, unsigned long id, char* mode, size_t mode_sz, char* name,
                      size_t name_sz) {
    if (id == 0UL || id > UINT32_MAX) {
        if (mode && mode_sz > 0) {
            mode[0] = '\0';
        }
        if (name && name_sz > 0) {
            name[0] = '\0';
        }
        return 0;
    }
    return dsd_tg_policy_lookup_label(state, (uint32_t)id, mode, mode_sz, name, name_sz);
}

/* Small helpers to align key/value fields to a consistent value column. */
static inline void
ui_print_label_pad(const char* label) {
    const int value_col = 14; /* column (from label start) where values begin */
    int lab_len = (int)strlen(label);
    if (lab_len < 0) {
        lab_len = 0;
    }
    /* Draw the left border using current color (green when carrier active, cyan otherwise) */
    addch('|');
    addch(' ');
    addstr(label);
    addch(':');
    int need = value_col - (lab_len + 1); /* +1 for ':' */
    if (need < 1) {
        need = 1; /* at least one space after ':' */
    }
    for (int i = 0; i < need; i++) {
        addch(' ');
    }
}

static void ui_print_kv_line(const char* label, const char* fmt, ...) DSD_ATTR_FORMAT(printf, 2, 3);

static void
ui_print_kv_line(const char* label, const char* fmt, ...) {
    ui_print_label_pad(label);
    va_list ap;
    va_start(ap, fmt);
    vw_printw(stdscr, fmt, ap);
    va_end(ap);
    addch('\n');
}

enum { UI_SNR_DB_FIELD_WIDTH = 8 }; /* "-49.9 dB" */

static void
ui_print_snr_db_field(const char* value) {
    const char* s = (value != NULL && value[0] != '\0') ? value : "n/a";
    addstr(" SNR: ");
    addstr(s);
    addstr(" dB");
    int pad = UI_SNR_DB_FIELD_WIDTH - ((int)strlen(s) + 3);
    for (int i = 0; i < pad; i++) {
        addch(' ');
    }
}

static inline int
ui_eh_item_has_content(const Event_History* item) {
    if (item == NULL) {
        return 0;
    }
    return item->event_string[0] != '\0' || item->text_message[0] != '\0' || item->alias[0] != '\0'
           || item->gps_s[0] != '\0' || item->internal_str[0] != '\0';
}

static int
ui_audio_in_is_soapy(const dsd_opts* opts) {
    const char* dev = opts ? opts->audio_in_dev : NULL;
    if (!dev) {
        return 0;
    }
    return (strcmp(dev, "soapy") == 0) || (strncmp(dev, "soapy:", 6) == 0);
}

static int
ui_demod_symbol_rate_hz(const dsd_opts* opts, const dsd_state* state) {
    int sample_rate_hz = dsd_opts_current_input_timing_rate(opts);

#ifdef USE_RADIO
    if (opts && state && opts->audio_in_type == AUDIO_IN_RTL && state->rtl_ctx) {
        dsd_frontend_metrics metrics;
        (void)dsd_app_frontend_get_metrics(&metrics);
        /* RTL direct symbol paths feed one decoded symbol per sample; report the configured profile rate. */
        if ((metrics.output_kind == DSD_FRONTEND_RTL_OUTPUT_SYMBOL_CQPSK
             || metrics.output_kind == DSD_FRONTEND_RTL_OUTPUT_FSK_DISCRIMINATOR)
            && metrics.symbol_rate_hz > 0) {
            return metrics.symbol_rate_hz;
        }

        sample_rate_hz = (int)metrics.output_rate_hz;
    }
#endif

    if (sample_rate_hz <= 0) {
        sample_rate_hz = 48000;
    }

    if (!state || state->samplesPerSymbol <= 0) {
        return sample_rate_hz;
    }
    return (sample_rate_hz + (state->samplesPerSymbol / 2)) / state->samplesPerSymbol;
}

static const char* DMRBusrtTypes[32] = {
    "PI       ", "VLC      ", "TLC      ", "CSBK     ", "MBCH     ", "MBCC     ", "DATA     ",
    "R12D     ", "R34D     ", "IDLE     ", "R1_D     ", "ERR      ", "DUID ERR ", "R-S ERR  ",
    "CRC ERR  ", "NULL     ", "VOICE",     "         ", "INIT     ", "INIT     ",
    "PTT",      //20 MAC
    "VOICE",    //21 MAC_ACTIVE
    "HANGTIME", //22 MAC
    "PTT END",  //23 MAC
    "IDLE",     //24 MAC
    "HDU",
    "VOICE", //26 LDU1
    "VOICE", //27 LDU2
    "TDU/LC",    "TSBK",
    "SIGNAL", //MAC_SIGNAL
    "SIGNAL"  //MAC_SIGNAL

};

static void
ui_update_sync_and_edacs_tree(const dsd_state* state) {
    if (state == NULL) {
        return;
    }

    // Keep the last detected sync type available while carrier state changes.
    if (state->synctype != DSD_SYNC_NONE) {
        ncurses_last_synctype = state->synctype;
    }

    //EDACS Channel Tree
    if (DSD_SYNC_IS_EDACS(ncurses_last_synctype) && state->carrier == 1) {

        if (state->edacs_vc_lcn != -1) {
            edacs_channel_tree[state->edacs_vc_lcn][0] = ncurses_last_synctype;
            edacs_channel_tree[state->edacs_vc_lcn][1] = state->edacs_vc_lcn;
            edacs_channel_tree[state->edacs_vc_lcn][2] = state->lasttg;
            //EDACS standard does not provide source LIDs on channel update messages; instead, for the sake of display, let's
            //assume the prior source for a given LCN is still accurate, unless we have an updated one provided (or the call
            //type has changed under us).
            //
            //If you MUST have perfectly-accurate source LIDs, look at the logged CC messages yourself - incorrect source LIDs
            //may be displayed if we miss an initial call channel assignment.
            if (state->ea_mode == 1
                || (state->lastsrc != 0
                    || edacs_channel_tree[state->edacs_vc_lcn][4] != (unsigned long long)state->edacs_vc_call_type)) {
                edacs_channel_tree[state->edacs_vc_lcn][3] = state->lastsrc;
            }
            if (state->ea_mode == 0 && state->lastsrc == 0x800) { //this was from a grant update, so set this to 0
                edacs_channel_tree[state->edacs_vc_lcn][3] = 0;
            }
            edacs_channel_tree[state->edacs_vc_lcn][4] = state->edacs_vc_call_type;
            edacs_channel_tree[state->edacs_vc_lcn][5] = time(NULL);
        }
    }
}

static void
ui_render_basic_input_sources(dsd_opts* opts) {
    if (opts->audio_in_type == AUDIO_IN_PULSE) {
        printw("| Pulse Signal Input:  %i kHz; %i Ch; ", opts->pulse_digi_rate_in / 1000, opts->pulse_digi_in_channels);
        if (opts->pa_input_idx[0] != 0) {
            printw(" D: %s;", opts->pa_input_idx);
        }
        if (opts->use_rigctl == 1) {
            printw("RIG: %s:%d; ", opts->tcp_hostname, opts->rigctlportno);
        }
        printw(" IV: %iX;", opts->input_volume_multiplier);
        printw("\n");
    }

    if (opts->audio_in_type == AUDIO_IN_SYMBOL_BIN) {
        printw("| Dibit Bin Input: %s \n", opts->audio_in_dev);
    }

    if (opts->audio_in_type == AUDIO_IN_SYMBOL_FLT) {
        printw("| Symbol Float Input: %s \n", opts->audio_in_dev);
    }

    if (opts->m17decoderip == 1 && opts->udp_sockfd) {
        printw("| M17 UDP IP Frame Input: %s:%d \n", opts->m17_hostname, opts->m17_portno);
    }

    if (opts->audio_in_type == AUDIO_IN_TCP) {
        printw("| TCP Signal Input: %s:%d; %d kHz; 1 Ch; ", opts->tcp_hostname, opts->tcp_portno,
               opts->wav_sample_rate / 1000);
        if (opts->use_rigctl == 1) {
            printw("RIG: %s:%d; ", opts->tcp_hostname, opts->rigctlportno);
        }
        printw(" IV: %iX;", opts->input_volume_multiplier);
        printw("\n");
    }

    if (opts->audio_in_type == AUDIO_IN_UDP) {
        const char* host = (opts->udp_in_bindaddr[0] ? opts->udp_in_bindaddr : "127.0.0.1");
        printw("| UDP Signal Input: %s:%d; %d kHz; 1 Ch; ", host, opts->udp_in_portno, opts->wav_sample_rate / 1000);
        if (opts->udp_in_packets == 0ULL) {
            printw("[Waiting]");
        } else {
            printw("Pkts:%llu Drops:%llu", (unsigned long long)opts->udp_in_packets,
                   (unsigned long long)opts->udp_in_drops);
        }
        printw(" IV: %iX;", opts->input_volume_multiplier);
        printw("\n");
    }

    if (opts->audio_in_type == AUDIO_IN_WAV) {
        printw("| WAV Audio Input: %s; %d kHz; ", opts->audio_in_dev, opts->wav_sample_rate);
        printw(" IV: %iX;\n", opts->input_volume_multiplier);
    }

    if (opts->audio_in_type == AUDIO_IN_STDIN) {
        printw("| STDIN Standard Input: - Menu Disabled when using STDIN!\n");
    }
}

static void
ui_print_rtl_gain_field(dsd_opts* opts) {
#ifndef USE_RADIO
    if (opts->rtl_gain_value == 0) {
        printw(" G: AGC;");
    } else {
        printw(" G: %idB;", opts->rtl_gain_value);
    }
    return;
#else
    /* Show applied tuner gain when available (actual driver value),
       otherwise fall back to requested value. */
    dsd_frontend_metrics metrics;
    (void)dsd_app_frontend_get_metrics(&metrics);
    if (metrics.tuner_gain_valid) {
        if (metrics.tuner_gain_is_auto) {
            printw(" G: AGC;");
        } else {
            int gdB = (metrics.tuner_gain_tenth_db >= 0) ? (metrics.tuner_gain_tenth_db + 5) / 10
                                                         : (metrics.tuner_gain_tenth_db - 5) / 10;
            printw(" G: %idB;", gdB);
        }
    } else {
        if (opts->rtl_gain_value == 0) {
            printw(" G: AGC;");
        } else {
            printw(" G: %idB;", opts->rtl_gain_value);
        }
    }
#endif
}

static void
ui_print_rtl_ppm_field(const dsd_opts* opts) {
    (void)opts;
    dsd_frontend_metrics metrics;
    (void)dsd_app_frontend_get_metrics(&metrics);
    printw(" PPM: %i;", metrics.requested_ppm); //Adjust manually now with { and }
}

static void
ui_print_rtl_auto_ppm_status_values(int enabled, int locked, int locked_ppm, double snr_db, double df_hz,
                                    int step_dir) {
    if (!enabled) {
        printw("\n| Auto PPM: Off");
    } else if (locked) {
        printw("\n| Auto PPM: Locked (PPM: %d)", locked_ppm);
    } else {
        printw("\n| Auto PPM: On; SNR: %.1f dB; df: %.1f Hz; step: %s;", snr_db, df_hz,
               (step_dir > 0)   ? "+1"
               : (step_dir < 0) ? "-1"
                                : "hold");
    }
}

static void
ui_print_rtl_auto_ppm_status(void) {
#ifndef USE_RADIO
    ui_print_rtl_auto_ppm_status_values(0, 0, 0, -100.0, 0.0, 0);
#else
    /* Show carrier/error-based auto PPM status snapshot */
    dsd_frontend_metrics metrics;
    (void)dsd_app_frontend_get_metrics(&metrics);
    ui_print_rtl_auto_ppm_status_values(metrics.auto_ppm_enabled, metrics.auto_ppm_locked, metrics.auto_ppm_locked_ppm,
                                        metrics.auto_ppm_snr_db, metrics.auto_ppm_df_hz, metrics.auto_ppm_step_dir);
#endif
}

static void
ui_render_rtl_input_source(dsd_opts* opts, dsd_state* state) {
    if (opts->audio_in_type == AUDIO_IN_RTL) {
        int soapy_input = ui_audio_in_is_soapy(opts);
        if (soapy_input) {
            if (strncmp(opts->audio_in_dev, "soapy:", 6) == 0 && opts->audio_in_dev[6] != '\0') {
                printw("| SoapySDR: %s;", opts->audio_in_dev + 6);
            } else {
                printw("| SoapySDR;");
            }
        } else {
            printw("| RTL: %d;", opts->rtl_dev_index);
        }
        ui_print_rtl_gain_field(opts);
        printw(" Mon: %iX;", opts->rtl_volume_multiplier);
        ui_print_rtl_ppm_field(opts);
        printw(" SQL: %.1f dB;", pwr_to_dB(opts->rtl_squelch_level));
        printw(" DSP-BW: %i kHz;", opts->rtl_dsp_bw_khz);
        printw(" FRQ: %i;", opts->rtlsdr_center_freq);
        ui_print_rtl_auto_ppm_status();
        if (!soapy_input && opts->rtl_udp_port != 0) {
            printw("\n| External RTL Tuning on UDP: %s:%i", opts->rtl_udp_bindaddr, opts->rtl_udp_port);
        }
        printw("\n");
        /* Show compact DSP status directly above audio sections (optional) */
        if (opts->frontend_display.show_dsp_panel) {
            print_dsp_status(opts, state);
        }
        /* Signal quality is shown inline above; no duplicate line here. */
    }
}

static void
ui_render_input_level_status(const dsd_state* state) {
    if (!state || state->input_level.source == DSD_INPUT_LEVEL_SOURCE_UNKNOWN
        || state->input_level.sample_count == 0U) {
        return;
    }
    const dsd_input_level_snapshot* level = &state->input_level;
    printw("| %s: %s rms %.1f dBFS peak %.1f dBFS clip %.1f%%", dsd_input_level_display_label(level->source),
           dsd_input_level_status_label(level->status), level->rms_dbfs, level->peak_dbfs, level->clip_pct);
    if (level->status == DSD_INPUT_LEVEL_LOW) {
        printw(" %s", dsd_input_level_source_is_rf(level->source) ? "raise RF gain if signal is present"
                                                                  : "raise source/input volume if signal is present");
    } else if (level->status == DSD_INPUT_LEVEL_HOT || level->status == DSD_INPUT_LEVEL_CLIPPING) {
        printw(" %s", dsd_input_level_source_is_rf(level->source) ? "lower RF gain or add filtering/attenuation"
                                                                  : "lower source/input volume");
    }
    printw("\n");
}

static void
ui_render_input_sources_block(dsd_opts* opts, dsd_state* state) {
    ui_render_basic_input_sources(opts);
    ui_render_rtl_input_source(opts, state);
    ui_render_input_level_status(state);
}

static void
ui_render_pulse_digital_output(const dsd_opts* opts, const dsd_state* state) {
    if (opts->audio_out_type == 0 && opts->analog_only == 0) {
        printw("| Pulse Digital Output: %i kHz; %i Ch; G: %02.0f%%", opts->pulse_digi_rate_out / 1000,
               opts->pulse_digi_out_channels, state->aout_gain * 2);
        if (opts->pulse_digi_out_channels == 2) {
            printw(" G: %02.0f%%", state->aout_gainR * 2);
        }
        if (opts->floating_point == 1) {
            printw(" FLOAT: %02.0f%%;", opts->audio_gain * 2);
        }
        if (opts->audio_gain == 0) {
            printw(" (+|-) Auto  ");
        }
        if (opts->audio_gain > 0) {
            printw(" (+|-) Manual");
        }
        if (opts->use_hpf_d == 1) {
            printw(" HPF");
        }
        if (opts->call_alert == 1) {
            printw(" *CA!"); //Call Alert
        }
        if (opts->pa_output_idx[0] != 0) {
            printw(" D: %s;", opts->pa_output_idx);
        }

        printw(" \n");
    }
}

static void
ui_render_pulse_analog_output(const dsd_opts* opts) {
    if (opts->audio_out_type == 0 && (opts->frame_provoice == 1 || opts->monitor_input_audio == 1)) {
        printw("| Pulse Analog Output: %i kHz; %i Ch; G: %02.0f%% (/|*) ", opts->pulse_raw_rate_out / 1000,
               opts->pulse_raw_out_channels, opts->audio_gainA);
        if (opts->audio_gainA == 0.0f) {
            printw("Auto   ");
        } else {
            printw("Manual ");
        }
        if (opts->audio_in_type != AUDIO_IN_RTL) {
            printw("PWR: %.1f dB; ", pwr_to_dB(opts->rtl_pwr));
        }
        if (opts->use_lpf == 1) {
            printw("F: |LP|");
        } else {
            printw("F: |  |");
        }
        if (opts->use_hpf == 1) {
            printw("HP|");
        } else {
            printw("  |");
        }
        if (opts->use_pbf == 1) {
            printw("PB|");
        } else {
            printw("  |");
        }
        if (opts->pa_output_idx[0] != 0) {
            printw(" D: %s;", opts->pa_output_idx);
        }
        printw(" \n");
    }
}

static void
ui_render_udp_output(const dsd_opts* opts, const dsd_state* state) {
    if (opts->audio_out_type == 8) {
        printw("| UDP Digital Output: %s:%d; %d kHz %d Ch; %02.0f%%", opts->udp_hostname, opts->udp_portno,
               opts->pulse_digi_rate_out / 1000, opts->pulse_digi_out_channels, state->aout_gain * 2);
        if (opts->pulse_digi_out_channels == 2) {
            printw(" G: %02.0f%%", state->aout_gainR * 2);
        }
        if (opts->audio_gain == 0) {
            printw(" (+/-) Auto  ");
        }
        if (opts->audio_gain > 0) {
            printw(" (+/-) Manual");
        }
        if (opts->use_hpf_d == 1) {
            printw(" HPF");
        }
        if (opts->call_alert == 1) {
            printw(" *CA!"); //Call Alert
        }
        printw(" \n");
        if (opts->udp_sockfdA != 0) //Analog Output on udp port +2
        {
            printw("| UDP Analog Output: %s:%d; 48 kHz 1 Ch; G: %02.0f%% (/|*) ", opts->udp_hostname,
                   opts->udp_portno + 2, opts->audio_gainA);
            if (opts->audio_gainA == 0.0f) {
                printw("A ");
            } else {
                printw("M ");
            }
            if (opts->audio_in_type != AUDIO_IN_RTL) {
                printw("PWR: %.1f dB; ", pwr_to_dB(opts->rtl_pwr));
            }
            if (opts->use_lpf == 1) {
                printw("F: |LP|");
            } else {
                printw("F: |  |");
            }
            if (opts->use_hpf == 1) {
                printw("HP|");
            } else {
                printw("  |");
            }
            if (opts->use_pbf == 1) {
                printw("PB|");
            } else {
                printw("  |");
            }
            printw(" \n");
        }
    }
}

static void
ui_render_audio_output_block(const dsd_opts* opts, const dsd_state* state) {
    ui_render_pulse_digital_output(opts, state);
    ui_render_pulse_analog_output(opts);
    ui_render_udp_output(opts, state);
}

static void
ui_render_m17_encoder_status(const dsd_opts* opts, const dsd_state* state) {
    if (opts->m17encoder == 1) {
        printw("| M17 Encoder:");
        if (state->m17encoder_tx == 1 && state->m17_vox == 0) {
            printw(" Toggle TX (\\) On ;");
        }
        if (state->m17encoder_tx == 0 && state->m17_vox == 0) {
            printw(" Toggle TX (\\) Off;");
        }
        if (state->m17_vox == 1) {
            printw(" Vox Mode;");
        }
        printw(" Input Gain (/|*): %02.0f%% ", opts->audio_gainA);

        if (opts->use_lpf == 1) {
            printw("F: |LP|");
        } else {
            printw("F: |  |");
        }
        if (opts->use_hpf == 1) {
            printw("HP|");
        } else {
            printw("  |");
        }
        if (opts->use_pbf == 1) {
            printw("PB|");
        } else {
            printw("  |");
        }
        if (opts->audio_in_type != AUDIO_IN_RTL && state->m17_vox == 1) {
            printw(" SQL: %.1f : %.1f dB;", pwr_to_dB(opts->rtl_pwr), pwr_to_dB(opts->rtl_squelch_level));
        }
        printw("\n");
    }
}

static void
ui_render_file_output_status(const dsd_opts* opts) {
    if (opts->m17_use_ip == 1) {
        printw("| M17 UDP IP Frame Output: %s:%d \n", opts->m17_hostname, opts->m17_portno);
    }

    if (opts->mbe_out_dir[0] != 0 && opts->dmr_stereo == 0) {
        printw("| Writing MBE data files to directory %s\n", opts->mbe_out_dir);
    }

    if (opts->wav_out_raw) {
        printw("| Raw Audio Output: %s\n", opts->wav_out_file_raw);
    }

    if (opts->symbol_out_f) //don't display when not actively capturing
    {
        printw("| Symbol Bin Output: %s\n", opts->symbol_out_file);
    }

    if (opts->dmr_stereo_wav == 0 && opts->wav_out_file[0] != 0) {
        printw("| Decoded WAV Output: %s\n", opts->wav_out_file);
    }

    //new Per Call setup would just be random names until closed,
    //so no need to show, and will be in the event history anyways
    if (opts->dmr_stereo_wav == 1) {
        printw("| Per Call Wav File Enabled to Directory: %s \n", opts->wav_out_dir);
    }
}

static void
ui_render_encoder_and_file_outputs(const dsd_opts* opts, const dsd_state* state) {
    ui_render_m17_encoder_status(opts, state);
    ui_render_file_output_status(opts);
}

static void DSD_ATTR_UNUSED
ui_render_trunking_call_filters_pretty(const dsd_opts* opts) {
    printw("| Trunking -");
    if (opts->trunk_tune_group_calls == 0) {
        attron(COLOR_PAIR(2));
    }
    printw(" Group(g)");
    attron(COLOR_PAIR(4));
    if (opts->trunk_tune_private_calls == 0) {
        attron(COLOR_PAIR(2));
    }
    printw(" Private(u)");
    attron(COLOR_PAIR(4));
    if (opts->trunk_tune_data_calls == 0) {
        attron(COLOR_PAIR(2));
    }
    printw(" Data(d)");
    attron(COLOR_PAIR(4));
    if (opts->trunk_tune_enc_calls == 0) {
        attron(COLOR_PAIR(2));
    }
    printw(" Encrypted(e)");
    attron(COLOR_PAIR(4));
    printw(" Calls");
    if (opts->trunk_use_allow_list == 1) {
        printw(" - White List Mode\n");
    } else {
        printw(" - Black List Mode\n");
    }
}

#ifndef PRETTY_COLORS
static void
ui_render_trunking_call_filters_plain(const dsd_opts* opts) {
    printw("| Trunking -");
    printw((opts->trunk_tune_group_calls == 0) ? " group(g)" : " GROUP(g)");
    printw((opts->trunk_tune_private_calls == 0) ? " private(u)" : " PRIVATE(u)");
    printw((opts->trunk_tune_data_calls == 0) ? " data(d)" : " DATA(d)");
    printw((opts->trunk_tune_enc_calls == 0) ? " encrypted(e)" : " ENCRYPTED(e)");
    printw(" Calls");
    if (opts->trunk_use_allow_list == 1) {
        printw(" - White List Mode\n");
    } else {
        printw(" - Black List Mode\n");
    }
}
#endif

static void
ui_render_trunking_call_filters(const dsd_opts* opts) {
    if (!(opts->trunk_enable == 1 && (opts->use_rigctl == 1 || opts->audio_in_type == AUDIO_IN_RTL))) {
        return;
    }
#ifdef PRETTY_COLORS
    ui_render_trunking_call_filters_pretty(opts);
#else
    ui_render_trunking_call_filters_plain(opts);
#endif
}

static void
ui_render_edacs_tg_hold(dsd_state* state) {
    if (state->tg_hold == 0) {
        return;
    }

    int a = (state->tg_hold >> state->edacs_a_shift) & state->edacs_a_mask;
    int f = (state->tg_hold >> state->edacs_f_shift) & state->edacs_f_mask;
    int s = state->tg_hold & state->edacs_s_mask;
    if (state->ea_mode == 1) {
        printw("\n|  \\TG HOLD: %d; ", state->tg_hold);
        return;
    }

    char afs_str[8];
    getAfsString(state, afs_str, a, f, s);
    printw("\n|  \\TG HOLD: %d [%s]; ", state->tg_hold, afs_str);
}

#ifdef PRETTY_COLORS
static void
ui_render_edacs_mode_toggles_pretty(dsd_state* state) {
    printw("| \\--EDACS -");
    if (state->ea_mode == -1) {
        attron(COLOR_PAIR(2));
        printw(" Standard/Network");
        printw(" Extended Address");
        attron(COLOR_PAIR(4));
    } else if (state->ea_mode == 0) {
        printw(" Standard/Network");
        attron(COLOR_PAIR(2));
        printw(" Extended Address");
        attron(COLOR_PAIR(4));
    } else if (state->ea_mode == 1) {
        attron(COLOR_PAIR(2));
        printw(" Standard/Network");
        attron(COLOR_PAIR(4));
        printw(" Extended Address");
    }
    printw(" Mode (S);");
    printw(" ESK: %02X", state->esk_mask);
    printw(" (A);");
    if (state->ea_mode == 0) {
        printw(" AFS: %d:%d:%d;", state->edacs_a_bits, state->edacs_f_bits, state->edacs_s_bits);
    }
    ui_render_edacs_tg_hold(state);
    attron(COLOR_PAIR(4));
    printw("\n");
}
#else
static void
ui_render_edacs_mode_toggles_plain(dsd_state* state) {
    printw("| \\--EDACS -");
    if (state->ea_mode == -1) {
        printw(" standard/network");
        printw(" extended address");
    } else if (state->ea_mode == 0) {
        printw(" STANDARD/NETWORK");
        printw(" extended address");
    } else if (state->ea_mode == 1) {
        printw(" standard/network");
        printw(" EXTENDED ADDRESS");
    }
    printw(" Mode (S);");
    printw(" ESK: %02X", state->esk_mask);
    printw(" (A) Toggle; ");
    if (state->ea_mode == 0) {
        printw(" AFS: %d:%d:%d;", state->edacs_a_bits, state->edacs_f_bits, state->edacs_s_bits);
    }
    ui_render_edacs_tg_hold(state);
    printw("\n");
}
#endif

static void
ui_render_edacs_mode_toggles(const dsd_opts* opts, dsd_state* state) {
    //print additional information for EDACS modes and toggles
    if (!(opts->trunk_enable == 1 && opts->frame_provoice == 1)) {
        return;
    }
#ifdef PRETTY_COLORS
    ui_render_edacs_mode_toggles_pretty(state);
#else //set on to UPPER CASE, off to lower case
    ui_render_edacs_mode_toggles_plain(state);
#endif
}

static void
ui_render_trunking_and_edacs_toggles(const dsd_opts* opts, dsd_state* state) {
    ui_render_trunking_call_filters(opts);
    ui_render_edacs_mode_toggles(opts, state);
}

static const char*
ui_format_hytera_key(char* key_text, size_t key_text_size, const dsd_state* state, int show_keys,
                     unsigned int segment_count) {
    const unsigned long long segments[4] = {state->K1, state->K2, state->K3, state->K4};
    if (segment_count == 2U || segment_count == 4U) {
        return dsd_secret_format_u64_segments(key_text, key_text_size, show_keys, segments, segment_count);
    }
    return dsd_secret_format_hex(key_text, key_text_size, show_keys, state->K1 & 0xFFFFFFFFFFULL, 10U, 0);
}

static void
ui_render_hytera_loaded_key_status(const dsd_state* state, int show_keys) {
    unsigned int segment_count = ui_hytera_key_segment_count(state);
    if (segment_count == 0U) {
        return;
    }

    char key_text[68];
    const char* label = (segment_count == 1U) ? "Hytera BP Key Loaded (not forced)" : "Hytera Key Loaded (not forced)";
    printw("| %s: %s \n", label, ui_format_hytera_key(key_text, sizeof key_text, state, show_keys, segment_count));
}

static void
ui_render_forced_key_status_dmr(const dsd_state* state, int show_keys) {
    if (state->R != 0) {
        char key_text[16];
        printw("| Forcing Key Priority -- NXDN Sc Key: %s \n",
               dsd_secret_format_decimal(key_text, sizeof key_text, show_keys, state->R, 5U));
    }
    if (state->K != 0) {
        char key_text[16];
        printw("| Forcing Key Priority -- Moto BP Key: %s \n",
               dsd_secret_format_decimal(key_text, sizeof key_text, show_keys, state->K, 3U));
    }
    unsigned int hytera_segment_count = ui_hytera_key_segment_count(state);
    if (hytera_segment_count != 0U) {
        char key_text[68];
        const char* label = (hytera_segment_count == 1U) ? "Hytera BP Key" : "Hytera Key";
        printw("| Forcing Key Priority -- %s: %s \n", label,
               ui_format_hytera_key(key_text, sizeof key_text, state, show_keys, hytera_segment_count));
    }
    if (state->K != 0 && hytera_segment_count != 0U) {
        printw("| Warning! Multiple DMR Key Types Loaded! \n"); //warning may not be required
    }
}

static void
ui_render_forced_key_status_rc4(const dsd_state* state, int show_keys) {
    if (state->R != 0) {
        char key_text[17];
        printw("| Forcing Key Priority -- RC4 Key: %s \n",
               dsd_secret_format_hex(key_text, sizeof key_text, show_keys, state->R, 10U, 0));
    }
}

static void
ui_render_forced_key_status_tyt(const dsd_state* state, int show_keys) {
    char key_text[16];
    printw("| Forcing Key Priority -- TYT 16-bit Key: %s \n",
           dsd_secret_format_hex(key_text, sizeof key_text, show_keys, state->H, 4U, 0));
}

static void
ui_render_forced_key_status(const dsd_state* state, int show_keys) {
    if (state == NULL) {
        return;
    }

    if (state->M != 1 && state->tyt_bp == 0 && ui_hytera_key_segment_count(state) != 0U) {
        ui_render_hytera_loaded_key_status(state, show_keys);
    }
    if (state->M == 1) {
        ui_render_forced_key_status_dmr(state, show_keys);
    }
    if (state->M == 0x21) {
        ui_render_forced_key_status_rc4(state, show_keys);
    }
    if (state->M == 0x16) {
        ui_render_forced_key_status_tyt(state, show_keys);
    }
}

static void
ui_render_scanner_and_reverse_status(const dsd_opts* opts, const dsd_state* state) {
    if (opts->scanner_mode == 1) {
        printw("| Scan Mode: ");
        if (state->lcn_freq_roll != 0) {
            printw(" Frequency: %.06lf Mhz", (double)state->trunk_lcn_freq[state->lcn_freq_roll - 1] / 1000000);
        }
        printw(" Speed: %.02lf sec \n",
               opts->trunk_hangtime); // default aligned to OP25 (2.0s) unless overridden
    }

    if (opts->reverse_mute == 1) {
        printw("| Reverse Mute - Muting Unencrypted Voice\n");
    }
}

static void
ui_render_crypto_key_and_scanner_status(const dsd_opts* opts, const dsd_state* state) {
    ui_render_forced_key_status(state, opts->show_keys);
    ui_render_scanner_and_reverse_status(opts, state);
}

static void
ui_render_input_output_section(dsd_opts* opts, dsd_state* state) {
    ui_print_header("Input Output");
    ui_render_input_sources_block(opts, state);

    ui_render_audio_output_block(opts, state);

    ui_render_encoder_and_file_outputs(opts, state);

    ui_render_trunking_and_edacs_toggles(opts, state);
    ui_render_crypto_key_and_scanner_status(opts, state);

    ui_print_hr();
}

#ifdef USE_RADIO
static void
ui_print_rtl_visual_aids_controls(dsd_opts* opts, int nfft) {
    /* Controls/status line: only show controls relevant to active views */
    printw("| Const View:  %s (%c)", opts->frontend_display.constellation ? "On" : "Off", DSD_KEY_CONST_VIEW_UPPER);
    if (opts->frontend_display.constellation == 1) {
        printw("  Gate: %.02f (</>)  Norm: %s (%c)",
               (opts->mod_qpsk == 1) ? opts->frontend_display.const_gate_qpsk : opts->frontend_display.const_gate_other,
               opts->frontend_display.const_norm_mode ? "unit" : "radial", DSD_KEY_CONST_NORM);
    }
    printw("  Eye: %s (%c)", opts->frontend_display.eye_view ? "On" : "Off", DSD_KEY_EYE_VIEW);
    if (opts->frontend_display.eye_view == 1) {
        printw("  Uni: %s (%c) Col: %s (%c)", opts->frontend_terminal_display.eye_unicode ? "On" : "off",
               DSD_KEY_EYE_UNICODE, opts->frontend_terminal_display.eye_color ? "On" : "Off", DSD_KEY_EYE_COLOR);
    }
    printw("  Hist: %s (%c)", opts->frontend_display.fsk_hist_view ? "On" : "Off", DSD_KEY_FSK_HIST);
    printw("  Spec: %s (%c)", opts->frontend_display.spectrum_view ? "On" : "Off", DSD_KEY_SPECTRUM);
    if (opts->frontend_display.spectrum_view == 1) {
        printw("  FFT:%d (%c/%c)", nfft, DSD_KEY_SPEC_DEC, DSD_KEY_SPEC_INC);
    }
    addch('\n');
    ui_print_hr();
}

static void
ui_render_rtl_visual_aid_panels(dsd_opts* opts, dsd_state* state) {
    if (opts->frontend_display.constellation == 1) {
        print_constellation_view(opts, state);
    }
    if (opts->frontend_display.eye_view == 1) {
        print_eye_view(opts, state);
    }
    if (opts->frontend_display.fsk_hist_view == 1) {
        print_fsk_hist_view();
    }
    if (opts->frontend_display.spectrum_view == 1) {
        print_spectrum_view(opts);
    }
}
#endif

static void
ui_render_rtl_visual_aids(dsd_opts* opts, dsd_state* state) {
#ifdef USE_RADIO
    /* Only show RTL-SDR section and render visualizers when RTL input is active */
    if (opts->audio_in_type == AUDIO_IN_RTL) {
        ui_print_header(ui_audio_in_is_soapy(opts) ? "SoapySDR Visual Aids" : "RTL-SDR Visual Aids");
        dsd_frontend_metrics metrics;
        (void)dsd_app_frontend_get_metrics(&metrics);
        ui_print_rtl_visual_aids_controls(opts, metrics.spectrum_size);
        ui_render_rtl_visual_aid_panels(opts, state);
    }
#else
    (void)opts;
    (void)state;
#endif
    /* Ensure our primary UI color remains active after visual aids */
    attron(COLOR_PAIR(4));
}

static int
ui_compute_input_level_and_color(const dsd_opts* opts, const dsd_state* state) {
    if (opts == NULL || state == NULL) {
        return 0;
    }

    int level = 0;

    if (state->carrier == 1) {
        attron(COLOR_PAIR(3));
        if (opts->audio_in_type == AUDIO_IN_RTL) {
            /* RTL discriminator output is a normalized phase delta (angle/π).
               For C4FM/GFSK, typical symbol magnitudes are << 1.0 and depend on
               the DSP base rate (opts->rtl_dsp_bw_khz). Scale so a nominal "full
               deviation" C4FM signal (~±1.8 kHz) reads ~50% at V:1X, matching the
               non-RTL In Level behavior. */
            float bw_hz = (opts->rtl_dsp_bw_khz > 0) ? (float)opts->rtl_dsp_bw_khz * 1000.0f : 48000.0f;
            float scale = bw_hz / 72.0f; /* 50 * bw_hz / (2 * 1800) */
            level = (int)(state->max * scale);
        } else {
            int level_div = 164; /* baseline scaling for C4FM/GFSK symbol magnitudes */
            if (opts->mod_qpsk == 1 || state->rf_mod == 1) {
                level_div = 82; /* CQPSK phase deltas peak near pi/4 (~4k), so use tighter scale */
            }
            level = (int)state->max / level_div; //only update on carrier present
        }
        if (opts->audio_in_type == AUDIO_IN_SYMBOL_BIN) {
            level = 50; //hard set when reading symbol bin files, otherwise, it will just be near zero
        }
        if (level > 100) {
            level = 100; //cap max at 100 to prevent it going over
        }
    } else {
        level = 0;
    }
    return level;
}

static void
ui_render_audio_decode_header_fields(dsd_opts* opts, const dsd_state* state) {
    if (opts == NULL || state == NULL) {
        return;
    }

    ui_print_header("Audio Decode");
    if (opts->trunk_enable == 1 && (opts->trunk_is_tuned == 1)) {
        ui_print_kv_line("Tuner state", "Busy");
    }
    if (opts->trunk_enable == 1 && (opts->trunk_is_tuned == 0)) {
        ui_print_kv_line("Tuner state", "Free");
    }
    ui_print_label_pad("Demod/Rate");
    {
        const char* modlab = (state->rf_mod == 1) ? "QPSK" : (state->rf_mod == 2) ? "GFSK" : "C4FM";
        printw("[%s][%d] \n", modlab, ui_demod_symbol_rate_hz(opts, state));
    }
    if (opts->m17encoder == 1) {
        ui_print_kv_line("Encoding", "[%s]", opts->output_name);
    }
    ui_print_label_pad("Decoding");
    printw("[%s] ", opts->output_name);
    if (opts->aggressive_framesync == 0) {
        printw("CRC/(RAS) ");
    }
}

static void
ui_render_demod_snr_line(const dsd_opts* opts, const dsd_state* state) {
    if (opts == NULL || state == NULL) {
        printw("\n");
        return;
    }

    /* Demod SNR (per modulation) */
#ifdef USE_RADIO
    {
        ui_snr_readout snr = ui_snr_readout_for_mod(state->rf_mod);
        const char* m = snr.mod_label;
        if (snr.valid) {
            /* Show current SNR as a compact, colorized meter */
            char snr_value[16];
            if (DSD_SNPRINTF(snr_value, sizeof(snr_value), "%.1f", snr.snr_db) < 0) {
                snr_value[0] = '\0';
            }
            ui_print_snr_db_field(snr_value);
            addch(' ');
            /* Pass current modulation for per-mod color bands */
            print_snr_meter(opts, snr.snr_db, state->rf_mod);
            printw(" (%s)", m);
        } else {
            /* Show placeholder so users can see the field even when no estimate */
            ui_print_snr_db_field("n/a");
            printw("      (%s)", m[0] ? m : "-");
        }
    }
#endif
#ifndef USE_RADIO
    /* If built without RTL support, still show a placeholder */
    ui_print_snr_db_field("n/a");
    printw("     ");
#endif
    printw("\n");
}

static void
ui_render_audio_decode_levels(const dsd_opts* opts, const dsd_state* state, int level) {
    /* In Level is meaningful for non-RTL inputs and RTL C4FM/GFSK modes.
       Hide only for RTL QPSK where symbols are fixed ±1/±3 from differential demod. */
    if (opts->audio_in_type != AUDIO_IN_RTL || state->rf_mod != 1) {
        ui_print_kv_line("In Level", "[%02d%%]", level);
    }
    /* Quick hint for output mute toggle */
    ui_print_kv_line("Output (x)", "[%s]", (opts->audio_out == 0) ? "Muted" : "On");
}

static void
ui_render_voice_error_single_slot(const dsd_opts* opts, const dsd_state* state, int is_p25_active) {
    if (!is_p25_active) {
        ui_print_label_pad("Voice Error");
        printw("[%X][%X]", state->errs & 0xF, state->errs2 & 0xF);
        double avgv = 0.0;
        if (compute_p25p1_voice_avg_err(state, &avgv)) {
            printw(" Avg:%4.1f%%", avgv);
        }
        /* Keep slot toggle state at the end, as before */
        if (opts->slot1_on == 0) {
            printw(" Off");
        }
        if (opts->slot1_on == 1) {
            printw(" On");
        }
        printw("\n");
    } else {
        /* P25 active: show only slot toggle state, no error counters */
        ui_print_kv_line("Slot 1 (1)", "[%s]", (opts->slot1_on == 1) ? "On" : "Off");
    }
}

static void
ui_render_voice_error_dual_slot(const dsd_opts* opts, const dsd_state* state, int is_p25_active) {
    if (!is_p25_active) {
        ui_print_label_pad("Voice Error");
        printw("[%X][%X] Slot 1 (1)", state->errs & 0xF, state->errs2 & 0xF);
    } else {
        ui_print_label_pad("Slot 1 (1)");
        addch('[');
    }
    if (opts->slot1_on == 0) {
        printw(is_p25_active ? "Off" : " Off");
    }
    if (opts->slot1_on == 1) {
        printw(is_p25_active ? "On" : " On");
    }
    if (is_p25_active) {
        printw("]");
    }
    if (opts->slot_preference == 0) {
        printw(" *Preferred (3)");
    }
    printw("\n");

    if (!is_p25_active) {
        ui_print_label_pad("Voice Error");
        printw("[%X][%X] Slot 2 (2)", state->errsR & 0xF, state->errs2R & 0xF);
    } else {
        ui_print_label_pad("Slot 2 (2)");
        addch('[');
    }
    if (opts->slot2_on == 0) {
        printw(is_p25_active ? "Off" : " Off");
    }
    if (opts->slot2_on == 1) {
        printw(is_p25_active ? "On" : " On");
    }
    if (is_p25_active) {
        printw("]");
    }
    if (opts->slot_preference == 1) {
        printw(" *Preferred (3)");
    }
    printw("\n");
}

static void
ui_render_audio_decode_section(dsd_opts* opts, const dsd_state* state, int level) {
    ui_render_audio_decode_header_fields(opts, state);
    ui_render_demod_snr_line(opts, state);
    ui_render_audio_decode_levels(opts, state, level);

    /* Hide generic Voice Error line when P25 is active, but keep slot toggles */
    int is_p25p1_active = DSD_SYNC_IS_P25P1(ncurses_last_synctype);
    int is_p25p2_active = DSD_SYNC_IS_P25P2(ncurses_last_synctype);
    int is_p25_active = is_p25p1_active || is_p25p2_active;

    if (opts->dmr_stereo == 0) {
        ui_render_voice_error_single_slot(opts, state, is_p25_active);
    }

    if (opts->dmr_stereo == 1) {
        ui_render_voice_error_dual_slot(opts, state, is_p25_active);
    }
    ui_print_hr();
}

static void
ui_sort_indices_by_last_seen(const time_t* last_seen, int* idxs, int n) {
    for (int i = 0; i < n; i++) {
        int best = i;
        for (int j = i + 1; j < n; j++) {
            if (last_seen[idxs[j]] > last_seen[idxs[best]]) {
                best = j;
            }
        }
        if (best != i) {
            int tmp = idxs[i];
            idxs[i] = idxs[best];
            idxs[best] = tmp;
        }
    }
}

static int
ui_get_panel_cols(void) {
    int rows = 0, cols = 80;
    getmaxyx(stdscr, rows, cols);
    (void)rows;
    if (cols < 1) {
        cols = 80;
    }
    return cols;
}

static void
ui_print_wrapped_panel_item(const char* buf, int len, int cols, int* line_used) {
    int sep = (*line_used == 0) ? 0 : 4;
    int left_border = (*line_used == 0) ? 2 : 0;
    if ((left_border + *line_used + sep + len) > cols) {
        if (*line_used > 0) {
            addch('\n');
        }
        *line_used = 0;
    }
    if (*line_used == 0) {
        ui_print_lborder_green();
        addch(' ');
    } else {
        addstr("    ");
    }
    addnstr(buf, len);
    *line_used += ((*line_used == 0) ? 0 : sep) + len;
}

static void
ui_render_p25_metric_toggles(const dsd_opts* opts, const dsd_state* state) {
    int is_p25p1 = DSD_SYNC_IS_P25P1(ncurses_last_synctype);
    int is_p25p2 = DSD_SYNC_IS_P25P2(ncurses_last_synctype);
    if (!(is_p25p1 || is_p25p2)) {
        return;
    }

    if (opts->frontend_display.show_p25_metrics == 1) {
        ui_print_header("P25 Metrics");
        (void)ui_print_p25_metrics(opts, state);
        ui_print_hr();
    }
    if (opts->frontend_display.show_p25_cc_candidates == 1 && opts->trunk_enable == 1) {
        ui_print_header("P25 CC Candidates");
        ui_print_p25_cc_candidates(opts, state);
        ui_print_hr();
        ui_print_header("P25 Secondary CCs");
        ui_print_p25_secondary_ccs(opts, state);
        ui_print_hr();
    }
    if (opts->frontend_display.show_p25_neighbors == 1) {
        ui_print_header("P25 Neighbors");
        ui_print_p25_neighbors(opts, state);
        ui_print_hr();
    }
    if (opts->frontend_display.show_p25_iden_plan == 1) {
        ui_print_header("P25 IDEN Plan");
        ui_print_p25_iden_plan(opts, state);
        ui_print_hr();
    }
}

static void
ui_render_p25_affiliations_panel(const dsd_opts* opts, dsd_state* state) {
    int is_p25p1 = DSD_SYNC_IS_P25P1(ncurses_last_synctype);
    int is_p25p2 = DSD_SYNC_IS_P25P2(ncurses_last_synctype);
    if (!(opts->frontend_display.show_p25_affiliations == 1 && (is_p25p1 || is_p25p2))) {
        return;
    }

    ui_print_header("P25 Affiliations");
    // Compose a recent-first list of up to 20 RIDs
    int idxs[256];
    int n = 0;
    time_t now = time(NULL);
    for (int i = 0; i < 256; i++) {
        if (state->p25_aff_rid[i] != 0) {
            idxs[n++] = i;
        }
    }
    // Selection sort by last_seen desc (n is typically small)
    ui_sort_indices_by_last_seen(state->p25_aff_last_seen, idxs, n);
    int shown = 0;
    int cols = ui_get_panel_cols();
    // Track the current line width after the left border
    int line_used = 0;
    for (int i = 0; i < n && shown < 20; i++) {
        int k = idxs[i];
        uint32_t rid = state->p25_aff_rid[k];
        long age = (long)((state->p25_aff_last_seen[k] != 0) ? (now - state->p25_aff_last_seen[k]) : 0);
        if (age < 0) {
            age = 0;
        }
        char buf[64];
        int m = DSD_SNPRINTF(buf, sizeof buf, "RID:%u age:%lds", (unsigned)rid, age);
        if (m < 0) {
            m = 0;
        }
        ui_print_wrapped_panel_item(buf, m, cols, &line_used);
        shown++;
    }
    if (shown > 0 && line_used > 0) {
        addch('\n');
    }
    if (shown == 0) {
        ui_print_lborder_green();
        addstr(" (none)\n");
    }
    ui_print_hr();
}

static void
ui_render_p25_group_affiliations_panel(const dsd_opts* opts, dsd_state* state) {
    int is_p25p1 = DSD_SYNC_IS_P25P1(ncurses_last_synctype);
    int is_p25p2 = DSD_SYNC_IS_P25P2(ncurses_last_synctype);
    if (!(opts->frontend_display.show_p25_group_affiliations == 1 && (is_p25p1 || is_p25p2))) {
        return;
    }

    ui_print_header("P25 Group Affiliation");
    int idxs[512];
    int n = 0;
    time_t now = time(NULL);
    for (int i = 0; i < 512; i++) {
        if (state->p25_ga_rid[i] != 0 && state->p25_ga_tg[i] != 0) {
            idxs[n++] = i;
        }
    }
    ui_sort_indices_by_last_seen(state->p25_ga_last_seen, idxs, n);
    int shown = 0;
    int cols = ui_get_panel_cols();
    int line_used = 0;
    for (int i = 0; i < n && shown < 20; i++) {
        int k = idxs[i];
        uint32_t rid = state->p25_ga_rid[k];
        uint16_t tg = state->p25_ga_tg[k];
        long age = (long)((state->p25_ga_last_seen[k] != 0) ? (now - state->p25_ga_last_seen[k]) : 0);
        if (age < 0) {
            age = 0;
        }
        char buf[80];
        int m = DSD_SNPRINTF(buf, sizeof buf, "RID:%u TG:%u age:%lds", (unsigned)rid, (unsigned)tg, age);
        if (m < 0) {
            m = 0;
        }
        ui_print_wrapped_panel_item(buf, m, cols, &line_used);
        shown++;
    }
    if (shown > 0 && line_used > 0) {
        addch('\n');
    }
    if (shown == 0) {
        ui_print_lborder_green();
        addstr(" (none)\n");
    }
    ui_print_hr();
}

static void
ui_render_p25_optional_sections(const dsd_opts* opts, dsd_state* state) {
    ui_render_p25_metric_toggles(opts, state);
    ui_render_p25_affiliations_panel(opts, state);
    ui_render_p25_group_affiliations_panel(opts, state);
}

typedef struct {
    int history_mode;
    int rows;
    int cols;
    int history_stop_y;
    int events_to_show;
    uint16_t string_size;
} ui_history_render_ctx;

typedef struct {
    uint8_t slot;
    uint16_t idx;
    time_t sort_time;
} ui_history_item_ref;

static void
ui_history_render_header(const dsd_state* state, int history_mode) {
    int rows = 0;
    int cols = 80;
    getmaxyx(stdscr, rows, cols);
    if (cols < 4) {
        cols = 80;
    }
    int y = 0;
    int x0 = 0;
    getyx(stdscr, y, x0);
    (void)x0;

    addstr("--");
    if (state->eh_slot < 2) {
        printw("Latest Event History ([|])  Slot %d (\\)  Cycle (h): ", state->eh_slot + 1);
    } else {
        printw("Latest Event History ([|])  Slots 1+2 (\\)  Cycle (h): ");
    }

    if (history_mode == 1) {
        attron(A_BOLD);
    }
    addstr("Short");
    if (history_mode == 1) {
        attroff(A_BOLD);
    }

    addch('/');

    if (history_mode == 2) {
        attron(A_BOLD);
    }
    addstr("Long");
    if (history_mode == 2) {
        attroff(A_BOLD);
    }

    addch('/');

    if (history_mode == 0) {
        attron(A_BOLD);
    }
    addstr("Off");
    if (history_mode == 0) {
        attroff(A_BOLD);
    }

    if (history_mode != 0) {
        int room_hint = rows - (y + 1) - 2;
        if (room_hint < 1) {
            addstr(" [No room]");
        }
    }

    int used_y = 0;
    int used = 0;
    getyx(stdscr, used_y, used);
    (void)used_y;
    if (used < cols) {
        mvhline(y, used, '-', cols - used);
    }
    if (y + 1 < rows) {
        move(y + 1, 0);
    } else {
        addch('\n');
    }
}

static void
ui_history_setup_render_ctx(int history_mode, int* history_draw_footer, ui_history_render_ctx* ctx) {
    int start_y = 0;
    int start_x = 0;
    getmaxyx(stdscr, ctx->rows, ctx->cols);
    getyx(stdscr, start_y, start_x);
    (void)start_x;

    int avail_lines = ctx->rows - start_y - 2;
    if (avail_lines < 1) {
        avail_lines = ctx->rows - start_y - 1;
        *history_draw_footer = 0;
    }
    if (avail_lines < 0) {
        avail_lines = 0;
    }

    ctx->history_mode = history_mode;
    ctx->events_to_show = avail_lines;
    if (ctx->events_to_show > 50) {
        ctx->events_to_show = 50;
    }

    ctx->history_stop_y = ctx->rows - (*history_draw_footer ? 2 : 1);
    if (ctx->history_stop_y < 0) {
        ctx->history_stop_y = 0;
    }

    ctx->string_size = 71;
    if (history_mode == 2) {
        ctx->string_size = 1999;
    } else if (ctx->cols > 0) {
        int max_text = ctx->cols - 4;
        if (max_text < 0) {
            max_text = 0;
        }
        if (max_text < (int)ctx->string_size) {
            ctx->string_size = (uint16_t)max_text;
        }
    }
}

static int
ui_history_has_room_for_line(int history_stop_y) {
    int y = 0;
    int x = 0;
    getyx(stdscr, y, x);
    (void)x;
    return y < history_stop_y;
}

static uint16_t
ui_history_clamp_line_size(const ui_history_render_ctx* ctx, int prefix_len) {
    uint16_t line_size = ctx->string_size;
    if (ctx->history_mode != 2 && ctx->cols > 0) {
        int max_text = ctx->cols - (prefix_len + 2);
        if (max_text < 0) {
            max_text = 0;
        }
        if (max_text < (int)line_size) {
            line_size = (uint16_t)max_text;
        }
    }
    return line_size;
}

static void
ui_history_color_pair_for_event(const Event_History* item) {
    short color_pair = 4;
    if (item != NULL) {
        if (item->severity != DSD_EVENT_SEVERITY_UNKNOWN || item->category != DSD_EVENT_CATEGORY_UNKNOWN) {
            color_pair = 4;
        } else if (item->color_pair != 0) {
            color_pair = (short)item->color_pair;
        }
    }
    attron(COLOR_PAIR(color_pair));
}

static void
ui_history_print_event_summary(const Event_History* item, const char* line_prefix, int prefix_len,
                               const ui_history_render_ctx* ctx) {
    uint16_t line_size = ui_history_clamp_line_size(ctx, prefix_len);
    if (item->event_string[0] == '\0') {
        printw("%s\n", line_prefix);
        return;
    }

    char compact_string[2000];
    char text_string[2000];
    dsd_app_frontend_history_compact_event_text(compact_string, sizeof compact_string, item->event_string,
                                                ctx->history_mode);
    size_t text_size = (size_t)line_size;
    if (text_size >= sizeof text_string) {
        text_size = sizeof text_string - 1U;
    }
    size_t compact_size = strnlen(compact_string, sizeof compact_string);
    if (text_size > compact_size) {
        text_size = compact_size;
    }
    DSD_MEMCPY(text_string, compact_string, text_size);
    text_string[text_size] = '\0';
    printw("%s", line_prefix);
    ui_history_color_pair_for_event(item);
    printw("%s\n", text_string);
    attron(COLOR_PAIR(4));
}

static int
ui_history_print_detail_line(int history_stop_y, uint8_t slot, const char* label, const char* value) {
    if (value == NULL || value[0] == '\0') {
        return 1;
    }
    if (!ui_history_has_room_for_line(history_stop_y)) {
        return 0;
    }

    attron(COLOR_PAIR(4));
    if (slot < 2) {
        if (label && label[0] != '\0') {
            printw("|[%d] \\-- %s%s \n", slot + 1, label, value);
        } else {
            printw("|[%d] \\-- %s\n", slot + 1, value);
        }
    } else if (label && label[0] != '\0') {
        printw("|  \\-- %s%s \n", label, value);
    } else {
        printw("|  \\-- %s\n", value);
    }
    attron(COLOR_PAIR(4));
    return 1;
}

static void
ui_history_render_single_slot_item(const Event_History* item, const ui_history_render_ctx* ctx) {
    const int show_enc_tag = (ctx->history_mode == 1 && item->enc != 0);
    const char* line_prefix = show_enc_tag ? "| [ENC] " : "| ";
    const int line_prefix_len = show_enc_tag ? 8 : 2;
    attron(COLOR_PAIR(4));
    ui_history_print_event_summary(item, line_prefix, line_prefix_len, ctx);

    if (!ui_history_print_detail_line(ctx->history_stop_y, UINT8_MAX, "", item->text_message)) {
        return;
    }
    if (!ui_history_print_detail_line(ctx->history_stop_y, UINT8_MAX, "Alias: ", item->alias)) {
        return;
    }
    if (!ui_history_print_detail_line(ctx->history_stop_y, UINT8_MAX, "GPS: ", item->gps_s)) {
        return;
    }
    (void)ui_history_print_detail_line(ctx->history_stop_y, UINT8_MAX, "DSD-neo: ", item->internal_str);
}

static void
ui_history_render_dual_slot_item(const Event_History* item, uint8_t slot, const ui_history_render_ctx* ctx) {
    char line_prefix[16];
    const int show_enc_tag = (ctx->history_mode == 1 && item->enc != 0);
    if (show_enc_tag) {
        DSD_SNPRINTF(line_prefix, sizeof line_prefix, "|[%d] [ENC] ", slot + 1);
    } else {
        DSD_SNPRINTF(line_prefix, sizeof line_prefix, "|[%d] ", slot + 1);
    }

    attron(COLOR_PAIR(4));
    ui_history_print_event_summary(item, line_prefix, (int)strlen(line_prefix), ctx);

    if (!ui_history_print_detail_line(ctx->history_stop_y, slot, "", item->text_message)) {
        return;
    }
    if (!ui_history_print_detail_line(ctx->history_stop_y, slot, "Alias: ", item->alias)) {
        return;
    }
    if (!ui_history_print_detail_line(ctx->history_stop_y, slot, "GPS: ", item->gps_s)) {
        return;
    }
    (void)ui_history_print_detail_line(ctx->history_stop_y, slot, "DSD-neo: ", item->internal_str);
}

static int
ui_history_item_ref_compare(const void* lhs, const void* rhs) {
    const ui_history_item_ref* a = (const ui_history_item_ref*)lhs;
    const ui_history_item_ref* b = (const ui_history_item_ref*)rhs;

    if (a->sort_time > b->sort_time) {
        return -1;
    }
    if (a->sort_time < b->sort_time) {
        return 1;
    }
    if (a->idx < b->idx) {
        return -1;
    }
    if (a->idx > b->idx) {
        return 1;
    }
    if (a->slot < b->slot) {
        return -1;
    }
    if (a->slot > b->slot) {
        return 1;
    }
    return 0;
}

static size_t
ui_history_collect_slot_items(const dsd_state* state, uint8_t slot, ui_history_item_ref* refs, size_t count,
                              size_t cap) {
    if (state == NULL || state->event_history_s == NULL || refs == NULL || count >= cap || slot >= 2) {
        return count;
    }

    for (uint16_t idx = 1; idx < 255 && count < cap; idx++) {
        const Event_History* item = &state->event_history_s[slot].Event_History_Items[idx];
        if (!ui_eh_item_has_content(item)) {
            continue;
        }
        refs[count].slot = slot;
        refs[count].idx = idx;
        refs[count].sort_time = dsd_app_frontend_history_event_sort_time(item->event_string, item->event_time);
        count++;
    }
    return count;
}

static size_t
ui_history_collect_sorted_items(const dsd_state* state, uint8_t slot, ui_history_item_ref* refs, size_t cap) {
    size_t count = 0;
    if (slot < 2) {
        count = ui_history_collect_slot_items(state, slot, refs, count, cap);
    } else {
        count = ui_history_collect_slot_items(state, 0, refs, count, cap);
        count = ui_history_collect_slot_items(state, 1, refs, count, cap);
    }

    if (count > 1) {
        qsort(refs, count, sizeof(refs[0]), ui_history_item_ref_compare);
    }
    return count;
}

static void
ui_history_render_item_refs(const dsd_state* state, const ui_history_render_ctx* ctx, const ui_history_item_ref* refs,
                            size_t count) {
    size_t pos = state->eh_index;
    if (pos > count) {
        pos = count;
    }

    for (int shown = 0; shown < ctx->events_to_show && pos < count; pos++) {
        if (!ui_history_has_room_for_line(ctx->history_stop_y)) {
            break;
        }
        const uint8_t slot = refs[pos].slot;
        const uint16_t idx = refs[pos].idx;
        const Event_History* item = &state->event_history_s[slot].Event_History_Items[idx];
        shown++;
        if (state->eh_slot < 2) {
            ui_history_render_single_slot_item(item, ctx);
        } else {
            ui_history_render_dual_slot_item(item, slot, ctx);
        }
    }
}

static void
ui_history_render_sorted_slot_items(const dsd_state* state, const ui_history_render_ctx* ctx, uint8_t slot) {
    ui_history_item_ref refs[508];
    size_t count = ui_history_collect_sorted_items(state, slot, refs, sizeof(refs) / sizeof(refs[0]));
    ui_history_render_item_refs(state, ctx, refs, count);
}

static void
ui_render_event_history_section(const dsd_state* state) {
    const int history_mode = dsd_app_frontend_history_get_mode();
    int history_draw_footer = 1;
    attron(COLOR_PAIR(4));
    ui_history_render_header(state, history_mode);

    if (history_mode != 0) {
        ui_history_render_ctx ctx = {0};
        ui_history_setup_render_ctx(history_mode, &history_draw_footer, &ctx);
        if (state->event_history_s != NULL) {
            if (state->eh_slot < 2) {
                ui_history_render_sorted_slot_items(state, &ctx, state->eh_slot);
            } else {
                ui_history_render_sorted_slot_items(state, &ctx, 2);
            }
        }
    }

    if (history_draw_footer || history_mode == 0) {
        ui_print_hr();
    }
    attroff(COLOR_PAIR(4)); //cyan for history
}

static void
ui_render_call_info_dstar(dsd_state* state) {
    //DSTAR
    if (DSD_SYNC_IS_DSTAR(ncurses_last_synctype)) {
        printw("| %s ", dsd_synctype_to_string(ncurses_last_synctype));
        printw("\n");
        printw("| RPT2: %s", state->dstar_rpt2);
        printw(" RPT1: %s", state->dstar_rpt1);
        printw("\n");
        printw("| DEST: %s", state->dstar_dst);
        printw("  SRC: %s", state->dstar_src);
        printw("\n");
        printw("| TEXT: %s", state->dstar_txt);
        printw("\n");
        printw("| DATA: %s", state->dstar_gps);
        printw("\n");
    }
}

static void
ui_print_m17_data_type(int dt) {
    switch (dt) {
        case 0: printw("Reserved"); break;
        case 1: printw("Data "); break;
        case 2: printw("Voice (3200) "); break;
        case 3: printw("Voice (1600) + Data"); break;
        default: break;
    }
}

static void
ui_print_m17_encryption_details(dsd_state* state) {
    //fill in any extra info, like Meta (IV, etc)
    if (state->m17_enc == 1) {
        printw(" Scrambler - Type: %d", state->m17_enc_st);
    }

    if (state->m17_enc == 2) {
        attron(COLOR_PAIR(1));
        printw("AES-CTR - IV: ");
        //display packed meta as IV
        for (int i = 0; i < 16; i++) {
            printw("%02X", state->m17_meta[i]);
        }
    }

    if (state->m17_enc == 3) {
        printw(" Reserved Enc - Type: %d", state->m17_enc_st);
    }
}

static void
ui_render_call_info_m17(dsd_state* state) {
    //M17
    if (ncurses_last_synctype == DSD_SYNC_M17_STR_POS || ncurses_last_synctype == DSD_SYNC_M17_STR_NEG
        || ncurses_last_synctype == DSD_SYNC_M17_LSF_POS || ncurses_last_synctype == DSD_SYNC_M17_LSF_NEG) {

        printw("| ");
        printw("M17: ");

        //insert data type and frame information
        ui_print_m17_data_type(state->m17_str_dt);

        printw("\n");
        printw("| ");

        printw("DST: ");
        const uint8_t dst_kind = m17_address_classify(state->m17_dst);
        if (dst_kind == M17_ADDRESS_BROADCAST_KIND) {
            printw("BROADCAST ");
        } else if (dst_kind == M17_ADDRESS_EXTENDED) {
            printw("EXTENDED (%012llx) ", state->m17_dst);
        } else if (dst_kind == M17_ADDRESS_RESERVED) {
            printw("RESERVED (%012llx) ", state->m17_dst);
        } else {
            printw("%s", state->m17_dst_str);
        }

        printw("\n");
        printw("| ");

        printw("SRC: ");
        const uint8_t src_kind = m17_address_classify(state->m17_src);
        if (src_kind == M17_ADDRESS_BROADCAST_KIND) {
            printw("UNKNOWN FFFFFFFFFFFF");
        } else if (src_kind == M17_ADDRESS_EXTENDED) {
            printw("EXTENDED (%012llx)", state->m17_src);
        } else if (src_kind == M17_ADDRESS_RESERVED) {
            printw("RESERVED (%012llx)", state->m17_src);
        } else {
            printw("%s", state->m17_src_str);
        }

        printw("\n");
        printw("| ");

        printw("CAN: %02d ", state->m17_can);

        printw("\n");
        printw("| ");

        ui_print_m17_encryption_details(state);

        printw("\n");
    }
}

static void
ui_render_call_info_ysf(dsd_state* state) {
    //YSF
    if (DSD_SYNC_IS_YSF(ncurses_last_synctype)) {
        printw("| ");
        printw("Fusion - ");
        //insert data type and frame information
        if (state->ysf_dt == 0) {
            printw("V/D1 ");
        }
        if (state->ysf_dt == 1) {
            printw("DATA ");
        }
        if (state->ysf_dt == 2) {
            printw("V/D2 ");
        }
        if (state->ysf_dt == 3) {
            printw("VWFR ");
        }
        printw(" ");
        if (state->ysf_cm == 0) {
            printw("Group/CQ ");
        }
        if (state->ysf_cm == 3) {
            printw("Private  ");
        }
        if (state->ysf_cm == 1) {
            printw("Radio ID ");
        }
        if (state->ysf_cm == 2) {
            printw("Reserved ");
        }

        if (state->ysf_fi == 0) {
            printw("HC ");
        }
        if (state->ysf_fi == 1) {
            printw("CC ");
        }
        if (state->ysf_fi == 2) {
            printw("TC ");
        }
        if (state->ysf_fi == 3) {
            printw("XX ");
        }

        printw("\n");
        printw("| ");
        //NOTE: In Radio ID Mode, the DST will be split on Destination and Source Radio ID values
        printw("DST: %s ", state->ysf_tgt);
        printw("SRC: %s ", state->ysf_src);
        printw("\n");
        printw("| ");
        printw("UPL: %s ", state->ysf_upl);
        printw("DNL: %s ", state->ysf_dnl);
        printw("\n");
        printw("| ");
        printw("RM1: %s ", state->ysf_rm1);
        printw("RM2: %s ", state->ysf_rm2);
        printw("\n");
        printw("| ");
        printw("RM3: %s ", state->ysf_rm3);
        printw("RM4: %s ", state->ysf_rm4);

        printw("\n");
    }
}

static int
ui_channel_label_is_locked(const dsd_opts* opts, const dsd_state* state, const char* label) {
    int locked = ui_is_locked_from_label(state, label);
    if (locked || !opts) {
        return locked;
    }
    if (opts->trunk_tune_enc_calls == 0 && ui_is_transient_enc_locked_from_label(state, label)) {
        return 1;
    }
    if (opts->trunk_tune_data_calls == 0 && strstr(label, "Active Data Ch:") != NULL) {
        return 1;
    }
    if (opts->trunk_tune_group_calls == 0 && strstr(label, "TG:") != NULL) {
        return 1;
    }
    if (opts->trunk_tune_private_calls == 0 && strstr(label, "TGT:") != NULL) {
        return 1;
    }
    return 0;
}

static void
ui_render_active_channel_list(const dsd_opts* opts, const dsd_state* state, unsigned int max_channels) {
    for (unsigned int i = 0; i < max_channels; i++) {
        if (state->active_channel[i][0] == '\0') {
            continue;
        }
        const char* s = state->active_channel[i];
        if (ui_channel_label_is_locked(opts, state, s)) {
            attron(COLOR_PAIR(2));
            printw("%s", s);
            attron(COLOR_PAIR(4));
        } else {
            printw("%s", s);
        }
    }
    if (state->carrier == 1) {
        attron(COLOR_PAIR(3));
    } else {
        attron(COLOR_PAIR(4));
    }
}

static int
ui_nxdn_is_idas(const dsd_state* state) {
    return strcmp(state->nxdn_location_category, "Type-D") == 0;
}

static void
ui_render_nxdn_monitor_line(const dsd_opts* opts, const dsd_state* state, int idas) {
    if (opts->trunk_enable != 1) {
        return;
    }
    printw("| ");
    if (opts->trunk_is_tuned == 0) {
        printw(idas ? "Monitoring RTCH2 Channel" : "Monitoring RCCH Channel");
        if (state->trunk_cc_freq != 0 || state->p25_cc_freq != 0) {
            long f = (state->trunk_cc_freq != 0) ? state->trunk_cc_freq : state->p25_cc_freq;
            printw(" - Frequency: %.06lf Mhz ", (double)f / 1000000);
        }
    } else {
        printw(idas ? "Monitoring RTCH2 Channel" : "Monitoring RTCH Channel");
        if (state->trunk_vc_freq[0] != 0 || state->p25_vc_freq[0] != 0) {
            long f = (state->trunk_vc_freq[0] != 0) ? state->trunk_vc_freq[0] : state->p25_vc_freq[0];
            printw(" - Frequency: %.06lf Mhz ", (double)f / 1000000);
        }
    }
    printw("\n");
}

static void
ui_render_nxdn_site_line(const dsd_state* state, int idas) {
    printw("| ");
    if (idas) {
        printw("IDAS - Area: %02d; ", state->nxdn_last_ran);
    } else {
        printw("NXDN - RAN: %02d; ", state->nxdn_last_ran);
    }
    if (state->nxdn_location_site_code != 0) {
        printw("Cat: %s; ", state->nxdn_location_category);
        printw("Sys Code: %d; ", state->nxdn_location_sys_code);
        printw("Site Code: %d; ", state->nxdn_location_site_code);
    }
    if (state->nxdn_rcn == 1) {
        printw("DFA ");
    }
    printw("\n");
}

static void
ui_render_nxdn_tgt_src_line(const dsd_state* state) {
    printw("| ");
    printw("TGT: [%5d] ", state->nxdn_last_tg);
    printw("SRC: [%5d] ", state->nxdn_last_rid);
    printw("Alias: [%s]", state->generic_talker_alias[0]);
    {
        char group_mode[8];
        char group_name[50];
        if (ui_lookup_group_label(state, (unsigned long)state->nxdn_last_tg, group_mode, sizeof(group_mode), group_name,
                                  sizeof(group_name))) {
            printw("TG: ");
            attron(COLOR_PAIR(4));
            printw(" [%s]", group_name);
            printw("[%s] ", group_mode);
        }
        if (state->nxdn_last_rid != state->nxdn_last_tg
            && ui_lookup_group_label(state, (unsigned long)state->nxdn_last_rid, NULL, 0, group_name,
                                     sizeof(group_name))) {
            attron(COLOR_PAIR(4));
            printw(" [%s]", group_name);
        }
        if (state->carrier == 1) {
            attron(COLOR_PAIR(3));
        }
    }
    if (state->carrier == 1) {
        printw(" %s ", state->nxdn_call_type);
    }
}

static void
ui_render_nxdn_encryption_line(const dsd_opts* opts, const dsd_state* state) {
    printw("\n|");
    if (state->nxdn_cipher_type > 0) {
        printw(" ALG: %d Key ID: %02d ", state->nxdn_cipher_type, state->nxdn_key);
    }
    if (state->carrier != 1) {
        return;
    }
    switch (state->nxdn_cipher_type) {
        case 0x1:
            if (state->R == 0) {
                attron(COLOR_PAIR(2));
            }
            printw("Scrambler ");
            if (state->R == 0) {
                attroff(COLOR_PAIR(2));
            }
            attron(COLOR_PAIR(3));
            if (state->R != 0) {
                attron(COLOR_PAIR(1));
                printw("Seed: %04llX ", state->payload_miN);
                char key_text[16];
                printw("Key: %s ", dsd_secret_format_decimal(key_text, sizeof key_text, opts->show_keys, state->R, 5U));
                attron(COLOR_PAIR(3));
            }
            break;
        case 0x2:
            attron(COLOR_PAIR(1));
            printw("IV: %016llX ", state->payload_miN);
            attron(COLOR_PAIR(2));
            printw("DES1 ");
            if (state->R != 0) {
                char key_text[17];
                printw("Key: %s ", dsd_secret_format_hex(key_text, sizeof key_text, opts->show_keys, state->R, 16U, 0));
            }
            attroff(COLOR_PAIR(2));
            attron(COLOR_PAIR(3));
            break;
        case 0x3:
            attron(COLOR_PAIR(1));
            printw("IV: %016llX ", state->payload_miN);
            attron(COLOR_PAIR(2));
            printw("AES-256 ");
            if (state->aes_key_loaded[0] == 1) {
                char key_text[17];
                printw("KS: %s",
                       dsd_secret_format_hex(key_text, sizeof key_text, opts->show_keys, state->A4[0], 16U, 0));
            }
            attroff(COLOR_PAIR(2));
            attron(COLOR_PAIR(3));
            break;
        default:
            if (state->nxdn_cipher_type > 0x3) {
                attron(COLOR_PAIR(2));
                printw("Unknown Encryption ");
                attroff(COLOR_PAIR(2));
                attron(COLOR_PAIR(3));
            }
            break;
    }
}

static void
ui_render_nxdn_active_channels_and_tg_hold(const dsd_opts* opts, const dsd_state* state) {
    printw("\n| ");
    attron(COLOR_PAIR(4));
    ui_render_active_channel_list(opts, state, 16);
    if (state->tg_hold != 0) {
        printw("TG HOLD: %d", state->tg_hold);
    }
    printw("\n");
}

static void
ui_render_call_info_nxdn(const dsd_opts* opts, const dsd_state* state) {
    //NXDN
    if (!DSD_SYNC_IS_NXDN(ncurses_last_synctype)) {
        return;
    }

    int idas = ui_nxdn_is_idas(state);
    ui_render_nxdn_monitor_line(opts, state, idas);
    ui_render_nxdn_site_line(state, idas);
    ui_render_nxdn_tgt_src_line(state);
    ui_render_nxdn_encryption_line(opts, state);
    ui_render_nxdn_active_channels_and_tg_hold(opts, state);
}

static void
ui_render_call_info_dpmr(const dsd_opts* opts, dsd_state* state) {
    //dPMR
    if (DSD_SYNC_IS_DPMR(ncurses_last_synctype)) {
        printw("| DCC: [%i] ", state->dpmr_color_code);
        printw("TGT: [%s] SRC: [%s] ", state->dpmr_target_id, state->dpmr_caller_id);
        printw("\n| ");
        if (state->dPMRVoiceFS2Frame.Version[0] == 3) {
            attron(COLOR_PAIR(2));
            printw("Scrambler ");
            attroff(COLOR_PAIR(2));
            attron(COLOR_PAIR(3));
            if (state->R != 0) {
                attron(COLOR_PAIR(1));
                char key_text[16];
                printw("KEY VALUE: [%s] ",
                       dsd_secret_format_decimal(key_text, sizeof key_text, opts->show_keys, state->R, 5U));
                attron(COLOR_PAIR(3));
            }
        }
        printw("\n");
    }
}

static void
ui_render_edacs_site_header(const dsd_opts* opts, dsd_state* state) {
    if (state->edacs_site_id == 0) {
        return;
    }

    if (opts->trunk_is_tuned == 0) {
        printw("| Monitoring CC - LCN [%02d]\n", state->edacs_cc_lcn);
    } else {
        printw("| Monitoring VC - LCN [%02d]\n", state->edacs_tuned_lcn);
        edacs_channel_tree[state->edacs_tuned_lcn][5] = time(NULL);
    }
    printw("| SITE [%03lld][%02llX]", state->edacs_site_id, state->edacs_site_id);
    printw((state->ea_mode == 1) ? " Extended Addressing" : " Standard/Networked");
    printw((state->esk_mask == 0xA0) ? " w/  ESK" : " w/o ESK");
    printw("\n");
}

static int
ui_get_edacs_call_color(const dsd_state* state, int lcn) {
    if (lcn == state->edacs_cc_lcn) {
        return 0;
    }
    time_t age = time(NULL) - edacs_channel_tree[lcn][5];
    if (age < 2) {
        return 3;
    }
    if (age < 5) {
        return 2;
    }
    return 0;
}

static void
ui_render_edacs_call_flags_ea(unsigned long long flags) {
    if ((flags & EDACS_IS_TEST_CALL) == 0) {
        printw(((flags & EDACS_IS_DIGITAL) == 0) ? " [Ana]" : " [Dig]");
    }
    if ((flags & EDACS_IS_EMERGENCY) != 0) {
        printw("[EM]");
    }
}

static void
ui_render_edacs_call_flags_standard(unsigned long long flags) {
    if ((flags & EDACS_IS_TEST_CALL) == 0) {
        printw(((flags & EDACS_IS_DIGITAL) == 0) ? " [Ana]" : " [Dig]");
    }
    if ((flags & EDACS_IS_AGENCY_CALL) != 0) {
        printw("[A]");
    }
    if ((flags & EDACS_IS_FLEET_CALL) != 0) {
        printw("[F]");
    }
    if ((flags & EDACS_IS_EMERGENCY) != 0) {
        printw("[EM]");
    }
}

static void
ui_render_edacs_extended_call_body(int lcn, unsigned long long flags) {
    unsigned long long tgt = edacs_channel_tree[lcn][2];
    unsigned long long src = edacs_channel_tree[lcn][3];

    if ((flags & EDACS_IS_VOICE) == 0) {
        printw(" TGT [  DATA  ] SRC [%8lld] Data", src);
        return;
    }

    if ((flags & EDACS_IS_GROUP) != 0) {
        printw(" TGT [%8lld] SRC [%8lld]", tgt, src);
    } else if ((flags & EDACS_IS_INDIVIDUAL) != 0) {
        printw(" TGT [%8lld] SRC [%8lld] I-Call", tgt, src);
    } else if ((flags & EDACS_IS_ALL_CALL) != 0) {
        printw(" TGT [ SYSTEM ] SRC [%8lld] All-Call", src);
    } else if ((flags & EDACS_IS_INTERCONNECT) != 0) {
        printw(" TGT [ SYSTEM ] SRC [%8lld] Interconnect", src);
    } else if ((flags & EDACS_IS_TEST_CALL) != 0) {
        printw(" TGT [ SYSTEM ] SRC [ SYSTEM ] Test Call");
    } else {
        printw(" Unknown call type");
    }
    ui_render_edacs_call_flags_ea(flags);
}

static void
ui_render_edacs_standard_voice_body(const dsd_state* state, int lcn, unsigned long long flags, int a, int f, int s) {
    const int afs_len = getAfsStringLength(state);
    unsigned long long tgt = edacs_channel_tree[lcn][2];
    unsigned long long src = edacs_channel_tree[lcn][3];

    if ((flags & EDACS_IS_GROUP) != 0) {
        char afs_str[8];
        getAfsString(state, afs_str, a, f, s);
        printw(" TGT [%6lld][%s] SRC [%5lld]", tgt, afs_str, src);
    } else if ((flags & EDACS_IS_INDIVIDUAL) != 0) {
        printw((afs_len == 6) ? " TGT [%6lld][ UNIT ] SRC [%5lld] I-Call" : " TGT [%6lld][  UNIT ] SRC [%5lld] I-Call",
               tgt, src);
    } else if ((flags & EDACS_IS_ALL_CALL) != 0) {
        printw((afs_len == 6) ? " TGT [    SYSTEM    ] SRC [%5lld] All-Call"
                              : " TGT [     SYSTEM    ] SRC [%5lld] All-Call",
               src);
    } else if ((flags & EDACS_IS_INTERCONNECT) != 0) {
        printw((afs_len == 6) ? " TGT [    SYSTEM    ] SRC [%5lld] Interconnect"
                              : " TGT [     SYSTEM    ] SRC [%5lld] Interconnect",
               src);
    } else if ((flags & EDACS_IS_TEST_CALL) != 0) {
        printw((afs_len == 6) ? " TGT [    SYSTEM    ] SRC [ SYS ] Test Call"
                              : " TGT [     SYSTEM    ] SRC [ SYS ] Test Call");
    } else {
        printw(" Unknown call type");
    }
    ui_render_edacs_call_flags_standard(flags);
}

static void
ui_render_edacs_standard_call_body(const dsd_state* state, int lcn, unsigned long long flags, int a, int f, int s) {
    if ((flags & EDACS_IS_VOICE) != 0) {
        ui_render_edacs_standard_voice_body(state, lcn, flags, a, f, s);
        return;
    }
    if (getAfsStringLength(state) == 6) {
        printw(" TGT [     DATA     ] SRC [%5lld] Data", edacs_channel_tree[lcn][3]);
    } else {
        printw(" TGT [      DATA     ] SRC [%5lld] Data", edacs_channel_tree[lcn][3]);
    }
}

static void
ui_render_edacs_channel_label(const dsd_state* state, int lcn) {
    char group_mode[8];
    char group_name[50];
    int label_found = 0;
    if (edacs_channel_tree[lcn][2] != 0) {
        label_found = ui_lookup_group_label(state, (unsigned long)edacs_channel_tree[lcn][2], group_mode,
                                            sizeof(group_mode), group_name, sizeof(group_name));
    }
    if (!label_found && edacs_channel_tree[lcn][3] != 0) {
        label_found = ui_lookup_group_label(state, (unsigned long)edacs_channel_tree[lcn][3], group_mode,
                                            sizeof(group_mode), group_name, sizeof(group_name));
    }
    if (label_found) {
        printw(" [%s]", group_name);
        printw("[%s]", group_mode);
    }
}

static void
ui_render_edacs_lcn_row(const dsd_opts* opts, const dsd_state* state, int lcn) {
    int a = (edacs_channel_tree[lcn][2] >> state->edacs_a_shift) & state->edacs_a_mask;
    int f = (edacs_channel_tree[lcn][2] >> state->edacs_f_shift) & state->edacs_f_mask;
    int s = edacs_channel_tree[lcn][2] & state->edacs_s_mask;
    unsigned long long flags = edacs_channel_tree[lcn][4];

    printw("| - LCN [%02d][%.06lf] MHz", lcn, (double)state->trunk_lcn_freq[lcn - 1] / 1000000);
    if (lcn == state->edacs_cc_lcn) {
        attron(COLOR_PAIR(1));
        printw(" Control Channel");
        attroff(COLOR_PAIR(1));
    }

    int call_color = ui_get_edacs_call_color(state, lcn);
    if (call_color == 3) {
        attron(COLOR_PAIR(3));
    } else if (call_color == 2) {
        attron(COLOR_PAIR(2));
    }
    if (call_color != 0) {
        if (state->ea_mode == 1) {
            ui_render_edacs_extended_call_body(lcn, flags);
        } else {
            ui_render_edacs_standard_call_body(state, lcn, flags, a, f, s);
        }
        ui_render_edacs_channel_label(state, lcn);
        if (call_color == 3) {
            attroff(COLOR_PAIR(3));
        } else if (call_color == 2) {
            attroff(COLOR_PAIR(2));
        }
    }

    if (lcn == state->edacs_tuned_lcn && (opts->trunk_is_tuned == 1)) {
        printw(" **T**");
    }
    printw("\n");
}

static void
ui_render_call_info_edacs(const dsd_opts* opts, dsd_state* state) {
    //EDACS and ProVoice
    if (!DSD_SYNC_IS_EDACS(ncurses_last_synctype)) {
        return;
    }

    attroff(COLOR_PAIR(3));
    ui_render_edacs_site_header(opts, state);
    for (int i = 1; i <= state->edacs_lcn_count; i++) {
        ui_render_edacs_lcn_row(opts, state, i);
    }
    if (state->carrier == 1) {
        attron(COLOR_PAIR(3));
    }
}

static void
ui_parse_patch_tokens(const char* patch_line, char tokens[48][64], int* count_out) {
    int count = 0;
    const char* s = patch_line;
    while (*s && count < 48) {
        while (*s == ';' || *s == ' ') {
            s++;
        }
        if (!*s) {
            break;
        }
        int t = 0;
        while (*s && *s != ';' && t < 63) {
            tokens[count][t++] = *s++;
        }
        while (t > 0 && tokens[count][t - 1] == ' ') {
            t--;
        }
        tokens[count][t] = '\0';
        if (t > 0) {
            count++;
        }
        if (*s == ';') {
            s++;
        }
    }
    *count_out = count;
}

static int
ui_patch_tokens_col_width(char tokens[48][64], int count) {
    int colw = 0;
    for (int i = 0; i < count; i++) {
        int len = (int)strlen(tokens[i]);
        if (len > colw) {
            colw = len;
        }
    }
    if (colw > 28) {
        colw = 28;
    }
    return colw;
}

static void
ui_render_patch_rows(const dsd_state* state, char tokens[48][64], int count, int colw) {
    const int cols_per_line = 3;
    const char* label = "Patches: ";
    int idx = 0;
    while (idx < count) {
        printw("|        | ");
        if (idx == 0) {
            attron(COLOR_PAIR(4));
            printw("%s", label);
        } else {
            for (size_t sp = 0; sp < strlen(label); sp++) {
                addch(' ');
            }
        }
        for (int c = 0; c < cols_per_line && idx < count; c++, idx++) {
            attron(COLOR_PAIR(4));
            printw("%-*s", colw, tokens[idx]);
            if (state->carrier == 1) {
                attron(COLOR_PAIR(3));
            } else {
                attron(COLOR_PAIR(4));
            }
            if (c < cols_per_line - 1 && idx < count) {
                addstr("   ");
            }
        }
        printw("\n");
    }
}

static void
ui_render_call_info_patches(const dsd_state* state) {
    // If any P25 patches are active, show them in wrapped columns (3 per line)
    // to avoid overflowing the Call Info width (similar to Channels layout).
    {
        char patch_line[192] = {0};
        int n = p25_patch_compose_details(state, patch_line, sizeof patch_line);
        if (n > 0) {
            char tokens[48][64];
            int count = 0;
            ui_parse_patch_tokens(patch_line, tokens, &count);
            if (count > 0) {
                int colw = ui_patch_tokens_col_width(tokens, count);
                ui_render_patch_rows(state, tokens, count, colw);
            }
        }
    }
}

typedef struct {
    int slot_no;
    int burst;
    int lasttg;
    int lastsrc;
    int p25_call_emergency;
    int p25_call_priority;
    int payload_algid;
    int payload_keyid;
    unsigned long long payload_mi_dmr;
    unsigned long long payload_mi_p25;
    unsigned int dmr_so;
    unsigned int dmr_fid;
    unsigned long long rc4_key;
    const char* call_banner;
    const char* embedded_gps;
    const char* lrrp_gps;
    const char* talker_alias;
    int aes_loaded;
    unsigned long long aes_a2;
    unsigned long long aes_a4;
} ui_slot_view;

typedef struct {
    int show_ids;
    int show_p25_vxtra;
    int show_crypto_status;
} ui_slot_render_flags;

static ui_slot_view
ui_build_slot_view(const dsd_state* state, int slot_idx) {
    ui_slot_view slot;
    slot.slot_no = slot_idx + 1;
    slot.burst = (slot_idx == 0) ? state->dmrburstL : state->dmrburstR;
    slot.lasttg = (slot_idx == 0) ? state->lasttg : state->lasttgR;
    slot.lastsrc = (slot_idx == 0) ? state->lastsrc : state->lastsrcR;
    slot.p25_call_emergency = state->p25_call_emergency[slot_idx];
    slot.p25_call_priority = state->p25_call_priority[slot_idx];
    slot.payload_algid = (slot_idx == 0) ? state->payload_algid : state->payload_algidR;
    slot.payload_keyid = (slot_idx == 0) ? state->payload_keyid : state->payload_keyidR;
    slot.payload_mi_dmr = (slot_idx == 0) ? state->payload_mi : state->payload_miR;
    slot.payload_mi_p25 = (slot_idx == 0) ? state->payload_miP : state->payload_miN;
    slot.dmr_so = (slot_idx == 0) ? state->dmr_so : state->dmr_soR;
    slot.dmr_fid = (slot_idx == 0) ? state->dmr_fid : state->dmr_fidR;
    slot.rc4_key = (slot_idx == 0) ? state->R : state->RR;
    slot.call_banner = state->call_string[slot_idx];
    slot.embedded_gps = state->dmr_embedded_gps[slot_idx];
    slot.lrrp_gps = state->dmr_lrrp_gps[slot_idx];
    slot.talker_alias = state->generic_talker_alias[slot_idx];
    slot.aes_loaded = state->aes_key_loaded[slot_idx];
    slot.aes_a2 = state->A2[slot_idx];
    slot.aes_a4 = state->A4[slot_idx];
    return slot;
}

static void
ui_restore_call_info_color(const dsd_state* state) {
    if (state->carrier == 1) {
        attron(COLOR_PAIR(3));
    } else {
        attron(COLOR_PAIR(4));
    }
}

static void
ui_render_p25_talker_alias(dsd_state* state, unsigned long src, int alias_index) {
    char group_name[50];
    if (ui_lookup_group_label(state, src, NULL, 0, group_name, sizeof(group_name))) {
        DSD_SNPRINTF(state->generic_talker_alias[alias_index], sizeof state->generic_talker_alias[alias_index], "%s",
                     group_name);
    }
}

static void
ui_render_p25_dmr_header_dmr_bs(const dsd_state* state) {
    printw("DMR BS - DCC: %02i; ", state->dmr_color_code);
    printw("%s ", state->dmr_branding);
    printw("%s", state->dmr_branding_sub);
    printw("%s", state->dmr_site_parms);
    if (state->dmr_rest_channel > 0) {
        printw("Rest LSN: %02d; ", state->dmr_rest_channel);
        if (state->trunk_chan_map[state->dmr_rest_channel] != 0) {
            printw("Freq: %.06lf Mhz", (double)state->trunk_chan_map[state->dmr_rest_channel] / 1000000);
        }
        return;
    }
    if (state->trunk_cc_freq != 0 || state->p25_cc_freq != 0) {
        long f = (state->trunk_cc_freq != 0) ? state->trunk_cc_freq : state->p25_cc_freq;
        printw("Freq: %.06lf MHz", (double)f / 1000000);
    }
}

static void
ui_render_p25_dmr_header_p25p1(const dsd_opts* opts, dsd_state* state) {
    char callsign[7] = {0};
    if (opts->frontend_display.show_p25_callsign_decode && (state->p2_wacn != 0 || state->p2_sysid != 0)) {
        p25_wacn_sysid_to_callsign((uint32_t)state->p2_wacn, (uint16_t)state->p2_sysid, callsign);
    }
    printw("P25p1  - WACN: %05llX SYS: %03llX NAC: %03llX", state->p2_wacn, state->p2_sysid, state->p2_cc);
    if (opts->frontend_display.show_p25_callsign_decode && callsign[0] != '\0' && callsign[0] != ' ') {
        printw(" [%s]", callsign);
    }
    printw("; RFSS: %lld SITE: %lld ", state->p2_rfssid, state->p2_siteid);
    if (state->trunk_cc_freq != 0 || state->p25_cc_freq != 0) {
        long f = (state->trunk_cc_freq != 0) ? state->trunk_cc_freq : state->p25_cc_freq;
        printw("FREQ: %.06lf MHz", (double)f / 1000000);
    }
    ui_render_p25_talker_alias(state, (unsigned long)state->lastsrc, 0);
}

static void
ui_render_p25p2_parameter_status(const dsd_state* state) {
    if (state->p2_wacn == 0 || state->p2_sysid == 0 || state->p2_cc == 0) {
        attron(COLOR_PAIR(2));
        printw(" Phase 2 Missing Parameters ");
        attron(COLOR_PAIR(3));
        return;
    }
    if (state->p2_wacn == 0xFFFFF || state->p2_sysid == 0xFFF || state->p2_cc == 0xFFF) {
        attron(COLOR_PAIR(2));
        printw(" Phase 2 Invalid Parameters ");
        attron(COLOR_PAIR(3));
        return;
    }
    if (state->trunk_cc_freq != 0 || state->p25_cc_freq != 0) {
        long f = (state->trunk_cc_freq != 0) ? state->trunk_cc_freq : state->p25_cc_freq;
        printw("FREQ: %.06lf MHz", (double)f / 1000000);
    }
}

static void
ui_render_p25_dmr_header_p25p2(const dsd_opts* opts, dsd_state* state) {
    char callsign[7] = {0};
    if (opts->frontend_display.show_p25_callsign_decode && (state->p2_wacn != 0 || state->p2_sysid != 0)) {
        p25_wacn_sysid_to_callsign((uint32_t)state->p2_wacn, (uint16_t)state->p2_sysid, callsign);
    }
    printw("P25p2  - WACN: %05llX SYS: %03llX NAC: %03llX", state->p2_wacn, state->p2_sysid, state->p2_cc);
    if (opts->frontend_display.show_p25_callsign_decode && callsign[0] != '\0' && callsign[0] != ' ') {
        printw(" [%s]", callsign);
    }
    printw("; RFSS: %lld SITE: %lld ", state->p2_rfssid, state->p2_siteid);
    ui_render_p25p2_parameter_status(state);
    ui_render_p25_talker_alias(state, (unsigned long)state->lastsrc, 0);
    ui_render_p25_talker_alias(state, (unsigned long)state->lastsrcR, 1);
}

static void
ui_render_p25_dmr_header(const dsd_opts* opts, dsd_state* state) {
    printw("| ");
    if (DSD_SYNC_IS_DMR_BS(ncurses_last_synctype)) {
        ui_render_p25_dmr_header_dmr_bs(state);
    } else if (DSD_SYNC_IS_DMR_MS(ncurses_last_synctype)) {
        printw("DMR MS - DCC: %02i; ", state->dmr_color_code);
    } else if (DSD_SYNC_IS_P25P1(ncurses_last_synctype)) {
        ui_render_p25_dmr_header_p25p1(opts, state);
    } else if (DSD_SYNC_IS_P25P2(ncurses_last_synctype)) {
        ui_render_p25_dmr_header_p25p2(opts, state);
    }
}

static void
ui_render_slot_header_line(const dsd_state* state, const ui_slot_view* slot, ui_slot_render_flags* flags) {
    printw("| SLOT %d - ", slot->slot_no);
    if (slot->burst < 16 && state->carrier == 1 && slot->lasttg > 0 && slot->lastsrc > 0) {
        attron(COLOR_PAIR(2));
    }

    flags->show_ids = ui_burst_is_active_call(slot->burst);
    flags->show_p25_vxtra = ui_burst_has_p25_crypto_metadata(slot->burst);
    flags->show_crypto_status = slot->burst == 16 || flags->show_p25_vxtra;

    if (flags->show_ids) {
        printw("TGT: [%8i] SRC: [%8i] ", slot->lasttg, slot->lastsrc);
        if (slot->p25_call_emergency) {
            printw("[EM] ");
        }
        if (slot->p25_call_priority > 0) {
            printw("[PR:%d] ", slot->p25_call_priority);
        }
    } else {
        printw("TGT: [        ] SRC: [        ] ");
    }

    if (slot->burst != 16 && state->carrier == 1 && slot->lasttg > 0 && slot->lastsrc > 0) {
        attroff(COLOR_PAIR(2));
        attron(COLOR_PAIR(3));
    }
    printw("%s | ", flags->show_ids ? slot->call_banner : "                     ");
    printw("%s ", DMRBusrtTypes[slot->burst]);
    printw("\n");
}

static void
ui_render_slot_p25_dmr_alg_details(const ui_slot_view* slot, int show_p25_vxtra) {
    if (slot->burst == 16 && slot->payload_algid > 0 && (slot->dmr_so & 0x40)) {
        attron(COLOR_PAIR(1));
        printw("ALG: 0x%02X KEY ID: 0x%02X MI: 0x%08llX ", slot->payload_algid, slot->payload_keyid,
               slot->payload_mi_dmr);
        attroff(COLOR_PAIR(1));
        attron(COLOR_PAIR(3));
    }

    if (show_p25_vxtra && slot->payload_algid > 0 && slot->payload_algid != 0x80) {
        attron(COLOR_PAIR(1));
        printw("ALG: 0x%02X KEY ID: 0x%04X MI: 0x%016llX ", slot->payload_algid, slot->payload_keyid,
               slot->payload_mi_p25);
        attroff(COLOR_PAIR(1));
        attron(COLOR_PAIR(3));
    }
}

static int
ui_render_slot_named_crypto_rc4_des(const ui_slot_view* slot, int show_keys) {
    if (slot->payload_algid == 0xAA || slot->payload_algid == 0x21 || slot->payload_algid == 0x01) {
        attron(COLOR_PAIR(1));
        printw("RC4 ");
        if (slot->rc4_key != 0) {
            char key_text[17];
            printw("Key: %s ", dsd_secret_format_hex(key_text, sizeof key_text, show_keys, slot->rc4_key, 10U, 0));
        }
        attron(COLOR_PAIR(3));
        return 1;
    }
    if (slot->payload_algid == 0x81 || slot->payload_algid == 0x22) {
        attron(COLOR_PAIR(1));
        printw("DES1 ");
        if (slot->rc4_key != 0) {
            char key_text[17];
            printw("Key: %s ", dsd_secret_format_hex(key_text, sizeof key_text, show_keys, slot->rc4_key, 16U, 0));
        }
        attron(COLOR_PAIR(3));
        return 1;
    }
    if (slot->payload_algid == 0x9F) {
        attron(COLOR_PAIR(1));
        printw("DES-XL ");
        if (slot->rc4_key != 0) {
            char key_text[17];
            printw("Key: %s ", dsd_secret_format_hex(key_text, sizeof key_text, show_keys, slot->rc4_key, 16U, 0));
        }
        attron(COLOR_PAIR(3));
        return 1;
    }
    if (slot->payload_algid == 0x82) {
        attron(COLOR_PAIR(1));
        printw("DES2 ");
        attron(COLOR_PAIR(3));
        return 1;
    }
    if (slot->payload_algid == 0x83) {
        attron(COLOR_PAIR(1));
        printw("DES3 ");
        attron(COLOR_PAIR(3));
        return 1;
    }
    return 0;
}

static int
ui_render_slot_named_crypto_aes(const ui_slot_view* slot, int show_keys) {
    if (slot->payload_algid == 0x89 || slot->payload_algid == 0x24) {
        attron(COLOR_PAIR(1));
        printw("AES-128 ");
        if (slot->aes_loaded != 0) {
            char key_text[17];
            printw("KS: %s ", dsd_secret_format_hex(key_text, sizeof key_text, show_keys, slot->aes_a2, 16U, 0));
        }
        attron(COLOR_PAIR(3));
        return 1;
    }
    if (slot->payload_algid == 0x84 || slot->payload_algid == 0x25 || slot->payload_algid == 0x05) {
        attron(COLOR_PAIR(1));
        printw("AES-256 ");
        if (slot->aes_loaded != 0) {
            char key_text[17];
            printw("KS: %s ", dsd_secret_format_hex(key_text, sizeof key_text, show_keys, slot->aes_a4, 16U, 0));
        }
        attron(COLOR_PAIR(3));
        return 1;
    }
    return 0;
}

static int
ui_render_slot_named_crypto_vendor(const ui_slot_view* slot, int show_keys) {
    if (slot->payload_algid == 0x02) {
        attron(COLOR_PAIR(1));
        printw("Hytera Enhanced");
        if (slot->rc4_key != 0) {
            char key_text[17];
            printw(" Key: %s", dsd_secret_format_hex(key_text, sizeof key_text, show_keys, slot->rc4_key, 10U, 0));
        }
        attron(COLOR_PAIR(3));
        return 1;
    }
    if (slot->payload_algid == 0x07) {
        attron(COLOR_PAIR(1));
        printw("Vertex Std");
        attron(COLOR_PAIR(3));
        return 1;
    }
    if (slot->payload_algid == 0x36 || slot->payload_algid == 0x37) {
        attron(COLOR_PAIR(1));
        printw((slot->payload_algid == 0x36) ? "Kirisun Adv" : "Kirisun Uni");
        if (slot->aes_loaded != 0) {
            char key_text[17];
            printw(" KS: %s", dsd_secret_format_hex(key_text, sizeof key_text, show_keys, slot->aes_a4, 16U, 0));
        }
        attron(COLOR_PAIR(3));
        return 1;
    }
    return 0;
}

static void
ui_render_slot_named_crypto_details(const ui_slot_view* slot, int show_crypto_status, int show_keys) {
    if (!show_crypto_status) {
        return;
    }
    if (ui_render_slot_named_crypto_rc4_des(slot, show_keys)) {
        return;
    }
    if (ui_render_slot_named_crypto_aes(slot, show_keys)) {
        return;
    }
    (void)ui_render_slot_named_crypto_vendor(slot, show_keys);
}

static void
ui_render_slot_vxtra_line(const dsd_opts* opts, const dsd_state* state, const ui_slot_view* slot,
                          const ui_slot_render_flags* flags) {
    printw("| V XTRA | ");

    if (slot->burst == 16 && slot->payload_algid == 0 && (slot->dmr_so & 0x40)) {
        attron(COLOR_PAIR(5));
        printw(" **BP** ");
        attroff(COLOR_PAIR(5));
        attron(COLOR_PAIR(3));
    }
    if (slot->burst == 16 && slot->payload_algid == 0 && state->K > 0 && slot->dmr_fid == 0x10
        && (slot->dmr_so & 0x40)) {
        attron(COLOR_PAIR(1));
        char key_text[16];
        printw("BP Key: %s ", dsd_secret_format_decimal(key_text, sizeof key_text, opts->show_keys, state->K, 3U));
        attroff(COLOR_PAIR(1));
        attron(COLOR_PAIR(3));
    }
    if (slot->burst == 16 && slot->payload_algid == 0 && state->H > 0 && slot->dmr_fid == 0x68
        && (slot->dmr_so & 0x40)) {
        attron(COLOR_PAIR(1));
        char key_text[17];
        printw("Hytera BP Key: %s ",
               dsd_secret_format_hex(key_text, sizeof key_text, opts->show_keys, state->H, 10U, 0));
        attroff(COLOR_PAIR(1));
        attron(COLOR_PAIR(3));
    }

    ui_render_slot_p25_dmr_alg_details(slot, flags->show_p25_vxtra);
    ui_render_slot_named_crypto_details(slot, flags->show_crypto_status, opts->show_keys);
    printw("\n");
}

static int
ui_slot_has_dxtra_embedded(int slot_no, int burst) {
    if (slot_no == 1) {
        return burst == 16 || burst == 21 || burst == 26 || burst == 27 || burst == 32;
    }
    return burst == 16 || burst == 21;
}

static void
ui_render_slot_group_label(const dsd_state* state, const ui_slot_view* slot, int show_ids) {
    if (!show_ids) {
        return;
    }

    char group_mode[8];
    char group_name[50];
    if (ui_lookup_group_label(state, (unsigned long)slot->lasttg, group_mode, sizeof(group_mode), group_name,
                              sizeof(group_name))) {
        attron(COLOR_PAIR(4));
        printw(" [%s]", group_name);
        printw("[%s] ", group_mode);
    }
}

static void
ui_render_slot_dxtra_line(const dsd_state* state, const ui_slot_view* slot, int show_ids) {
    printw("| D XTRA | ");
    attron(COLOR_PAIR(4));

    if (ui_slot_has_dxtra_embedded(slot->slot_no, slot->burst)) {
        attron(COLOR_PAIR(4));
        printw("%s ", slot->embedded_gps);
        if (slot->talker_alias[0] != '\0') {
            printw("%s ", slot->talker_alias);
        }
        attroff(COLOR_PAIR(5));
        if (state->carrier == 1) {
            attron(COLOR_PAIR(3));
        }
    }

    if (slot->burst != 16) {
        attron(COLOR_PAIR(4));
        printw("%s", slot->lrrp_gps);
    }

    ui_render_slot_group_label(state, slot, show_ids);
    ui_restore_call_info_color(state);
    printw("\n");
}

static void
ui_render_p25_dmr_slot_block(const dsd_opts* opts, const dsd_state* state, const ui_slot_view* slot) {
    ui_slot_render_flags flags = {0};
    ui_render_slot_header_line(state, slot, &flags);
    ui_render_slot_vxtra_line(opts, state, slot, &flags);
    ui_render_slot_dxtra_line(state, slot, flags.show_ids);
}

static void
ui_render_p25_dmr_active_channels_line(const dsd_opts* opts, const dsd_state* state) {
    printw("|        | ");
    attron(COLOR_PAIR(4));
    ui_render_active_channel_list(opts, state, 31);
    printw("\n");
}

static void
ui_render_p25_dmr_tuned_freq_line(const dsd_opts* opts, const dsd_state* state) {
    if (opts->trunk_enable != 1) {
        return;
    }

    printw("|        | ");
    if (opts->trunk_is_tuned == 1) {
        long int vc = (state->trunk_vc_freq[0] != 0) ? state->trunk_vc_freq[0] : state->p25_vc_freq[0];
        if (vc == 0) {
            vc = ui_guess_active_vc_freq(state);
        }
        if (vc != 0) {
            attron(COLOR_PAIR(4));
            printw("Frequency: %.06lf MHz  ", (double)vc / 1000000);
        }
    }
    if (state->tg_hold != 0) {
        printw("TG HOLD: %d", state->tg_hold);
    }
    ui_restore_call_info_color(state);
    printw("\n");
}

static void
ui_render_call_info_p25_dmr(const dsd_opts* opts, dsd_state* state) {
    if (!(DSD_SYNC_IS_P25(ncurses_last_synctype) || DSD_SYNC_IS_DMR(ncurses_last_synctype))) {
        return;
    }

    ui_render_p25_dmr_header(opts, state);
    printw("\n");

    ui_slot_view left = ui_build_slot_view(state, 0);
    ui_slot_view right = ui_build_slot_view(state, 1);
    ui_render_p25_dmr_slot_block(opts, state, &left);
    ui_render_p25_dmr_slot_block(opts, state, &right);
    ui_render_p25_dmr_active_channels_line(opts, state);
    ui_render_p25_dmr_tuned_freq_line(opts, state);
}

static void
ui_render_call_info_and_history(const dsd_opts* opts, dsd_state* state) {
    ui_print_header("Call Info");

    ui_render_call_info_dstar(state);

    ui_render_call_info_m17(state);

    ui_render_call_info_ysf(state);

    ui_render_call_info_nxdn(opts, state);

    ui_render_call_info_p25_dmr(opts, state);

    ui_render_call_info_dpmr(opts, state);

    ui_render_call_info_edacs(opts, state);

    ui_render_call_info_patches(state);

    // Bottom border for Call Info section
    ui_print_hr();

    // Render learned LCNs just under the Call Info section when trunking (toggle in menu)
    if (opts->frontend_display.show_channels == 1) {
        ui_print_learned_lcns(opts, state);
        // fence bottom only when Channels are shown
        ui_print_hr();
    }
    //colors off
    if (state->carrier == 1) { //same as above
        attroff(COLOR_PAIR(3));
    }
    ui_render_event_history_section(state);
}

void
dsd_terminal_render(dsd_opts* opts, dsd_state* state) {
    /* Guard against null opts. Without opts we cannot render safely. */
    if (!opts) {
        return;
    }
    /* Demod path must not touch ncurses. Telemetry is published through
       runtime/app-control hooks, so non-UI-thread calls are render no-ops. */
    if (!ui_is_thread_context()) {
        return;
    }
    int level = 0;

    ui_update_sync_and_edacs_tree(state);

    //Start Printing Section
    erase();
    ui_panel_header_render(opts, state);
    if (state) {
        ui_panel_footer_status_render(opts, state);
    }

    ui_render_input_output_section(opts, state);
    ui_render_rtl_visual_aids(opts, state);

    level = ui_compute_input_level_and_color(opts, state);

    ui_render_audio_decode_section(opts, state, level);

    ui_render_p25_optional_sections(opts, state);

    ui_render_call_info_and_history(opts, state);

    wnoutrefresh(stdscr);

    // Draw menu overlay last so it sits above base UI
    if (ui_menu_is_open()) {
        ui_menu_tick(opts, state);
    }
}
