// SPDX-License-Identifier: GPL-3.0-or-later
/*
 * Copyright (C) 2026 by arancormonk <180709949+arancormonk@users.noreply.github.com>
 */

/**
 * @file
 * @brief NcMenuItem[] array definitions for all menu submenus.
 *
 * This file defines all the static menu item arrays. Top-level menus that
 * need external linkage (referenced by menu_defs.c) are non-static; nested
 * submenu arrays are static.
 */

#include "menu_items.h"

#include "menu_actions.h"
#include "menu_internal.h"
#include "menu_labels.h"

#include <dsd-neo/ui/menu_core.h>

// ============================================================================
// RTL-SDR Menu Items (USE_RTLSDR only)
// ============================================================================
#ifdef USE_RTLSDR
static const NcMenuItem RTL_CTL_ITEMS[] = {
    {.id = "enable", .label = "Enable RTL-SDR Input", .help = "Switch input to RTL-SDR.", .on_select = rtl_enable},
    {.id = "restart",
     .label = "Restart RTL Stream",
     .help = "Apply config by restarting the stream.",
     .on_select = rtl_restart},
    {.id = "dev", .label = "Set Device Index...", .help = "Select RTL device index.", .on_select = rtl_set_dev},
};

static const NcMenuItem RTL_RF_ITEMS[] = {
    {.id = "freq", .label = "Set Frequency (Hz)...", .help = "Set center frequency in Hz.", .on_select = rtl_set_freq},
    {.id = "gain", .label = "Set Gain...", .help = "0=AGC; else driver gain units.", .on_select = rtl_set_gain},
    {.id = "ppm", .label = "Set PPM error...", .help = "-200..200.", .on_select = rtl_set_ppm},
    {.id = "bw", .label = "Set DSP Bandwidth (kHz)...", .help = "4,6,8,12,16,24,48.", .on_select = rtl_set_bw},
    {.id = "sql", .label = "Set Squelch (dB)...", .help = "More negative -> tighter.", .on_select = rtl_set_sql},
    {.id = "vol", .label = "Set Volume Multiplier...", .help = "0..3 sample scaler.", .on_select = rtl_set_vol},
};

static const NcMenuItem RTL_CAL_ITEMS[] = {
    {.id = "auto_ppm",
     .label = "Auto-PPM (Spectrum)",
     .label_fn = lbl_rtl_auto_ppm,
     .help = "Enable/disable spectrum-based auto PPM tracking.",
     .on_select = rtl_toggle_auto_ppm},
    {.id = "tuner_autogain",
     .label = "Tuner Autogain",
     .label_fn = lbl_rtl_tuner_autogain,
     .help = "Enable/disable supervisory tuner autogain.",
     .on_select = rtl_toggle_tuner_autogain},
    {.id = "bias",
     .label = "Toggle Bias Tee",
     .label_fn = lbl_rtl_bias,
     .help = "Enable/disable 5V bias tee (USB or rtl_tcp).",
     .on_select = rtl_toggle_bias},
    {.id = "rtltcp_autotune",
     .label = "RTL-TCP Adaptive Networking",
     .label_fn = lbl_rtl_rtltcp_autotune,
     .help = "Enable/disable adaptive buffering for rtl_tcp.",
     .on_select = rtl_toggle_rtltcp_autotune},
};

const NcMenuItem RTL_MENU_ITEMS[] = {
    {.id = "rtl.ctl",
     .label = "Control...",
     .help = "Stream control and device select.",
     .submenu = RTL_CTL_ITEMS,
     .submenu_len = sizeof RTL_CTL_ITEMS / sizeof RTL_CTL_ITEMS[0]},
    {.id = "rtl.rf",
     .label = "RF & IF Tuning...",
     .help = "RF center/gain, BW, squelch, volume.",
     .submenu = RTL_RF_ITEMS,
     .submenu_len = sizeof RTL_RF_ITEMS / sizeof RTL_RF_ITEMS[0]},
    {.id = "rtl.cal",
     .label = "Calibration & Helpers...",
     .help = "Auto-PPM, autogain, bias tee, RTL-TCP.",
     .submenu = RTL_CAL_ITEMS,
     .submenu_len = sizeof RTL_CAL_ITEMS / sizeof RTL_CAL_ITEMS[0]},
};
#endif

// ============================================================================
// IO Menu Items
// ============================================================================
static const NcMenuItem IO_SWITCH_INPUT_ITEMS[] = {
    {.id = "switch.current", .label = "Current", .label_fn = lbl_current_input, .help = "Shows current input."},
    {.id = "switch.pulse",
     .label = "Pulse Audio (mic/line)",
     .help = "Use Pulse Audio input.",
     .on_select = switch_to_pulse},
#ifdef USE_RTLSDR
    {.id = "switch.rtl", .label = "RTL-SDR", .help = "Switch to RTL-SDR input.", .on_select = switch_to_rtl},
#endif
    {.id = "switch.tcp",
     .label = "TCP Direct Audio...",
     .help = "Connect to PCM16LE over TCP.",
     .on_select = switch_to_tcp},
    {.id = "switch.wav",
     .label = "WAV/File...",
     .help = "Open WAV/RAW file or named pipe.",
     .on_select = switch_to_wav},
    {.id = "switch.sym",
     .label = "Symbol Capture (.bin/.raw/.sym)...",
     .help = "Replay captured symbols.",
     .on_select = switch_to_symbol},
    {.id = "switch.udp", .label = "UDP Signal Input...", .help = "Bind UDP PCM16LE input.", .on_select = switch_to_udp},
};

static const NcMenuItem IO_SWITCH_OUTPUT_ITEMS[] = {
    {.id = "switch.current_out",
     .label = "Current Output",
     .label_fn = lbl_current_output,
     .help = "Shows the active output sink."},
    {.id = "switch.pulse_out",
     .label = "Pulse Digital Output",
     .help = "Play decoded audio via Pulse.",
     .on_select = switch_out_pulse},
    {.id = "switch.udp_out",
     .label = "UDP Audio Output...",
     .help = "Send decoded audio via UDP.",
     .on_select = switch_out_udp},
    {.id = "switch.mute",
     .label = "Mute Output",
     .label_fn = lbl_out_mute,
     .help = "Toggle mute without changing sink.",
     .on_select = switch_out_toggle_mute},
};

static const NcMenuItem IO_INPUT_ITEMS[] = {
    {.id = "io.switch_input",
     .label = "Switch Input...",
     .help = "Change active input source.",
     .submenu = IO_SWITCH_INPUT_ITEMS,
     .submenu_len = sizeof IO_SWITCH_INPUT_ITEMS / sizeof IO_SWITCH_INPUT_ITEMS[0]},
#ifdef USE_RTLSDR
    {.id = "io.rtl",
     .label = "RTL-SDR...",
     .help = "Configure RTL device, gain, PPM, BW, SQL.",
     .is_enabled = io_rtl_active,
     .submenu = RTL_MENU_ITEMS,
     .submenu_len = sizeof RTL_MENU_ITEMS / sizeof RTL_MENU_ITEMS[0]},
#endif
    {.id = "io.pulse_in",
     .label = "Set Pulse Input...",
     .help = "Set Pulse input by index/name.",
     .is_enabled = io_always_on,
     .on_select = io_set_pulse_in},
    {.id = "io.tcp_input",
     .label = "TCP Direct Audio",
     .label_fn = lbl_tcp,
     .help = "Connect to a remote PCM16LE source via TCP.",
     .is_enabled = io_always_on,
     .on_select = io_tcp_direct_link},
    {.id = "io.read_sym",
     .label = "Read Symbol Capture File",
     .help = "Open an existing symbol capture for replay.",
     .is_enabled = io_always_on,
     .on_select = io_read_symbol_bin},
    {.id = "io.replay_last",
     .label = "Replay Last Symbol Capture",
     .label_fn = lbl_replay_last,
     .help = "Re-open the last used symbol capture file.",
     .is_enabled = io_always_on,
     .on_select = io_replay_last_symbol_bin},
    {.id = "io.stop_playback",
     .label = "Stop Symbol Playback",
     .label_fn = lbl_stop_symbol_playback,
     .help = "Stop replaying the symbol capture and restore input mode.",
     .is_enabled = io_always_on,
     .on_select = io_stop_symbol_playback},
};

static const NcMenuItem IO_OUTPUT_ITEMS2[] = {
    {.id = "io.switch_output",
     .label = "Switch Output...",
     .help = "Change audio output sink.",
     .submenu = IO_SWITCH_OUTPUT_ITEMS,
     .submenu_len = sizeof IO_SWITCH_OUTPUT_ITEMS / sizeof IO_SWITCH_OUTPUT_ITEMS[0]},
    {.id = "io.pulse_out",
     .label = "Set Pulse Output...",
     .help = "Set Pulse output by index/name.",
     .is_enabled = io_always_on,
     .on_select = io_set_pulse_out},
    {.id = "io.udp_out",
     .label = "Configure UDP Output...",
     .help = "Set UDP blaster host/port and enable.",
     .on_select = io_set_udp_out},
};

static const NcMenuItem IO_LEVELS_ITEMS[] = {
    {.id = "gain_d", .label = "Set Digital Output Gain...", .help = "0=auto; 1..50.", .on_select = io_set_gain_dig},
    {.id = "gain_a", .label = "Set Analog Output Gain...", .help = "0..100.", .on_select = io_set_gain_ana},
    {.id = "in_vol_set",
     .label = "Set Input Volume...",
     .label_fn = lbl_input_volume,
     .help = "Scale non-RTL inputs by N (1..16).",
     .on_select = io_set_input_volume},
    {.id = "in_vol_up",
     .label = "Input Volume +1X",
     .help = "Increase non-RTL input gain.",
     .on_select = io_input_vol_up},
    {.id = "in_vol_dn",
     .label = "Input Volume -1X",
     .help = "Decrease non-RTL input gain.",
     .on_select = io_input_vol_dn},
    {.id = "monitor",
     .label = "Toggle Source Audio Monitor",
     .label_fn = lbl_monitor,
     .help = "Enable analog source monitor.",
     .on_select = io_toggle_monitor},
    {.id = "input_warn",
     .label = "Low Input Warning (dBFS)",
     .label_fn = lbl_input_warn,
     .help = "Warn if input magnitude below threshold.",
     .on_select = act_set_input_warn},
};

static const NcMenuItem IO_INV_ITEMS[] = {
    {.id = "invert",
     .label = "Toggle Signal Inversion",
     .label_fn = lbl_invert_all,
     .help = "Invert/uninvert all supported inputs.",
     .is_enabled = io_always_on,
     .on_select = act_toggle_invert},
    {.id = "inv_x2",
     .label = "Invert X2-TDMA",
     .label_fn = lbl_inv_x2,
     .help = "Toggle X2 inversion.",
     .on_select = inv_x2},
    {.id = "inv_dmr",
     .label = "Invert DMR",
     .label_fn = lbl_inv_dmr,
     .help = "Toggle DMR inversion.",
     .on_select = inv_dmr},
    {.id = "inv_dpmr",
     .label = "Invert dPMR",
     .label_fn = lbl_inv_dpmr,
     .help = "Toggle dPMR inversion.",
     .on_select = inv_dpmr},
    {.id = "inv_m17",
     .label = "Invert M17",
     .label_fn = lbl_inv_m17,
     .help = "Toggle M17 inversion.",
     .on_select = inv_m17},
};

static const NcMenuItem IO_FILTER_ITEMS[] = {
    {.id = "cosine",
     .label = "Toggle Cosine Filter",
     .label_fn = lbl_cosine,
     .help = "Enable/disable cosine filter.",
     .on_select = io_toggle_cosine},
};

const NcMenuItem IO_MENU_ITEMS[] = {
    {.id = "io.inputs",
     .label = "Inputs...",
     .help = "Select and configure inputs.",
     .submenu = IO_INPUT_ITEMS,
     .submenu_len = sizeof IO_INPUT_ITEMS / sizeof IO_INPUT_ITEMS[0]},
    {.id = "io.outputs",
     .label = "Outputs...",
     .help = "Audio sinks and UDP output.",
     .submenu = IO_OUTPUT_ITEMS2,
     .submenu_len = sizeof IO_OUTPUT_ITEMS2 / sizeof IO_OUTPUT_ITEMS2[0]},
    {.id = "io.levels",
     .label = "Levels & Monitor...",
     .help = "Gains, input volume, monitor.",
     .submenu = IO_LEVELS_ITEMS,
     .submenu_len = sizeof IO_LEVELS_ITEMS / sizeof IO_LEVELS_ITEMS[0]},
    {.id = "io.invert",
     .label = "Inversion...",
     .help = "Per‑protocol inversion toggles.",
     .submenu = IO_INV_ITEMS,
     .submenu_len = sizeof IO_INV_ITEMS / sizeof IO_INV_ITEMS[0]},
    {.id = "io.filters",
     .label = "Filters...",
     .help = "Cosine filter presets.",
     .submenu = IO_FILTER_ITEMS,
     .submenu_len = sizeof IO_FILTER_ITEMS / sizeof IO_FILTER_ITEMS[0]},
};
const size_t IO_MENU_ITEMS_LEN = sizeof IO_MENU_ITEMS / sizeof IO_MENU_ITEMS[0];

// ============================================================================
// Logging & Capture Menu Items
// ============================================================================
static const NcMenuItem LOGGING_CAPTURE_ITEMS[] = {
    {.id = "save_sym",
     .label = "Save Symbols to File",
     .label_fn = lbl_sym_save,
     .help = "Write raw symbols to a capture file for replay.",
     .is_enabled = io_always_on,
     .on_select = io_save_symbol_capture},
    {.id = "stop_save",
     .label = "Stop Symbol Capture",
     .label_fn = lbl_stop_symbol_capture,
     .help = "Close the current symbol capture output file.",
     .is_enabled = io_always_on,
     .on_select = io_stop_symbol_saving},
    {.id = "per_call_wav",
     .label = "Save Per-Call WAV",
     .label_fn = lbl_per_call_wav,
     .help = "Create per-call WAV files under the configured directory.",
     .is_enabled = io_always_on,
     .on_select = io_enable_per_call_wav},
    {.id = "static_wav",
     .label = "Static WAV Output...",
     .help = "Append decoded audio to one WAV file.",
     .on_select = act_static_wav},
    {.id = "raw_wav",
     .label = "Raw Audio WAV...",
     .help = "Write raw 48k/1 input audio to WAV.",
     .on_select = act_raw_wav},
    {.id = "dsp_out",
     .label = "DSP Structured Output...",
     .help = "Write DSP structured or M17 stream to ./DSP/",
     .on_select = act_dsp_out},
};

static const NcMenuItem LOGGING_LOG_ITEMS[] = {
    {.id = "payload",
     .label = "Toggle Payload Logging",
     .label_fn = lbl_toggle_payload,
     .help = "Toggle raw payloads to console.",
     .is_enabled = io_always_on,
     .on_select = act_toggle_payload},
    {.id = "event_on",
     .label = "Set Event Log File...",
     .help = "Append event history to a file.",
     .on_select = act_event_log_set},
    {.id = "event_off",
     .label = "Disable Event Log",
     .help = "Stop logging events to file.",
     .on_select = act_event_log_disable},
    {.id = "crc_relax",
     .label = "Toggle Relaxed CRC checks",
     .label_fn = lbl_crc_relax,
     .help = "Relax CRC checks across protocols.",
     .on_select = act_crc_relax},
    {.id = "reset_eh",
     .label = "Reset Event History",
     .help = "Clear ring-buffered event history.",
     .is_enabled = io_always_on,
     .on_select = act_reset_eh},
    {.id = "call_alert",
     .label = "Toggle Call Alert Beep",
     .label_fn = lbl_call_alert,
     .help = "Audible beep on call start.",
     .is_enabled = io_always_on,
     .on_select = io_toggle_call_alert},
};

const NcMenuItem LOGGING_MENU_ITEMS[] = {
    {.id = "log.capture",
     .label = "Capture...",
     .help = "Symbol/audio capture and structured output.",
     .submenu = LOGGING_CAPTURE_ITEMS,
     .submenu_len = sizeof LOGGING_CAPTURE_ITEMS / sizeof LOGGING_CAPTURE_ITEMS[0]},
    {.id = "log.logging",
     .label = "Logging...",
     .help = "Event/payload logging and housekeeping.",
     .submenu = LOGGING_LOG_ITEMS,
     .submenu_len = sizeof LOGGING_LOG_ITEMS / sizeof LOGGING_LOG_ITEMS[0]},
};
const size_t LOGGING_MENU_ITEMS_LEN = sizeof LOGGING_MENU_ITEMS / sizeof LOGGING_MENU_ITEMS[0];

// ============================================================================
// Trunking & Control Menu Items
// ============================================================================
static const NcMenuItem TRUNK_MODES_ITEMS[] = {
    {.id = "trunk_on",
     .label = "Toggle Trunking",
     .label_fn = lbl_trunk,
     .help = "Enable/disable trunking features.",
     .on_select = act_trunk_toggle},
    {.id = "scan_on",
     .label = "Toggle Scanning Mode",
     .label_fn = lbl_scan,
     .help = "Enable/disable conventional scanning.",
     .on_select = act_scan_toggle},
};

static const NcMenuItem TRUNK_P25_ITEMS[] = {
    {.id = "prefer_cc",
     .label = "Prefer P25 CC Candidates",
     .label_fn = lbl_pref_cc,
     .help = "Prefer viable control-channel candidates during hunt.",
     .is_enabled = io_always_on,
     .on_select = io_toggle_cc_candidates},
    {.id = "lcw_retune",
     .label = "Toggle P25 LCW Retune",
     .label_fn = lbl_lcw,
     .help = "Enable LCW explicit retune.",
     .on_select = act_lcw_toggle},

    {.id = "p25_enc",
     .label = "P25 Encrypted Call Lockout",
     .label_fn = lbl_p25_enc_lockout,
     .help = "Do not tune encrypted calls when On.",
     .on_select = act_p25_enc_lockout},
    {.id = "p2params",
     .label = "Set P25 Phase 2 Parameters",
     .help = "Set WACN/SYSID/NAC manually.",
     .is_enabled = io_always_on,
     .on_select = act_p2_params},
};

static const NcMenuItem TRUNK_RIG_ITEMS[] = {
    {.id = "rigctl",
     .label = "Rigctl",
     .label_fn = lbl_rigctl,
     .help = "Connect to a rigctl server for tuner control.",
     .is_enabled = io_always_on,
     .on_select = io_rigctl_config},
    {.id = "setmod_bw",
     .label = "Set Rigctl Setmod BW...",
     .help = "Set rigctl setmod bandwidth (Hz).",
     .on_select = act_setmod_bw},
};

static const NcMenuItem TRUNK_LISTS_ITEMS[] = {
    {.id = "chan_map",
     .label = "Import Channel Map CSV...",
     .help = "Load channel->frequency map.",
     .on_select = act_import_chan},
    {.id = "group_list",
     .label = "Import Group List CSV...",
     .help = "Load groups allow/block & labels.",
     .on_select = act_import_group},
    {.id = "allow_list",
     .label = "Toggle Allow/White List",
     .label_fn = lbl_allow,
     .help = "Use group list as allow list.",
     .on_select = act_allow_toggle},
    {.id = "tune_group",
     .label = "Toggle Tune Group Calls",
     .label_fn = lbl_tune_group,
     .help = "Enable/disable group call tuning.",
     .on_select = act_tune_group},
    {.id = "tune_priv",
     .label = "Toggle Tune Private Calls",
     .label_fn = lbl_tune_priv,
     .help = "Enable/disable private call tuning.",
     .on_select = act_tune_priv},
    {.id = "tune_data",
     .label = "Toggle Tune Data Calls",
     .label_fn = lbl_tune_data,
     .help = "Enable/disable data call tuning.",
     .on_select = act_tune_data},
    {.id = "tg_hold",
     .label = "Set TG Hold...",
     .help = "Hold on a specific TG while trunking.",
     .on_select = act_tg_hold},
    {.id = "hangtime",
     .label = "Set Hangtime (s)...",
     .help = "VC/sync loss hangtime (seconds).",
     .on_select = act_hangtime},
    {.id = "reverse_mute",
     .label = "Toggle Reverse Mute",
     .label_fn = lbl_rev_mute,
     .help = "Reverse mute behavior.",
     .on_select = act_rev_mute},
};

static const NcMenuItem TRUNK_TDMA_ITEMS[] = {
    {.id = "dmr_le",
     .label = "Toggle DMR Late Entry",
     .label_fn = lbl_dmr_le,
     .help = "Enable/disable DMR late entry.",
     .on_select = act_dmr_le},
    {.id = "slot_pref",
     .label = "Set TDMA Slot Preference...",
     .label_fn = lbl_slotpref,
     .help = "Prefer slot 1 or 2 (DMR/P25p2).",
     .on_select = act_slot_pref},
    {.id = "slots_on",
     .label = "Set TDMA Synth Slots...",
     .label_fn = lbl_slots_on,
     .help = "Bitmask: 1=slot1, 2=slot2, 3=both, 0=off.",
     .on_select = act_slots_on},
};

const NcMenuItem TRUNK_MENU_ITEMS[] = {
    {.id = "trunk.modes",
     .label = "Modes...",
     .help = "Enable trunking or conventional scanning.",
     .submenu = TRUNK_MODES_ITEMS,
     .submenu_len = sizeof TRUNK_MODES_ITEMS / sizeof TRUNK_MODES_ITEMS[0]},
    {.id = "trunk.p25",
     .label = "P25 Options...",
     .help = "Control-channel hunting and follower behavior.",
     .submenu = TRUNK_P25_ITEMS,
     .submenu_len = sizeof TRUNK_P25_ITEMS / sizeof TRUNK_P25_ITEMS[0]},
    {.id = "trunk.rig",
     .label = "Rig Control...",
     .help = "External rig control settings.",
     .submenu = TRUNK_RIG_ITEMS,
     .submenu_len = sizeof TRUNK_RIG_ITEMS / sizeof TRUNK_RIG_ITEMS[0]},
    {.id = "trunk.lists",
     .label = "Lists & Filters...",
     .help = "Channel maps, groups, and tuning filters.",
     .submenu = TRUNK_LISTS_ITEMS,
     .submenu_len = sizeof TRUNK_LISTS_ITEMS / sizeof TRUNK_LISTS_ITEMS[0]},
    {.id = "trunk.tdma",
     .label = "DMR/TDMA...",
     .help = "TDMA slot controls and DMR late entry.",
     .submenu = TRUNK_TDMA_ITEMS,
     .submenu_len = sizeof TRUNK_TDMA_ITEMS / sizeof TRUNK_TDMA_ITEMS[0]},
};
const size_t TRUNK_MENU_ITEMS_LEN = sizeof TRUNK_MENU_ITEMS / sizeof TRUNK_MENU_ITEMS[0];

// ============================================================================
// Keys & Security Menu Items
// ============================================================================
static const NcMenuItem KEYS_ENTRY_ITEMS[] = {
    {.id = "basic", .label = "Basic Privacy (DEC)", .help = "Set 0..255 basic privacy key.", .on_select = key_basic},
    {.id = "hytera",
     .label = "Hytera Privacy (HEX)",
     .label_fn = lbl_key_hytera,
     .help = "Set up to 4 x 16-hex segments.",
     .on_select = key_hytera},
    {.id = "scrambler",
     .label = "NXDN/dPMR Scrambler (DEC)",
     .help = "Set 0..32767 scrambler key.",
     .on_select = key_scrambler},
    {.id = "force_bp",
     .label = "Force BP/Scr Priority",
     .label_fn = lbl_key_force_bp,
     .help = "Toggle basic/scrambler priority.",
     .on_select = key_force_bp},
    {.id = "rc4des", .label = "RC4/DES Key (HEX)", .help = "Set RC4/DES key.", .on_select = key_rc4des},
    {.id = "aes", .label = "AES-128/256 Keys (HEX)", .help = "Set AES key segments.", .on_select = key_aes},
};

static const NcMenuItem KEYS_MANAGE_ITEMS[] = {
    {.id = "keys",
     .label = "Manage Encryption Keys...",
     .help = "Enter or edit BP/Hytera/RC4/AES keys.",
     .submenu = KEYS_ENTRY_ITEMS,
     .submenu_len = sizeof KEYS_ENTRY_ITEMS / sizeof KEYS_ENTRY_ITEMS[0]},
    {.id = "muting",
     .label = "Toggle Encrypted Audio Muting",
     .label_fn = lbl_muting,
     .help = "Toggle P25 and DMR encrypted audio muting.",
     .is_enabled = io_always_on,
     .on_select = io_toggle_mute_enc},
};

static const NcMenuItem KEYS_IMPORT_ITEMS[] = {
    {.id = "keys_dec",
     .label = "Import Keys CSV (DEC)...",
     .help = "Import decimal keys CSV.",
     .on_select = act_keys_dec},
    {.id = "keys_hex",
     .label = "Import Keys CSV (HEX)...",
     .help = "Import hexadecimal keys CSV.",
     .on_select = act_keys_hex},
};

static const NcMenuItem KEYS_KS_ITEMS[] = {
    {.id = "tyt_ap", .label = "TYT AP (PC4) Keystream...", .help = "Enter AP seed string.", .on_select = act_tyt_ap},
    {.id = "retevis_rc2",
     .label = "Retevis AP (RC2) Keystream...",
     .help = "Enter AP seed string.",
     .on_select = act_retevis_rc2},
    {.id = "tyt_ep", .label = "TYT EP (AES) Keystream...", .help = "Enter EP seed string.", .on_select = act_tyt_ep},
    {.id = "ken_scr", .label = "Kenwood DMR Scrambler...", .help = "Enter scrambler seed.", .on_select = act_ken_scr},
    {.id = "anytone_bp", .label = "Anytone BP Keystream...", .help = "Enter BP seed.", .on_select = act_anytone_bp},
    {.id = "xor_ks", .label = "Straight XOR Keystream...", .help = "Enter raw string to XOR.", .on_select = act_xor_ks},
};

static const NcMenuItem KEYS_M17_ITEMS[] = {
    {.id = "m17_ud",
     .label = "M17 Encoder User Data...",
     .label_fn = lbl_m17_user_data,
     .help = "Set M17 encoder CAN/DST/SRC user data.",
     .on_select = act_m17_user_data},
};

const NcMenuItem KEYS_MENU_ITEMS[] = {
    {.id = "keys.manage",
     .label = "Manage...",
     .help = "Enter/edit keys and priorities.",
     .submenu = KEYS_MANAGE_ITEMS,
     .submenu_len = sizeof KEYS_MANAGE_ITEMS / sizeof KEYS_MANAGE_ITEMS[0]},
    {.id = "keys.import",
     .label = "Import...",
     .help = "Import key CSV files.",
     .submenu = KEYS_IMPORT_ITEMS,
     .submenu_len = sizeof KEYS_IMPORT_ITEMS / sizeof KEYS_IMPORT_ITEMS[0]},
    {.id = "keys.ks",
     .label = "Keystreams...",
     .help = "Radio/vendor-specific derivations.",
     .submenu = KEYS_KS_ITEMS,
     .submenu_len = sizeof KEYS_KS_ITEMS / sizeof KEYS_KS_ITEMS[0]},
    {.id = "keys.m17",
     .label = "M17 Encoder...",
     .help = "Set M17 encoder IDs/user data.",
     .submenu = KEYS_M17_ITEMS,
     .submenu_len = sizeof KEYS_M17_ITEMS / sizeof KEYS_M17_ITEMS[0]},
};
const size_t KEYS_MENU_ITEMS_LEN = sizeof KEYS_MENU_ITEMS / sizeof KEYS_MENU_ITEMS[0];

// ============================================================================
// UI Display Menu Items
// ============================================================================
static const NcMenuItem UI_DISPLAY_P25_ITEMS[] = {
    {.id = "p25m",
     .label_fn = lbl_ui_p25_metrics,
     .help = "Toggle P25 Metrics section.",
     .on_select = act_toggle_ui_p25_metrics},
    {.id = "p25aff",
     .label_fn = lbl_ui_p25_affil,
     .help = "Toggle P25 Affiliations section (RID list).",
     .on_select = act_toggle_ui_p25_affil},
    {.id = "p25ga",
     .label_fn = lbl_ui_p25_ga,
     .help = "Toggle P25 Group Affiliation section (RID↔TG).",
     .on_select = act_toggle_ui_p25_ga},
    {.id = "p25nb",
     .label_fn = lbl_ui_p25_neighbors,
     .help = "Toggle P25 Neighbors section (adjacent/candidate freqs).",
     .on_select = act_toggle_ui_p25_neighbors},
    {.id = "p25iden",
     .label_fn = lbl_ui_p25_iden,
     .help = "Toggle P25 IDEN Plan table.",
     .on_select = act_toggle_ui_p25_iden},
    {.id = "p25ccc",
     .label_fn = lbl_ui_p25_ccc,
     .help = "Toggle P25 CC Candidates list.",
     .on_select = act_toggle_ui_p25_ccc},
    {.id = "p25call",
     .label_fn = lbl_ui_p25_callsign,
     .help = "Toggle P25 callsign decode from WACN/SysID (may show false positives).",
     .on_select = act_toggle_ui_p25_callsign},
};

static const NcMenuItem UI_DISPLAY_GENERAL_ITEMS[] = {
    {.id = "chans",
     .label_fn = lbl_ui_channels,
     .help = "Toggle Channels section.",
     .on_select = act_toggle_ui_channels},
};

const NcMenuItem UI_DISPLAY_MENU_ITEMS[] = {
    {.id = "ui.p25",
     .label = "P25 Sections...",
     .help = "Toggle P25-related on-screen sections.",
     .submenu = UI_DISPLAY_P25_ITEMS,
     .submenu_len = sizeof UI_DISPLAY_P25_ITEMS / sizeof UI_DISPLAY_P25_ITEMS[0]},
    {.id = "ui.general",
     .label = "General...",
     .help = "Other UI sections.",
     .submenu = UI_DISPLAY_GENERAL_ITEMS,
     .submenu_len = sizeof UI_DISPLAY_GENERAL_ITEMS / sizeof UI_DISPLAY_GENERAL_ITEMS[0]},
};
const size_t UI_DISPLAY_MENU_ITEMS_LEN = sizeof UI_DISPLAY_MENU_ITEMS / sizeof UI_DISPLAY_MENU_ITEMS[0];

// ============================================================================
// LRRP Menu Items
// ============================================================================
static const NcMenuItem LRRP_STATUS_ITEMS[] = {
    {.id = "lrrp.status",
     .label = "LRRP Output",
     .label_fn = lbl_lrrp_current,
     .help = "Shows the active LRRP output target.",
     .is_enabled = io_always_on},
};

static const NcMenuItem LRRP_DEST_ITEMS[] = {
    {.id = "home",
     .label = "Write to ~/lrrp.txt (QGIS)",
     .help = "Standard QGIS-friendly output.",
     .on_select = lr_home},
    {.id = "dsdp", .label = "Write to ./DSDPlus.LRRP (LRRP.exe)", .help = "DSDPlus LRRP format.", .on_select = lr_dsdp},
    {.id = "custom", .label = "Custom Filename...", .help = "Choose a custom path.", .on_select = lr_custom},
    {.id = "disable", .label = "Disable/Stop", .help = "Disable LRRP output.", .on_select = lr_off},
};

const NcMenuItem LRRP_MENU_ITEMS[] = {
    {.id = "lrrp.status_menu",
     .label = "Status...",
     .help = "Shows current output target.",
     .submenu = LRRP_STATUS_ITEMS,
     .submenu_len = sizeof LRRP_STATUS_ITEMS / sizeof LRRP_STATUS_ITEMS[0]},
    {.id = "lrrp.dest",
     .label = "Destination...",
     .help = "Choose LRRP output file path.",
     .submenu = LRRP_DEST_ITEMS,
     .submenu_len = sizeof LRRP_DEST_ITEMS / sizeof LRRP_DEST_ITEMS[0]},
};
const size_t LRRP_MENU_ITEMS_LEN = sizeof LRRP_MENU_ITEMS / sizeof LRRP_MENU_ITEMS[0];

// ============================================================================
// DSP Menu Items (USE_RTLSDR only)
// ============================================================================
#ifdef USE_RTLSDR
static const NcMenuItem DSP_OVERVIEW_ITEMS[] = {
    {.id = "dsp.status",
     .label = "Show DSP Panel",
     .label_fn = lbl_dsp_panel,
     .help = "Toggle compact DSP status panel in main UI.",
     .on_select = act_toggle_dsp_panel},
};

static const NcMenuItem DSP_PATH_ITEMS[] = {
    {.id = "cqpsk",
     .label = "Toggle CQPSK",
     .label_fn = lbl_onoff_cq,
     .help = "Enable/disable CQPSK path.",
     .on_select = act_toggle_cq},
    {.id = "fll",
     .label = "Toggle FLL",
     .label_fn = lbl_onoff_fll,
     .help = "Enable/disable frequency-locked loop.",
     .is_enabled = is_fll_allowed,
     .on_select = act_toggle_fll},
    {.id = "ted",
     .label = "Timing Error (TED)",
     .label_fn = lbl_onoff_ted,
     .help = "Toggle TED (symbol timing).",
     .is_enabled = is_ted_allowed,
     .on_select = act_toggle_ted},
    {.id = "ted_force",
     .label = "TED Force",
     .label_fn = lbl_ted_force,
     .help = "Force TED even for FM/C4FM/GFSK paths.",
     .is_enabled = is_mod_fm,
     .on_select = act_ted_force_toggle},
    {.id = "c4fm_clk",
     .label = "C4FM Clock Assist",
     .label_fn = lbl_c4fm_clk,
     .help = "Cycle C4FM timing assist: Off → EL → MM.",
     .is_enabled = is_mod_c4fm,
     .on_select = act_c4fm_clk_cycle},
    {.id = "c4fm_clk_sync",
     .label = "C4FM Clock While Synced",
     .label_fn = lbl_c4fm_clk_sync,
     .help = "Allow clock assist to remain active while synchronized.",
     .is_enabled = is_mod_c4fm,
     .on_select = act_c4fm_clk_sync_toggle},
};

static const NcMenuItem DSP_IQ_ITEMS[] = {
    {.id = "iqb",
     .label = "IQ Balance",
     .label_fn = lbl_onoff_iqbal,
     .help = "Toggle IQ imbalance compensation.",
     .is_enabled = is_not_qpsk,
     .on_select = act_toggle_iqbal},
    {.id = "iq_dc",
     .label = "IQ DC Block",
     .label_fn = lbl_iq_dc,
     .help = "Toggle complex DC blocker.",
     .on_select = act_toggle_iq_dc},
    {.id = "iq_dck",
     .label = "IQ DC Shift k (status)",
     .label_fn = lbl_iq_dc_k,
     .help = "k in dc += (x-dc)>>k (6..15)."},
    {.id = "iq_dck+", .label = "Shift k +1", .help = "Increase k.", .on_select = act_iq_dc_k_up},
    {.id = "iq_dck-", .label = "Shift k -1", .help = "Decrease k.", .on_select = act_iq_dc_k_dn},
};

const NcMenuItem DSP_AGC_ITEMS[] = {
    {.id = "fm_agc",
     .label = "FM AGC",
     .label_fn = lbl_fm_agc,
     .help = "Toggle pre-discriminator FM AGC.",
     .is_enabled = is_mod_fm,
     .on_select = act_toggle_fm_agc},

    {.id = "fm_lim",
     .label = "FM Limiter",
     .label_fn = lbl_fm_limiter,
     .help = "Toggle constant-envelope limiter.",
     .is_enabled = is_mod_fm,
     .on_select = act_toggle_fm_limiter},
    {.id = "fm_tgt",
     .label = "AGC Target (status)",
     .label_fn = lbl_fm_agc_target,
     .help = "Target RMS amplitude (normalized float).",
     .is_enabled = is_mod_fm},
    {.id = "fm_tgt+", .label = "AGC Target +0.02", .is_enabled = is_mod_fm, .on_select = act_fm_agc_target_up},
    {.id = "fm_tgt-", .label = "AGC Target -0.02", .is_enabled = is_mod_fm, .on_select = act_fm_agc_target_dn},
    {.id = "fm_min",
     .label = "AGC Min (status)",
     .label_fn = lbl_fm_agc_min,
     .help = "Min RMS to engage AGC.",
     .is_enabled = is_mod_fm},
    {.id = "fm_min+", .label = "AGC Min +0.01", .is_enabled = is_mod_fm, .on_select = act_fm_agc_min_up},
    {.id = "fm_min-", .label = "AGC Min -0.01", .is_enabled = is_mod_fm, .on_select = act_fm_agc_min_dn},
    {.id = "fm_au",
     .label = "AGC Alpha Up (status)",
     .label_fn = lbl_fm_agc_alpha_up,
     .help = "Smoothing when gain increases (0..1).",
     .is_enabled = is_mod_fm},
    {.id = "fm_au+", .label = "Alpha Up +0.05", .is_enabled = is_mod_fm, .on_select = act_fm_agc_alpha_up_up},
    {.id = "fm_au-", .label = "Alpha Up -0.05", .is_enabled = is_mod_fm, .on_select = act_fm_agc_alpha_up_dn},
    {.id = "fm_ad",
     .label = "AGC Alpha Down (status)",
     .label_fn = lbl_fm_agc_alpha_down,
     .help = "Smoothing when gain decreases (0..1).",
     .is_enabled = is_mod_fm},
    {.id = "fm_ad+", .label = "Alpha Down +0.05", .is_enabled = is_mod_fm, .on_select = act_fm_agc_alpha_down_up},
    {.id = "fm_ad-", .label = "Alpha Down -0.05", .is_enabled = is_mod_fm, .on_select = act_fm_agc_alpha_down_dn},
};

const NcMenuItem DSP_TED_ITEMS[] = {
    {.id = "ted_gain_status",
     .label = "TED Gain (status)",
     .label_fn = lbl_ted_gain,
     .help = "TED small gain (Q20).",
     .is_enabled = is_ted_allowed},
    {.id = "ted_gain+",
     .label = "TED Gain +",
     .help = "Increase TED small gain.",
     .is_enabled = is_ted_allowed,
     .on_select = act_ted_gain_up},
    {.id = "ted_gain-",
     .label = "TED Gain -",
     .help = "Decrease TED small gain.",
     .is_enabled = is_ted_allowed,
     .on_select = act_ted_gain_dn},
    {.id = "ted_bias",
     .label = "TED Bias (status)",
     .label_fn = lbl_ted_bias,
     .help = "Smoothed Gardner residual (read-only).",
     .is_enabled = is_ted_allowed},
};
const size_t DSP_AGC_ITEMS_LEN = sizeof DSP_AGC_ITEMS / sizeof DSP_AGC_ITEMS[0];
const size_t DSP_TED_ITEMS_LEN = sizeof DSP_TED_ITEMS / sizeof DSP_TED_ITEMS[0];

const NcMenuItem DSP_MENU_ITEMS[] = {
    {.id = "dsp.overview",
     .label = "Overview...",
     .help = "Global toggles and status.",
     .submenu = DSP_OVERVIEW_ITEMS,
     .submenu_len = sizeof DSP_OVERVIEW_ITEMS / sizeof DSP_OVERVIEW_ITEMS[0]},
    {.id = "dsp.path",
     .label = "Signal Path & Timing...",
     .help = "Demod path selection and timing assists.",
     .submenu = DSP_PATH_ITEMS,
     .submenu_len = sizeof DSP_PATH_ITEMS / sizeof DSP_PATH_ITEMS[0]},
    {.id = "dsp.iq",
     .label = "IQ & Front-End...",
     .help = "IQ balance and DC blocker.",
     .submenu = DSP_IQ_ITEMS,
     .submenu_len = sizeof DSP_IQ_ITEMS / sizeof DSP_IQ_ITEMS[0]},
    {.id = "dsp.agc",
     .label = "AGC & Limiter...",
     .help = "FM AGC, limiter, and parameters.",
     .submenu = DSP_AGC_ITEMS,
     .submenu_len = sizeof DSP_AGC_ITEMS / sizeof DSP_AGC_ITEMS[0],
     .is_enabled = dsp_agc_any},
    {.id = "dsp.ted",
     .label = "TED Controls...",
     .help = "Timing recovery parameters.",
     .submenu = DSP_TED_ITEMS,
     .submenu_len = sizeof DSP_TED_ITEMS / sizeof DSP_TED_ITEMS[0],
     .is_enabled = dsp_ted_any},
};
const size_t DSP_MENU_ITEMS_LEN = sizeof DSP_MENU_ITEMS / sizeof DSP_MENU_ITEMS[0];
#endif

// ============================================================================
// Advanced & Env Submenus
// ============================================================================
static const NcMenuItem P25_FOLLOW_ITEMS[] = {
    {.id = "p25_vc_grace",
     .label = "P25: VC grace (s)",
     .label_fn = lbl_p25_vc_grace,
     .help = "Seconds after VC tune before eligible to return to CC.",
     .on_select = act_set_p25_vc_grace},
    {.id = "p25_min_follow",
     .label = "P25: Min follow dwell (s)",
     .label_fn = lbl_p25_min_follow,
     .help = "Minimum follow dwell after first voice.",
     .on_select = act_set_p25_min_follow},
    {.id = "p25_grant_voice",
     .label = "P25: Grant->Voice timeout (s)",
     .label_fn = lbl_p25_grant_voice,
     .help = "Max seconds from grant to voice before return.",
     .on_select = act_set_p25_grant_voice},
    {.id = "p25_retune_backoff",
     .label = "P25: Retune backoff (s)",
     .label_fn = lbl_p25_retune_backoff,
     .help = "Block immediate re-tune to same VC for N seconds.",
     .on_select = act_set_p25_retune_backoff},
    {.id = "p25_cc_grace",
     .label = "P25: CC hunt grace (s)",
     .label_fn = lbl_p25_cc_grace,
     .help = "Grace period for CC candidate transitions.",
     .on_select = act_set_p25_cc_grace},
    {.id = "p25_force_extra",
     .label = "P25: Safety-net extra (s)",
     .label_fn = lbl_p25_force_extra,
     .help = "Extra seconds beyond hangtime before force-release.",
     .on_select = act_set_p25_force_extra},
    {.id = "p25_force_margin",
     .label = "P25: Safety-net margin (s)",
     .label_fn = lbl_p25_force_margin,
     .help = "Hard margin seconds beyond extra.",
     .on_select = act_set_p25_force_margin},
    {.id = "p25p1_err_pct",
     .label = "P25p1: Err-hold %%",
     .label_fn = lbl_p25_p1_err_pct,
     .help = "IMBE error %% threshold to extend hang.",
     .on_select = act_set_p25_p1_err_pct},
    {.id = "p25p1_err_s",
     .label = "P25p1: Err-hold seconds",
     .label_fn = lbl_p25_p1_err_sec,
     .help = "Additional seconds to hold when threshold exceeded.",
     .on_select = act_set_p25_p1_err_sec},
};

static const NcMenuItem DSP_ADV_ITEMS[] = {
    {.id = "deemph",
     .label = "Deemphasis",
     .label_fn = lbl_deemph,
     .help = "Cycle deemphasis: Unset/Off/50/75/NFM.",
     .on_select = act_deemph_cycle},
    {.id = "audio_lpf",
     .label = "Audio LPF cutoff...",
     .label_fn = lbl_audio_lpf,
     .help = "Set post-demod LPF cutoff in Hz (0=off).",
     .on_select = act_set_audio_lpf},
    {.id = "win_freeze",
     .label = "Freeze Symbol Window",
     .label_fn = lbl_window_freeze,
     .help = "Freeze window selection and disable auto-centering.",
     .on_select = act_window_freeze_toggle},
    {.id = "ftz_daz",
     .label = "SSE FTZ/DAZ",
     .label_fn = lbl_ftz_daz,
     .help = "Toggle Flush-To-Zero / Denormals-Are-Zero (x86 SSE).",
     .on_select = act_toggle_ftz_daz},
};

static const NcMenuItem RTL_TCP_ADV_ITEMS_REAL[] = {
    {.id = "ap_snr",
     .label = "Auto-PPM SNR threshold...",
     .label_fn = lbl_auto_ppm_snr,
     .help = "Minimum SNR to allow spectrum-based PPM tracking.",
     .on_select = act_auto_ppm_snr_prompt},
    {.id = "ap_pwr",
     .label = "Auto-PPM Min power...",
     .label_fn = lbl_auto_ppm_pwr,
     .help = "Minimum spectral power to track PPM.",
     .on_select = act_auto_ppm_pwr_prompt},
    {.id = "ap_zero_ppm",
     .label = "Auto-PPM Zero-lock PPM...",
     .label_fn = lbl_auto_ppm_zeroppm,
     .help = "Snap to PPM=0 when within threshold.",
     .on_select = act_auto_ppm_zeroppm_prompt},
    {.id = "ap_zero_hz",
     .label = "Auto-PPM Zero-lock Hz...",
     .label_fn = lbl_auto_ppm_zerohz,
     .help = "Snap to PPM=0 when within frequency threshold.",
     .on_select = act_auto_ppm_zerohz_prompt},
    {.id = "ap_freeze",
     .label = "Auto-PPM Freeze",
     .label_fn = lbl_auto_ppm_freeze,
     .help = "Temporarily freeze auto-PPM updates.",
     .on_select = act_auto_ppm_freeze},
    {.id = "tcp_prebuf",
     .label = "RTL-TCP Prebuffer (ms)...",
     .label_fn = lbl_tcp_prebuf,
     .help = "Internal prebuffering to absorb jitter.",
     .on_select = act_tcp_prebuf_prompt},
    {.id = "tcp_rcvbuf",
     .label = "RTL-TCP SO_RCVBUF...",
     .label_fn = lbl_tcp_rcvbuf,
     .help = "Socket receive buffer size (bytes).",
     .on_select = act_tcp_rcvbuf_prompt},
    {.id = "tcp_rcvtimeo",
     .label = "RTL-TCP SO_RCVTIMEO...",
     .label_fn = lbl_tcp_rcvtimeo,
     .help = "Socket receive timeout (ms).",
     .on_select = act_tcp_rcvtimeo_prompt},
    {.id = "tcp_waitall",
     .label = "RTL-TCP MSG_WAITALL",
     .label_fn = lbl_tcp_waitall,
     .help = "Enable recv() MSG_WAITALL for full-block reads.",
     .on_select = act_tcp_waitall},
};

static const NcMenuItem RUNTIME_ADV_ITEMS[] = {
    {.id = "rt_sched",
     .label = "Realtime Scheduling",
     .label_fn = lbl_rt_sched,
     .help = "Best-effort realtime threads (requires privileges).",
     .on_select = act_rt_sched},
    {.id = "mt",
     .label = "Intra-block Multithreading",
     .label_fn = lbl_mt,
     .help = "Enable light worker-pool for hot loops.",
     .on_select = act_mt},
};

static const NcMenuItem ENV_EDITOR_ITEMS[] = {
    {.id = "env.edit",
     .label = "Set DSD_NEO_* Variable...",
     .help = "Edit any DSD_NEO_* environment variable.",
     .on_select = act_env_editor},
};

const NcMenuItem CONFIG_MENU_ITEMS[] = {
    {.id = "cfg.save_current",
     .label = "Save Config (Current)",
     .help = "Save current settings to the active config path (loaded via --config or Load Config...).",
     .on_select = act_config_save_current},
    {.id = "cfg.save_default",
     .label = "Save Config (Default)",
     .help = "Save current settings to the default config path.",
     .on_select = act_config_save_default},
    {.id = "cfg.load",
     .label = "Load Config...",
     .help = "Load settings from a config file into this session.",
     .on_select = act_config_load},
    {.id = "cfg.save_as",
     .label = "Save Config As...",
     .help = "Choose a path and save current settings.",
     .on_select = act_config_save_as},
};
const size_t CONFIG_MENU_ITEMS_LEN = sizeof CONFIG_MENU_ITEMS / sizeof CONFIG_MENU_ITEMS[0];

const NcMenuItem ADV_MENU_ITEMS[] = {
    {.id = "p25_follow",
     .label = "P25 Follower Tuning",
     .help = "Adjust P25 SM/follower timing parameters.",
     .submenu = P25_FOLLOW_ITEMS,
     .submenu_len = sizeof P25_FOLLOW_ITEMS / sizeof P25_FOLLOW_ITEMS[0]},
    {.id = "dsp_adv",
     .label = "DSP Advanced",
     .help = "Deemph, LPF, window freeze, FTZ/DAZ.",
     .submenu = DSP_ADV_ITEMS,
     .submenu_len = sizeof DSP_ADV_ITEMS / sizeof DSP_ADV_ITEMS[0]},
    {.id = "rtl_tcp_adv",
     .label = "RTL/TCP Advanced",
     .help = "Auto-PPM thresholds and RTL-TCP socket tuning.",
     .submenu = RTL_TCP_ADV_ITEMS_REAL,
     .submenu_len = sizeof RTL_TCP_ADV_ITEMS_REAL / sizeof RTL_TCP_ADV_ITEMS_REAL[0]},
    {.id = "runtime",
     .label = "Runtime & Threads",
     .help = "Realtime scheduling and light MT.",
     .submenu = RUNTIME_ADV_ITEMS,
     .submenu_len = sizeof RUNTIME_ADV_ITEMS / sizeof RUNTIME_ADV_ITEMS[0]},
    {.id = "env_editor",
     .label = "Environment Editor",
     .help = "Set any DSD_NEO_* variable.",
     .submenu = ENV_EDITOR_ITEMS,
     .submenu_len = sizeof ENV_EDITOR_ITEMS / sizeof ENV_EDITOR_ITEMS[0]},
};
const size_t ADV_MENU_ITEMS_LEN = sizeof ADV_MENU_ITEMS / sizeof ADV_MENU_ITEMS[0];
