// SPDX-License-Identifier: GPL-3.0-or-later
/*
 * Copyright (C) 2026 by arancormonk <180709949+arancormonk@users.noreply.github.com>
 */

/**
 * @file
 * @brief NcMenuItem[] array definitions for every submenu.
 *
 * Placement rules (enforced by tests/ui/test_ui_menu_tree_audit.c):
 *  - One home per concept, chosen by the signal it acts on, not by the module
 *    that implements it: Input > Decoder > Trunking > Encryption > Audio >
 *    Recording & logs > Display > Config > Advanced.
 *  - Within a submenu: status row first, the primary on/off switch, the
 *    settings people change often, then one-shot actions; destructive actions
 *    last, after a separator.
 *  - No single-item submenus; nothing deeper than three levels; no submenu
 *    longer than fifteen rows (what a 24-row terminal shows).
 *  - Labels: `Noun [State]` for toggles (On/Off), `Noun... [current]` for
 *    prompts (submenu rows get " >" from the renderer, never "..."), an
 *    imperative verb only for a one-shot action. Every row that duplicates a
 *    main-screen hotkey shows it.
 *
 * Top-level arrays that menus/menu_defs.c references are non-static; nested
 * submenu arrays are static.
 */

#include "menu_items.h"

#include <dsd-neo/ui/menu_core.h>

#include "menu_actions.h"
#include "menu_labels.h"

#define NC_LEN(arr) (sizeof(arr) / sizeof((arr)[0]))

// ============================================================================
// Input
// ============================================================================
#ifdef USE_RADIO
static const NcMenuItem RTL_TUNING_ADV_ITEMS[] = {
    {.id = "rtl.adv.ap_snr",
     .label_fn = lbl_auto_ppm_snr,
     .help = "Minimum SNR before carrier-assisted PPM tracking may adjust the correction.",
     .on_select = act_auto_ppm_snr_prompt},
    {.id = "rtl.adv.ap_pwr",
     .label_fn = lbl_auto_ppm_pwr,
     .help = "Minimum spectral power before auto-PPM tracks a carrier.",
     .on_select = act_auto_ppm_pwr_prompt},
    {.id = "rtl.adv.ap_zero_ppm",
     .label_fn = lbl_auto_ppm_zeroppm,
     .help = "Snap the correction to 0 PPM when it is already within this many PPM.",
     .on_select = act_auto_ppm_zeroppm_prompt},
    {.id = "rtl.adv.ap_zero_hz",
     .label_fn = lbl_auto_ppm_zerohz,
     .help = "Snap the correction to 0 PPM when the carrier is within this many Hz.",
     .on_select = act_auto_ppm_zerohz_prompt},
    {.id = "rtl.adv.ap_freeze",
     .label_fn = lbl_auto_ppm_freeze,
     .help = "Hold the current auto-PPM correction and stop tracking until turned off.",
     .on_select = act_auto_ppm_freeze},
    {.id = "rtl.adv.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "rtl.adv.tcp_prebuf",
     .label_fn = lbl_tcp_prebuf,
     .help = "Milliseconds of rtl_tcp samples buffered before decoding, to absorb network jitter.",
     .on_select = act_tcp_prebuf_prompt},
    {.id = "rtl.adv.tcp_rcvbuf",
     .label_fn = lbl_tcp_rcvbuf,
     .help = "rtl_tcp socket receive buffer size in bytes; 0 keeps the system default.",
     .on_select = act_tcp_rcvbuf_prompt},
    {.id = "rtl.adv.tcp_rcvtimeo",
     .label_fn = lbl_tcp_rcvtimeo,
     .help = "rtl_tcp socket receive timeout in milliseconds; 0 disables it.",
     .on_select = act_tcp_rcvtimeo_prompt},
    {.id = "rtl.adv.tcp_waitall",
     .label_fn = lbl_tcp_waitall,
     .help = "Ask recv() for full blocks (MSG_WAITALL) on the rtl_tcp socket.",
     .on_select = act_tcp_waitall},
};

static const NcMenuItem RTL_DSP_ITEMS[] = {
    {.id = "rtl.dsp.iqbal",
     .label_fn = lbl_onoff_iqbal,
     .help = "Compensate IQ gain/phase imbalance (not on the CQPSK path).",
     .is_enabled = is_not_qpsk,
     .on_select = act_toggle_iqbal},
    {.id = "rtl.dsp.iq_dc",
     .label_fn = lbl_iq_dc,
     .help = "Remove the DC offset from the complex baseband.",
     .on_select = act_toggle_iq_dc},
    {.id = "rtl.dsp.iq_dck",
     .label_fn = lbl_iq_dc_k,
     .help = "DC blocker time constant k in dc += (x - dc) >> k; larger is slower (6..15).",
     .on_select = act_iq_dc_k_prompt},
    {.id = "rtl.dsp.ted_gain",
     .label_fn = lbl_ted_gain,
     .help = "CQPSK Gardner timing loop gain, in thousandths.",
     .is_enabled = is_ted_allowed,
     .on_select = act_ted_gain_prompt},
    {.id = "rtl.dsp.ted_bias",
     .label_fn = lbl_cqpsk_timing_bias,
     .help = "Smoothed Gardner timing residual (read-only).",
     .is_enabled = is_ted_allowed,
     .kind = NC_ITEM_STATUS},
};

static const NcMenuItem RTL_MENU_ITEMS[] = {
    {.id = "rtl.freq", .label_fn = lbl_rtl_freq, .help = "Set the center frequency in Hz.", .on_select = rtl_set_freq},
    {.id = "rtl.gain",
     .label_fn = lbl_rtl_gain,
     .help = "Tuner gain in driver units; 0 hands gain to the AGC.",
     .on_select = rtl_set_gain},
    {.id = "rtl.ppm",
     .label_fn = lbl_rtl_ppm,
     .help = "Frequency correction in parts per million (-200..200).",
     .hotkey = "{ }",
     .on_select = rtl_set_ppm},
    {.id = "rtl.bw",
     .label_fn = lbl_rtl_bw,
     .help = "DSP bandwidth in kHz: 4, 6, 8, 12, 16, 24 or 48.",
     .on_select = rtl_set_bw},
    {.id = "rtl.sql",
     .label = "Squelch (dB)...",
     .help = "Post-filter squelch threshold in dB; more negative opens more; 0 switches squelch off.",
     .on_select = rtl_set_sql},
    /* 'v' is here as well as on Input > Input volume: the key drives whichever of the
       two multipliers matches the live input type, and on RTL that is this row. */
    {.id = "rtl.vol",
     .label_fn = lbl_rtl_vol,
     .help = "Monitor audio sample scaler (0..3). The hotkey cycles it while the RTL front end is the input.",
     .hotkey = "v",
     .on_select = rtl_set_vol},
    {.id = "rtl.auto_ppm",
     .label_fn = lbl_rtl_auto_ppm,
     .help = "Track the PPM correction from a carrier automatically.",
     .on_select = rtl_toggle_auto_ppm},
    {.id = "rtl.tuner_autogain",
     .label_fn = lbl_rtl_tuner_autogain,
     .help = "Let the supervisory loop steer the tuner gain.",
     .on_select = rtl_toggle_tuner_autogain},
    {.id = "rtl.bias",
     .label_fn = lbl_rtl_bias,
     .help = "5 V bias tee on the antenna port (USB or rtl_tcp).",
     .on_select = rtl_toggle_bias},
    {.id = "rtl.rtltcp_autotune",
     .label_fn = lbl_rtl_rtltcp_autotune,
     .help = "Adapt rtl_tcp buffering to the measured network jitter.",
     .on_select = rtl_toggle_rtltcp_autotune},
    {.id = "rtl.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "rtl.dev",
     .label = "Device index...",
     .help = "Select which RTL-SDR device to open.",
     .on_select = rtl_set_dev},
    {.id = "rtl.restart",
     .label = "Restart stream",
     .help = "Reopen the device so pending device settings take effect.",
     .on_select = rtl_restart},
    {.id = "rtl.tuning_adv",
     .label = "Auto-PPM & rtl_tcp",
     .help = "Auto-PPM thresholds and rtl_tcp socket tuning.",
     .submenu = RTL_TUNING_ADV_ITEMS,
     .submenu_len = NC_LEN(RTL_TUNING_ADV_ITEMS)},
    {.id = "rtl.dsp",
     .label = "IQ & CQPSK timing",
     .help = "IQ balance, DC blocker, CQPSK Gardner timing loop.",
     .submenu = RTL_DSP_ITEMS,
     .submenu_len = NC_LEN(RTL_DSP_ITEMS)},
};
#endif

static const NcMenuItem INPUT_SOURCE_ITEMS[] = {
    {.id = "src.pulse",
     .label = "Pulse Audio (mic/line)",
     .help = "Decode the default Pulse Audio input.",
     .on_select = switch_to_pulse},
    {.id = "src.pulse_dev",
     .label = "Pulse input device...",
     .help = "Pick the Pulse input by index or name.",
     .on_select = io_set_pulse_in},
#ifdef USE_RADIO
    {.id = "src.rtl", .label = "RTL-SDR", .help = "Decode from the RTL-SDR front end.", .on_select = switch_to_rtl},
#endif
    {.id = "src.tcp",
     .label_fn = lbl_tcp,
     .help = "Connect to a remote PCM16LE audio source over TCP.",
     .hotkey = "8",
     .on_select = io_tcp_direct_link},
    {.id = "src.udp",
     .label = "UDP audio...",
     .help = "Bind a UDP port for PCM16LE audio.",
     .on_select = switch_to_udp},
    {.id = "src.wav",
     .label = "WAV / raw file...",
     .help = "Decode a WAV or raw PCM file, or a named pipe.",
     .on_select = switch_to_wav},
    {.id = "src.sym",
     .label = "Symbol file (.bin/.raw/.sym)...",
     .help = "Replay a symbol capture (.bin) or feed a symbol stream (.raw/.sym).",
     .on_select = switch_to_symbol},
};

const NcMenuItem INPUT_MENU_ITEMS[] = {
    {.id = "input.current", .label_fn = lbl_current_input, .kind = NC_ITEM_STATUS},
    {.id = "input.switch",
     .label = "Switch source",
     .help = "Change the active input source.",
     .submenu = INPUT_SOURCE_ITEMS,
     .submenu_len = NC_LEN(INPUT_SOURCE_ITEMS)},
    {.id = "input.volume",
     .label_fn = lbl_input_volume,
     .help = "Scale non-RTL inputs by 1..16. The hotkey cycles this only while the input is not the RTL front end; "
             "on RTL it cycles Input > RTL-SDR > Volume multiplier instead.",
     .hotkey = "v",
     .on_select = io_set_input_volume},
    {.id = "input.warn",
     .label_fn = lbl_input_warn,
     .help = "Warn in the footer when the input level falls below this many dBFS.",
     .on_select = act_set_input_warn},
    {.id = "input.invert",
     .label_fn = lbl_invert_all,
     .help = "Invert or uninvert all supported inputs at once.",
     .hotkey = "i",
     .on_select = act_toggle_invert},
#ifdef USE_RADIO
    {.id = "input.rtl",
     .label = "RTL-SDR",
     .help = "Frequency, gain, PPM, bandwidth, squelch, calibration, device.",
     .is_enabled = io_rtl_active,
     .submenu = RTL_MENU_ITEMS,
     .submenu_len = NC_LEN(RTL_MENU_ITEMS)},
#endif
};
const size_t INPUT_MENU_ITEMS_LEN = NC_LEN(INPUT_MENU_ITEMS);

// ============================================================================
// Decoder
// ============================================================================
static const NcMenuItem DEC_FILTER_ITEMS[] = {
    {.id = "flt.lpf",
     .label_fn = lbl_lpf,
     .help = "Low-pass filter on the input audio.",
     .hotkey = "V",
     .on_select = act_lpf_toggle},
    {.id = "flt.hpf",
     .label_fn = lbl_hpf,
     .help = "High-pass filter on the input audio.",
     .hotkey = "B",
     .on_select = act_hpf_toggle},
    {.id = "flt.pbf",
     .label_fn = lbl_pbf,
     .help = "Pulse-shaping band-pass filter on the input audio.",
     .hotkey = "N",
     .on_select = act_pbf_toggle},
    {.id = "flt.hpfd",
     .label_fn = lbl_hpf_d,
     .help = "High-pass filter on the decoded digital audio.",
     .hotkey = "H",
     .on_select = act_hpf_d_toggle},
    {.id = "flt.cosine", .label_fn = lbl_cosine, .help = "Raised-cosine symbol filter.", .on_select = io_toggle_cosine},
};

static const NcMenuItem DEC_INV_ITEMS[] = {
    {.id = "inv.x2", .label_fn = lbl_inv_x2, .help = "Invert X2-TDMA polarity.", .on_select = inv_x2},
    {.id = "inv.dmr", .label_fn = lbl_inv_dmr, .help = "Invert DMR polarity.", .on_select = inv_dmr},
    {.id = "inv.dpmr", .label_fn = lbl_inv_dpmr, .help = "Invert dPMR polarity.", .on_select = inv_dpmr},
    {.id = "inv.m17", .label_fn = lbl_inv_m17, .help = "Invert M17 polarity.", .on_select = inv_m17},
};

static const NcMenuItem DEC_TDMA_ITEMS[] = {
    {.id = "tdma.le",
     .label_fn = lbl_dmr_le,
     .help = "Join DMR voice calls already in progress.",
     .on_select = act_dmr_le},
    {.id = "tdma.slot1",
     .label_fn = lbl_slot1,
     .help = "Synthesize and play audio from slot 1.",
     .hotkey = "1",
     .on_select = act_slot1_toggle},
    {.id = "tdma.slot2",
     .label_fn = lbl_slot2,
     .help = "Synthesize and play audio from slot 2.",
     .hotkey = "2",
     .on_select = act_slot2_toggle},
    {.id = "tdma.pref",
     .label_fn = lbl_slotpref,
     .help = "Which slot wins when both carry voice (DMR, P25 Phase 2).",
     .hotkey = "3",
     .on_select = act_slot_pref},
    {.id = "tdma.reset",
     .label = "DMR reset",
     .help = "Clear DMR rest-channel and manufacturer state when a system goes off the rails.",
     .hotkey = "D",
     .on_select = act_dmr_reset},
};

const NcMenuItem DECODER_MENU_ITEMS[] = {
    {.id = "dec.mode",
     .label_fn = lbl_decode_mode,
     .help = "Choose which protocols are decoded. Takes effect immediately.",
     .on_select = act_decode_mode},
    {.id = "dec.mod",
     .label_fn = lbl_modulation,
     .help = "Cycle the demodulator: C4FM, QPSK, GFSK.",
     .hotkey = "m",
     .on_select = act_mod_cycle},
    {.id = "dec.p2lock",
     .label_fn = lbl_p25p2_mod_lock,
     .help = "Pin P25 Phase 2 to C4FM or QPSK instead of letting the hunt choose.",
     .hotkey = "M",
     .on_select = act_mod_p2_toggle},
#ifdef USE_RADIO
    {.id = "dec.cqpsk",
     .label_fn = lbl_onoff_cq,
     .help = "Run the RTL front end through the CQPSK demodulator path.",
     .is_enabled = io_rtl_active,
     .on_select = act_toggle_cq},
#endif
    {.id = "dec.filters",
     .label = "Audio filters",
     .help = "Input and digital audio filters.",
     .submenu = DEC_FILTER_ITEMS,
     .submenu_len = NC_LEN(DEC_FILTER_ITEMS)},
    {.id = "dec.inversion",
     .label = "Per-protocol inversion",
     .help = "Polarity per protocol; Input > Invert signal flips them all.",
     .submenu = DEC_INV_ITEMS,
     .submenu_len = NC_LEN(DEC_INV_ITEMS)},
    {.id = "dec.crc",
     .label_fn = lbl_crc_relax,
     .help = "Relax CRC checks and frame-sync strictness across protocols.",
     .hotkey = "F",
     .on_select = act_crc_relax},
    {.id = "dec.tdma",
     .label = "DMR / TDMA",
     .help = "Slot audio, slot preference, late entry, DMR reset.",
     .submenu = DEC_TDMA_ITEMS,
     .submenu_len = NC_LEN(DEC_TDMA_ITEMS)},
    {.id = "dec.pv_esk",
     .label_fn = lbl_provoice_esk,
     .help = "Apply the ProVoice ESK mask.",
     .hotkey = "A",
     .is_enabled = provoice_active,
     .on_select = act_provoice_esk},
    {.id = "dec.pv_mode",
     .label_fn = lbl_provoice_mode,
     .help = "Switch ProVoice between standard and extended addressing.",
     .hotkey = "S",
     .is_enabled = provoice_active,
     .on_select = act_provoice_mode},
    {.id = "dec.m17",
     .label_fn = lbl_m17_user_data,
     .help = "CAN, destination and source for the M17 encoder.",
     .on_select = act_m17_user_data},
};
const size_t DECODER_MENU_ITEMS_LEN = NC_LEN(DECODER_MENU_ITEMS);

// ============================================================================
// Trunking
// ============================================================================
static const NcMenuItem TRUNK_FOLLOW_ITEMS[] = {
    {.id = "follow.group",
     .label_fn = lbl_tune_group,
     .help = "Follow group voice calls.",
     .hotkey = "g",
     .on_select = act_tune_group},
    {.id = "follow.priv",
     .label_fn = lbl_tune_priv,
     .help = "Follow private voice calls.",
     .hotkey = "u",
     .on_select = act_tune_priv},
    {.id = "follow.data",
     .label_fn = lbl_tune_data,
     .help = "Follow data calls.",
     .hotkey = "d",
     .on_select = act_tune_data},
    {.id = "follow.allow",
     .label_fn = lbl_allow,
     .help = "Only follow groups marked allowed in the imported group list.",
     .hotkey = "w",
     .on_select = act_allow_toggle},
    {.id = "follow.tg_hold",
     .label_fn = lbl_tg_hold,
     .help = "Stay on one talkgroup; 0 clears. The hotkeys hold the current call on slot 1 / slot 2.",
     .hotkey = "k/l",
     .on_select = act_tg_hold},
    {.id = "follow.hangtime",
     .label_fn = lbl_hangtime,
     .help = "Seconds to stay on a voice channel after the call ends before returning.",
     .on_select = act_hangtime},
    {.id = "follow.voice_only",
     .label_fn = lbl_scan_voice_only,
     .help = "Only stop the scan on voice; skip carriers without decoded voice.",
     .on_select = act_scan_voice_only},
    {.id = "follow.voice_qualify",
     .label_fn = lbl_scan_voice_qualify,
     .help = "Voice qualify window in ms: window after sync in which voice must appear or the scan moves on.",
     .on_select = act_scan_voice_qualify},
    {.id = "follow.voice_hold",
     .label_fn = lbl_scan_voice_hold,
     .help = "Voice hold in ms: time to stay after the last voice frame.",
     .on_select = act_scan_voice_hold},
    {.id = "follow.rev_mute",
     .label_fn = lbl_rev_mute,
     .help = "Mute clear voice and play encrypted voice instead.",
     .on_select = act_rev_mute},
    {.id = "follow.lock1",
     .label = "Lock out talkgroup on slot 1",
     .help = "Stop following the talkgroup currently on slot 1 for this session.",
     .hotkey = "!",
     .on_select = act_lockout_slot1},
    {.id = "follow.lock2",
     .label = "Lock out talkgroup on slot 2",
     .help = "Stop following the talkgroup currently on slot 2 for this session.",
     .hotkey = "@",
     .on_select = act_lockout_slot2},
};

static const NcMenuItem TRUNK_LISTS_ITEMS[] = {
    {.id = "lists.chan",
     .label = "Import channel map CSV...",
     .help = "Load a channel-to-frequency map.",
     .on_select = act_import_chan},
    {.id = "lists.group",
     .label = "Import group list CSV...",
     .help = "Load group labels and allow/block flags; a parse failure keeps the current list.",
     .on_select = act_import_group},
    {.id = "lists.p25_bandplan",
     .label = "Import P25 band plan CSV...",
     .help = "Load a P25 band plan (IDEN table) for sites that never send IDEN_UP.",
     .on_select = act_import_p25_bandplan},
    {.id = "lists.p25_bandplan_export",
     .label = "Export learned P25 band plan...",
     .help = "Write the IDEN tables learned on this system to a band plan CSV.",
     .on_select = act_export_p25_bandplan},
    {.id = "lists.sep", .is_enabled = rr_feature_available, .kind = NC_ITEM_SEPARATOR},
    {.id = "lists.rr_import",
     .label = "Import from RadioReference...",
     .help = "Build talkgroup and channel-map CSVs from the RadioReference database (premium account "
             "required) and apply them to this session.",
     .is_enabled = rr_feature_available,
     .on_select = act_rr_import},
    {.id = "lists.rr_imported",
     .label = "Imported RadioReference systems...",
     .help = "Browse imported systems: apply one to this session, refresh it, or delete its files.",
     .is_enabled = rr_imports_available_and_feature,
     .on_select = act_rr_library},
    {.id = "lists.rr_user",
     .label_fn = lbl_rr_account,
     .help = "RadioReference account username (stored in config; the password is asked once per session "
             "and never stored).",
     .is_enabled = rr_feature_available,
     .on_select = act_rr_account_user},
    {.id = "lists.rr_key",
     .label = "RadioReference application key...",
     .help = "RadioReference application key, for builds without a baked-in key.",
     .is_enabled = rr_key_prompt_offered_and_feature,
     .on_select = act_rr_account_key},
};

static const NcMenuItem P25_TIMING_ITEMS[] = {
    {.id = "p25t.vc_grace",
     .label_fn = lbl_p25_vc_grace,
     .help = "Seconds after tuning a voice channel before returning to the control channel is allowed.",
     .on_select = act_set_p25_vc_grace},
    {.id = "p25t.min_follow",
     .label_fn = lbl_p25_min_follow,
     .help = "Minimum seconds to stay on a voice channel after the first voice.",
     .on_select = act_set_p25_min_follow},
    {.id = "p25t.grant_voice",
     .label_fn = lbl_p25_grant_voice,
     .help = "Seconds to wait for voice after a grant before returning.",
     .on_select = act_set_p25_grant_voice},
    {.id = "p25t.cc_grace",
     .label_fn = lbl_p25_cc_grace,
     .help = "Grace period while moving between control-channel candidates.",
     .on_select = act_set_p25_cc_grace},
    {.id = "p25t.force_extra",
     .label_fn = lbl_p25_force_extra,
     .help = "Extra seconds beyond hangtime before the safety net forces a release.",
     .on_select = act_set_p25_force_extra},
    {.id = "p25t.force_margin",
     .label_fn = lbl_p25_force_margin,
     .help = "Hard margin beyond the extra seconds.",
     .on_select = act_set_p25_force_margin},
    {.id = "p25t.p1_err_pct",
     .label_fn = lbl_p25_p1_err_pct,
     .help = "IMBE error percentage above which Phase 1 calls are held longer.",
     .on_select = act_set_p25_p1_err_pct},
    {.id = "p25t.p1_err_s",
     .label_fn = lbl_p25_p1_err_sec,
     .help = "Seconds added to the hold when the error threshold is exceeded.",
     .on_select = act_set_p25_p1_err_sec},
};

static const NcMenuItem TRUNK_P25_ITEMS[] = {
    {.id = "p25.prefer_cc",
     .label_fn = lbl_pref_cc,
     .help = "Prefer control-channel candidates heard over the air while hunting.",
     .on_select = io_toggle_cc_candidates},
    {.id = "p25.lcw",
     .label_fn = lbl_lcw,
     .help = "Retune on explicit link-control channel updates.",
     .on_select = act_lcw_toggle},
    {.id = "p25.p2params",
     .label = "Phase 2 parameters...",
     .help = "Enter WACN, system ID and NAC by hand.",
     .on_select = act_p2_params},
    {.id = "p25.timing",
     .label = "Timing",
     .help = "Follower and control-channel timers.",
     .submenu = P25_TIMING_ITEMS,
     .submenu_len = NC_LEN(P25_TIMING_ITEMS)},
};

const NcMenuItem TRUNK_MENU_ITEMS[] = {
    {.id = "trunk.on",
     .label_fn = lbl_trunk,
     .help = "Follow calls on a trunked system.",
     .hotkey = "t",
     .on_select = act_trunk_toggle},
    {.id = "trunk.scan",
     .label_fn = lbl_scan,
     .help = "Scan the channel map as a conventional scanner.",
     .hotkey = "y",
     .on_select = act_scan_toggle},
    {.id = "trunk.return_cc",
     .label = "Return to control channel",
     .help = "Leave the voice channel now.",
     .hotkey = "C",
     .is_enabled = trunk_enabled,
     .on_select = act_return_cc},
    {.id = "trunk.cycle",
     .label = "Next channel",
     .help = "Step to the next channel in the map, or the next trunk-scan target.",
     .hotkey = "L",
     .is_enabled = trunk_enabled,
     .on_select = act_channel_cycle},
    {.id = "trunk.hold",
     .label_fn = lbl_scan_hold,
     .help = "Stay on the channel or trunk-scan target on air; Next channel still moves. Off resumes the rotation.",
     .hotkey = "Y",
     .is_enabled = scan_rotation_active,
     .on_select = act_scan_hold_toggle},
    {.id = "trunk.avoid",
     .label = "Avoid current channel",
     .help = "Skip the channel or trunk-scan target on air for the rest of the session and step to the next one.",
     .hotkey = "b",
     .is_enabled = scan_rotation_active,
     .on_select = act_scan_avoid},
    {.id = "trunk.avoid_clear",
     .label_fn = lbl_scan_avoid_clear,
     .help = "Put every avoided channel or trunk-scan target back into the rotation.",
     .is_enabled = scan_rotation_active,
     .on_select = act_scan_avoid_clear},
    {.id = "trunk.sep1", .kind = NC_ITEM_SEPARATOR},
    {.id = "trunk.follow",
     .label = "Follow",
     .help = "Which calls to follow, talkgroup hold, hangtime, lockouts.",
     .submenu = TRUNK_FOLLOW_ITEMS,
     .submenu_len = NC_LEN(TRUNK_FOLLOW_ITEMS)},
    {.id = "trunk.lists",
     .label = "Channels & groups",
     .help = "Channel maps and group lists, by CSV or from RadioReference.",
     .submenu = TRUNK_LISTS_ITEMS,
     .submenu_len = NC_LEN(TRUNK_LISTS_ITEMS)},
    {.id = "trunk.p25",
     .label = "P25",
     .help = "Control-channel hunting, retune, Phase 2 parameters, timers.",
     .submenu = TRUNK_P25_ITEMS,
     .submenu_len = NC_LEN(TRUNK_P25_ITEMS)},
    {.id = "trunk.sep2", .kind = NC_ITEM_SEPARATOR},
    {.id = "trunk.rigctl",
     .label_fn = lbl_rigctl,
     .help = "Tune an external radio through a rigctl server.",
     .hotkey = "9",
     .on_select = io_rigctl_config},
    {.id = "trunk.setmod",
     .label = "Rigctl setmod bandwidth...",
     .help = "Bandwidth in Hz passed with rigctl setmod.",
     .on_select = act_setmod_bw},
};
const size_t TRUNK_MENU_ITEMS_LEN = NC_LEN(TRUNK_MENU_ITEMS);

// ============================================================================
// Encryption
// ============================================================================
static const NcMenuItem KEYS_ENTRY_ITEMS[] = {
    {.id = "key.basic",
     .label = "Basic privacy key (decimal)...",
     .help = "Basic privacy key, 0..255.",
     .on_select = key_basic},
    {.id = "key.hytera",
     .label_fn = lbl_key_hytera,
     .help = "Hytera privacy key as up to four 16-hex-digit segments.",
     .on_select = key_hytera},
    {.id = "key.scr",
     .label = "NXDN/dPMR scrambler key (decimal)...",
     .help = "Scrambler key, 0..32767.",
     .on_select = key_scrambler},
    {.id = "key.rc4des", .label = "RC4 / DES key (hex)...", .help = "RC4 or DES key.", .on_select = key_rc4des},
    {.id = "key.aes", .label = "AES-128/256 key (hex)...", .help = "AES key segments.", .on_select = key_aes},
    {.id = "key.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "key.force_bp",
     .label_fn = lbl_key_force_bp,
     .help = "Apply the basic privacy or scrambler key even when the call does not signal one.",
     .hotkey = "4",
     .on_select = key_force_bp},
    {.id = "key.force_rc4",
     .label_fn = lbl_key_force_rc4,
     .help = "Apply the RC4 key when the PI header or link control identifiers are missing.",
     .hotkey = "6",
     .on_select = act_force_rc4},
};

static const NcMenuItem KEYS_KS_ITEMS[] = {
    {.id = "ks.tyt_ap",
     .label = "TYT AP (PC4) keystream...",
     .help = "Derive a keystream from a TYT AP seed.",
     .on_select = act_tyt_ap},
    {.id = "ks.retevis_rc2",
     .label = "Retevis AP (RC2) keystream...",
     .help = "Derive a keystream from a Retevis AP seed.",
     .on_select = act_retevis_rc2},
    {.id = "ks.tyt_ep",
     .label = "TYT EP (AES) keystream...",
     .help = "Derive a keystream from a TYT EP seed.",
     .on_select = act_tyt_ep},
    {.id = "ks.ken_scr",
     .label = "Kenwood DMR scrambler...",
     .help = "Kenwood scrambler seed.",
     .on_select = act_ken_scr},
    {.id = "ks.anytone_bp",
     .label = "Anytone BP keystream...",
     .help = "Anytone basic privacy seed.",
     .on_select = act_anytone_bp},
    {.id = "ks.xor",
     .label = "Straight XOR keystream...",
     .help = "Raw bytes to XOR against the payload.",
     .on_select = act_xor_ks},
};

const NcMenuItem ENC_MENU_ITEMS[] = {
    {.id = "enc.mute",
     .label_fn = lbl_muting,
     .help = "Silence P25 and DMR voice that cannot be decrypted.",
     .on_select = io_toggle_mute_enc},
    {.id = "enc.lockout",
     .label_fn = lbl_p25_enc_lockout,
     .help = "Stop following targets confirmed encrypted for the rest of the session; loading a key re-checks them.",
     .hotkey = "e",
     .on_select = act_p25_enc_lockout},
    {.id = "enc.clear",
     .label_fn = lbl_enc_lockout_clear,
     .help = "Forget every locked-out encrypted target so each can be re-verified.",
     .on_select = act_enc_lockout_clear},
    {.id = "enc.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "enc.keys",
     .label = "Keys",
     .help = "Enter basic privacy, Hytera, scrambler, RC4/DES and AES keys.",
     .submenu = KEYS_ENTRY_ITEMS,
     .submenu_len = NC_LEN(KEYS_ENTRY_ITEMS)},
    {.id = "enc.import_dec",
     .label = "Import keys CSV (decimal)...",
     .help = "Load a keys CSV with decimal values.",
     .on_select = act_keys_dec},
    {.id = "enc.import_hex",
     .label = "Import keys CSV (hex)...",
     .help = "Load a keys CSV with hexadecimal values.",
     .on_select = act_keys_hex},
    {.id = "enc.ks",
     .label = "Vendor keystreams",
     .help = "Radio-specific keystream derivations.",
     .submenu = KEYS_KS_ITEMS,
     .submenu_len = NC_LEN(KEYS_KS_ITEMS)},
};
const size_t ENC_MENU_ITEMS_LEN = NC_LEN(ENC_MENU_ITEMS);

// ============================================================================
// Audio
// ============================================================================
static const NcMenuItem AUDIO_SINK_ITEMS[] = {
    {.id = "sink.pulse",
     .label = "Pulse digital output",
     .help = "Play decoded audio through Pulse Audio.",
     .on_select = switch_out_pulse},
    {.id = "sink.pulse_dev",
     .label = "Pulse output device...",
     .help = "Pick the Pulse output by index or name.",
     .on_select = io_set_pulse_out},
    {.id = "sink.udp",
     .label = "UDP output...",
     .help = "Send decoded audio to a UDP host and port.",
     .on_select = io_set_udp_out},
};

const NcMenuItem AUDIO_MENU_ITEMS[] = {
    {.id = "audio.current", .label_fn = lbl_current_output, .kind = NC_ITEM_STATUS},
    {.id = "audio.mute",
     .label_fn = lbl_out_mute,
     .help = "Silence the output without changing the sink.",
     .hotkey = "x",
     .on_select = switch_out_toggle_mute},
    {.id = "audio.switch",
     .label = "Switch output",
     .help = "Change the audio sink.",
     .submenu = AUDIO_SINK_ITEMS,
     .submenu_len = NC_LEN(AUDIO_SINK_ITEMS)},
    {.id = "audio.gain_d",
     .label_fn = lbl_gain_dig,
     .help = "Digital voice gain: 0 is automatic, otherwise 1..50.",
     .hotkey = "+ -",
     .on_select = io_set_gain_dig},
    {.id = "audio.gain_a",
     .label_fn = lbl_gain_ana,
     .help = "Analog monitor gain, 0..100.",
     .hotkey = "* /",
     .on_select = io_set_gain_ana},
    {.id = "audio.monitor",
     .label_fn = lbl_monitor,
     .help = "Pass the analog source audio through to the output.",
     .on_select = io_toggle_monitor},
    {.id = "audio.deemph",
     .label_fn = lbl_deemph,
     .help = "Cycle deemphasis: unset, off, 50 us, 75 us, NFM.",
     .on_select = act_deemph_cycle},
    {.id = "audio.lpf",
     .label_fn = lbl_audio_lpf,
     .help = "Post-demodulation low-pass cutoff in Hz; 0 turns it off.",
     .on_select = act_set_audio_lpf},
    {.id = "audio.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "audio.alert",
     .label_fn = lbl_call_alert,
     .help = "Beep on call events.",
     .hotkey = "a",
     .on_select = io_toggle_call_alert},
    {.id = "audio.alert_ev",
     .label_fn = lbl_call_alert_events,
     .help = "Which call events beep.",
     .on_select = io_select_call_alert_events},
};
const size_t AUDIO_MENU_ITEMS_LEN = NC_LEN(AUDIO_MENU_ITEMS);

// ============================================================================
// Recording & logs
// ============================================================================
static const NcMenuItem REC_SYMCAP_ITEMS[] = {
    {.id = "symcap.save",
     .label_fn = lbl_sym_save,
     .help = "Write raw symbols to a capture file for later replay.",
     .hotkey = "R",
     .on_select = io_save_symbol_capture},
    {.id = "symcap.stop",
     .label_fn = lbl_stop_symbol_capture,
     .help = "Close the capture file.",
     .hotkey = "r",
     .on_select = io_stop_symbol_saving},
    {.id = "symcap.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "symcap.last",
     .label_fn = lbl_replay_last,
     .help = "Replay the most recent capture. To replay another file, switch the input source to it (Input > "
             "Switch source).",
     .hotkey = "Space",
     .on_select = io_replay_last_symbol_bin},
    {.id = "symcap.stop_play",
     .label_fn = lbl_stop_symbol_playback,
     .help = "Stop the replay and restore the previous input.",
     .hotkey = "s",
     .on_select = io_stop_symbol_playback},
};

static const NcMenuItem REC_WAV_ITEMS[] = {
    {.id = "wav.percall",
     .label_fn = lbl_per_call_wav,
     .help = "Write one WAV file per call under the configured directory.",
     .hotkey = "P/p",
     .on_select = io_enable_per_call_wav},
    {.id = "wav.static",
     .label = "Static WAV file...",
     .help = "Append all decoded audio to one WAV file.",
     .on_select = act_static_wav},
    {.id = "wav.raw",
     .label = "Raw input WAV file...",
     .help = "Write the raw 48 kHz mono input to a WAV file.",
     .on_select = act_raw_wav},
};

static const NcMenuItem REC_EVENT_ITEMS[] = {
    {.id = "ev.file",
     .label_fn = lbl_event_log,
     .help = "Append the event history to a file.",
     .on_select = act_event_log_set},
    {.id = "ev.off",
     .label = "Stop event log",
     .help = "Stop writing events to the file.",
     .on_select = act_event_log_disable},
    {.id = "ev.payload",
     .label_fn = lbl_toggle_payload,
     .help = "Print raw payloads to the console.",
     .hotkey = "z",
     .on_select = act_toggle_payload},
    {.id = "ev.reset",
     .label = "Clear event history",
     .help = "Empty the on-screen event history.",
     .on_select = act_reset_eh},
};

static const NcMenuItem LRRP_ITEMS[] = {
    {.id = "lrrp.status", .label_fn = lbl_lrrp_current, .kind = NC_ITEM_STATUS},
    {.id = "lrrp.home",
     .label = "Write to ~/lrrp.txt (QGIS)",
     .help = "QGIS-friendly LRRP position log.",
     .on_select = lr_home},
    {.id = "lrrp.dsdp", .label = "Write to ./DSDPlus.LRRP", .help = "DSDPlus LRRP.exe format.", .on_select = lr_dsdp},
    {.id = "lrrp.custom", .label = "Custom file...", .help = "Choose the LRRP output path.", .on_select = lr_custom},
    {.id = "lrrp.off", .label = "Stop LRRP output", .help = "Stop writing positions.", .on_select = lr_off},
};

const NcMenuItem REC_MENU_ITEMS[] = {
    {.id = "rec.symcap",
     .label = "Symbol capture",
     .help = "Record symbols to a file and replay them.",
     .submenu = REC_SYMCAP_ITEMS,
     .submenu_len = NC_LEN(REC_SYMCAP_ITEMS)},
    {.id = "rec.wav",
     .label = "WAV files",
     .help = "Per-call, static and raw-input WAV recording.",
     .submenu = REC_WAV_ITEMS,
     .submenu_len = NC_LEN(REC_WAV_ITEMS)},
    {.id = "rec.events",
     .label = "Event log",
     .help = "Event log file, payload logging, history reset.",
     .submenu = REC_EVENT_ITEMS,
     .submenu_len = NC_LEN(REC_EVENT_ITEMS)},
    {.id = "rec.lrrp",
     .label = "LRRP output",
     .help = "Where DMR LRRP positions are written.",
     .submenu = LRRP_ITEMS,
     .submenu_len = NC_LEN(LRRP_ITEMS)},
    {.id = "rec.dsp",
     .label = "DSP structured output...",
     .help = "Write DSP structured output or the M17 stream under ./DSP/.",
     .on_select = act_dsp_out},
};
const size_t REC_MENU_ITEMS_LEN = NC_LEN(REC_MENU_ITEMS);

// ============================================================================
// Display
// ============================================================================
static const NcMenuItem DISPLAY_SECTION_ITEMS[] = {
    {.id = "sec.channels",
     .label_fn = lbl_ui_channels,
     .help = "Show the channels section.",
     .on_select = act_toggle_ui_channels},
#ifdef USE_RADIO
    {.id = "sec.dsp",
     .label_fn = lbl_dsp_panel,
     .help = "Show the compact DSP status panel.",
     .is_enabled = io_rtl_active,
     .on_select = act_toggle_dsp_panel},
#endif
    {.id = "sec.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "sec.p25m",
     .label_fn = lbl_ui_p25_metrics,
     .help = "Show the P25 metrics section.",
     .on_select = act_toggle_ui_p25_metrics},
    {.id = "sec.p25aff",
     .label_fn = lbl_ui_p25_affil,
     .help = "Show the P25 affiliations section (radio IDs).",
     .on_select = act_toggle_ui_p25_affil},
    {.id = "sec.p25ga",
     .label_fn = lbl_ui_p25_ga,
     .help = "Show the P25 group affiliation section (radio ID to talkgroup).",
     .hotkey = "T",
     .on_select = act_toggle_ui_p25_ga},
    {.id = "sec.p25nb",
     .label_fn = lbl_ui_p25_neighbors,
     .help = "Show the P25 neighbors section (adjacent and candidate frequencies).",
     .on_select = act_toggle_ui_p25_neighbors},
    {.id = "sec.p25iden",
     .label_fn = lbl_ui_p25_iden,
     .help = "Show the P25 IDEN plan table.",
     .on_select = act_toggle_ui_p25_iden},
    {.id = "sec.p25ccc",
     .label_fn = lbl_ui_p25_ccc,
     .help = "Show the P25 control-channel candidates list.",
     .on_select = act_toggle_ui_p25_ccc},
    {.id = "sec.p25call",
     .label_fn = lbl_ui_p25_callsign,
     .help = "Decode a callsign from WACN/system ID (may show false positives).",
     .on_select = act_toggle_ui_p25_callsign},
};

static const NcMenuItem DISPLAY_VIS_ITEMS[] = {
    {.id = "vis.const",
     .label_fn = lbl_vis_const,
     .help = "Constellation view of the demodulated symbols; < and > adjust the gate.",
     .hotkey = "o",
     .on_select = act_vis_const},
    {.id = "vis.const_norm",
     .label_fn = lbl_vis_const_norm,
     .help = "Scale the constellation radially (p99) or to the unit circle.",
     .hotkey = "n",
     .is_enabled = const_view_active,
     .on_select = act_vis_const_norm},
    {.id = "vis.eye",
     .label_fn = lbl_vis_eye,
     .help = "Eye diagram of the symbol timing.",
     .hotkey = "E",
     .on_select = act_vis_eye},
    {.id = "vis.eye_unicode",
     .label_fn = lbl_vis_eye_unicode,
     .help = "Draw the eye diagram with Unicode blocks instead of ASCII.",
     .hotkey = "U",
     .is_enabled = eye_view_active,
     .on_select = act_vis_eye_unicode},
    {.id = "vis.eye_color",
     .label_fn = lbl_vis_eye_color,
     .help = "Color the eye diagram.",
     .hotkey = "G",
     .is_enabled = eye_view_active,
     .on_select = act_vis_eye_color},
    {.id = "vis.fsk",
     .label_fn = lbl_vis_fsk,
     .help = "Histogram of the FSK symbol levels.",
     .hotkey = "K",
     .on_select = act_vis_fsk},
    {.id = "vis.spectrum",
     .label_fn = lbl_vis_spectrum,
     .help = "Spectrum analyzer; , and . change the FFT size.",
     .hotkey = "f",
     .on_select = act_vis_spectrum},
};

static const NcMenuItem DISPLAY_HIST_ITEMS[] = {
    {.id = "hist.mode",
     .label_fn = lbl_history_mode,
     .help = "Cycle the event history between short, long and off.",
     .hotkey = "h",
     .on_select = act_history_cycle},
    {.id = "hist.slot",
     .label_fn = lbl_history_slot,
     .help = "Which slot's events the history shows.",
     .hotkey = "\\",
     .on_select = act_eh_toggle_slot},
    {.id = "hist.prev",
     .label = "Previous event",
     .help = "Step back through the event history.",
     .hotkey = "[",
     .on_select = act_eh_prev},
    {.id = "hist.next",
     .label = "Next event",
     .help = "Step forward through the event history.",
     .hotkey = "]",
     .on_select = act_eh_next},
};

const NcMenuItem DISPLAY_MENU_ITEMS[] = {
    {.id = "disp.compact",
     .label_fn = lbl_ui_compact,
     .help = "Collapse the screen to a scanner-style layout.",
     .hotkey = "c",
     .on_select = act_toggle_ui_compact},
    {.id = "disp.sections",
     .label = "Sections",
     .help = "Which on-screen sections are shown.",
     .submenu = DISPLAY_SECTION_ITEMS,
     .submenu_len = NC_LEN(DISPLAY_SECTION_ITEMS)},
    {.id = "disp.vis",
     .label = "Visualizers",
     .help = "Constellation, eye diagram, FSK histogram, spectrum (RTL-SDR input).",
     .is_enabled = io_rtl_active,
     .submenu = DISPLAY_VIS_ITEMS,
     .submenu_len = NC_LEN(DISPLAY_VIS_ITEMS)},
    {.id = "disp.history",
     .label = "Event history",
     .help = "History mode, slot, and browsing.",
     .submenu = DISPLAY_HIST_ITEMS,
     .submenu_len = NC_LEN(DISPLAY_HIST_ITEMS)},
};
const size_t DISPLAY_MENU_ITEMS_LEN = NC_LEN(DISPLAY_MENU_ITEMS);

// ============================================================================
// Config
// ============================================================================
const NcMenuItem CONFIG_MENU_ITEMS[] = {
    {.id = "cfg.load",
     .label = "Load config...",
     .help = "Load settings from a config file into this session.",
     .on_select = act_config_load},
    {.id = "cfg.load_profile",
     .label = "Load profile...",
     .help = "Load a named profile from the active config without enabling autosave.",
     .on_select = act_config_load_profile},
    {.id = "cfg.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "cfg.save",
     .label = "Save config",
     .help = "Save to the active config path (the file loaded with --config or Load config...).",
     .on_select = act_config_save_current},
    {.id = "cfg.save_as",
     .label = "Save config as...",
     .help = "Choose a path and save the current settings there.",
     .on_select = act_config_save_as},
    {.id = "cfg.save_default",
     .label = "Save as default config",
     .help = "Save the current settings to the default config path and enable autosave.",
     .on_select = act_config_save_default},
};
const size_t CONFIG_MENU_ITEMS_LEN = NC_LEN(CONFIG_MENU_ITEMS);

// ============================================================================
// Advanced
// ============================================================================
const NcMenuItem ADV_MENU_ITEMS[] = {
    {.id = "adv.rt_sched",
     .label_fn = lbl_rt_sched,
     .help = "Best-effort realtime scheduling for the decode threads (needs privileges).",
     .on_select = act_rt_sched},
    {.id = "adv.mt", .label_fn = lbl_mt, .help = "Light worker pool for hot DSP loops.", .on_select = act_mt},
    {.id = "adv.ftz",
     .label_fn = lbl_ftz_daz,
     .help = "Flush-to-zero / denormals-are-zero on x86 SSE.",
     .on_select = act_toggle_ftz_daz},
    {.id = "adv.win_freeze",
     .label_fn = lbl_window_freeze,
     .help = "Freeze the symbol window selection and stop auto-centering.",
     .on_select = act_window_freeze_toggle},
    {.id = "adv.sim_nocar",
     .label = "Simulate no-carrier event",
     .help = "Pretend the carrier dropped, to exercise the trunking timers.",
     .hotkey = "Z",
     .on_select = act_sim_nocar},
    {.id = "adv.sep", .kind = NC_ITEM_SEPARATOR},
    {.id = "adv.env",
     .label = "Environment variable...",
     .help = "Set any DSD_NEO_* variable for this session.",
     .on_select = act_env_editor},
};
const size_t ADV_MENU_ITEMS_LEN = NC_LEN(ADV_MENU_ITEMS);
